name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    if: github.repository == 'rolldown/tsdown'
    uses: sxzz/workflows/.github/workflows/release.yml@main
    with:
      publish: true
      build: pnpm run build
      tag: ${{ contains(github.ref_name, 'alpha') && 'alpha' || contains(github.ref_name, 'beta') && 'beta' || contains(github.ref_name, 'rc') && 'rc' || '' }}
      stage: true
    permissions:
      contents: write
      id-token: write
