allowBuilds:
  dprint: true
  esbuild: true
  unrs-resolver: true
catalog:
  typescript: ^7
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@oxlint-tsgolint"
overrides:
  vite: ^7
packages:
  - packages/*
  - packages/stryker-js/*
