[[repos]]
name = "oh-my-pi"
url = "https://github.com/can1357/oh-my-pi"
tag_prefix = "v"

[[repos]]
name = "constitution"
url = "https://github.com/systemfsoftware/constitution"
branch = "main"

[[repos]]
name = "tsdown"
url = "https://github.com/rolldown/tsdown"
tag_prefix = "v"

[[repos]]
name = "deno-std"
url = "https://github.com/denoland/std"
tag_prefix = "release-"

[[repos]]
name = "effect"
url = "https://github.com/Effect-TS/effect"
tag_prefix = "effect@3."

[[repos]]
name = "storybook"
url = "https://github.com/storybookjs/storybook"
tag_prefix = "v"

[[repos]]
name = "oxc"
url = "https://github.com/oxc-project/oxc"
branch = "main"
