// Generated from the Rust N-API exports by `pnpm generate:native-types`.
// Do not edit this file directly.

/** Stateful decoder for autoregressive token streams. */
export declare class NativeDecodeStream {
  /** Adds one token and returns the next stable text chunk, if available. */
  step(id: number): string | null
}

/**
 * A tokenizer instance exposed to JavaScript.
 *
 * An [`Arc`] holds the [`tokenizers::Tokenizer`] and its special-token policy
 * while batch work runs in the background. The instance is immutable after
 * construction, so encoding and decoding may run concurrently. NAPI
 * finalization frees its CPU memory after JavaScript collects the wrapper.
 */
export declare class NativeTokenizer {
  /**
   * Loads a Hugging Face `tokenizer.json` file.
   *
   * With `parse_specials = true`, special-token strings resolve to their
   * ids. With `false`, raw text does not produce a special id.
   */
  static fromFile(path: string, parseSpecials: boolean): NativeTokenizer
  /**
   * Loads a Hugging Face `tokenizer.json` string. `parse_specials` behaves
   * as described by [`NativeTokenizer::from_file`].
   */
  static fromJson(json: string, parseSpecials: boolean): NativeTokenizer
  /**
   * Trains a new tokenizer according to `config`.
   *
   * The job runs on Tokio's blocking thread pool and cannot be cancelled.
   * During the corpus feed, `progress` receives
   * `[processedBytes, totalBytes]` every `progressEveryBytes` bytes and a
   * final `[total, total]`. A zero interval disables reports. The module
   * docs describe each architecture's pipeline. `parse_specials` behaves as
   * described by [`NativeTokenizer::from_file`].
   */
  static train(config: NativeTrainConfig, parseSpecials: boolean, progress: (event: [number, number]) => void, progressEveryBytes: number): Promise<NativeTokenizer>
  /** Total vocabulary size, including added and special tokens. */
  get vocabSize(): number
  /**
   * Resolves a token string to its id, or `null` if it is not in the
   * vocabulary.
   */
  tokenToId(token: string): number | null
  /**
   * Resolves a token id to its string, or `null` if the id is out of
   * range.
   */
  idToToken(id: number): string | null
  /**
   * Saves the tokenizer to `path` as a compact Hugging Face
   * `tokenizer.json` file.
   */
  save(path: string): void
  /**
   * Encodes `text` to token ids.
   *
   * `add_special_tokens` defaults to `true` and controls whether the
   * postprocessor adds template tokens such as `[CLS]` and `[SEP]`. The
   * `parse_specials` flag chosen at construction controls input segmentation.
   */
  encode(text: string, addSpecialTokens?: boolean | undefined | null): Uint32Array
  /**
   * Encodes a batch of texts, always adding special tokens.
   *
   * Tokio runs the job on its blocking thread pool. Rayon processes the
   * texts in parallel while preserving input order.
   */
  encodeBatch(texts: Array<string>): Promise<Array<Uint32Array>>
  /**
   * Decodes token ids to text. `skip_special_tokens` defaults to `false`.
   * When enabled, it omits special tokens instead of rendering their strings.
   */
  decode(ids: Array<number>, skipSpecialTokens?: boolean | undefined | null): string
  /** Creates a stateful decoder for an autoregressive token stream. */
  decodeStream(skipSpecialTokens?: boolean | undefined | null): NativeDecodeStream
  /**
   * Decodes a batch of id sequences. `skip_special_tokens` behaves as
   * described by [`NativeTokenizer::decode`].
   */
  decodeBatch(ids: Array<Array<number>>, skipSpecialTokens?: boolean | undefined | null): Array<string>
  /**
   * Renders a Hugging Face chat template against a JSON context. The module
   * docs describe the environment and its `raise_exception` and
   * `strftime_now` helpers.
   */
  applyChatTemplate(template: string, contextJson: string): string
}

/** Configuration for [`NativeTokenizer::train`]. */
export interface NativeTrainConfig {
  /**
   * Model architecture. Accepts `"BPE"`, `"WordPiece"`, `"Unigram"`, or
   * `"WordLevel"`. `train_tokenizer` defines each architecture's fixed
   * normalizer, pre-tokenizer, and decoder pipeline.
   */
  model: string
  /** Target vocabulary size, including special tokens. */
  vocabSize: number
  /** Minimum corpus frequency for a token to enter the vocabulary. */
  minFrequency: number
  /**
   * Special tokens to register, such as `"<|endoftext|>"`. Training adds
   * them to the vocabulary as special added tokens.
   */
  specialTokens: Array<string>
  /** Training corpus. */
  source: NativeTrainSource
}

/**
 * Training corpus selector for [`NativeTokenizer::train`].
 *
 * `tag = "Files"` requires `paths` and streams those files line by line.
 * `tag = "Texts"` requires `texts` and trains from those in-memory strings.
 */
export interface NativeTrainSource {
  /** Corpus kind. Must be `"Files"` or `"Texts"`. */
  tag: string
  /** File paths to stream when `tag` is `"Files"`. */
  paths?: Array<string> | undefined
  /** In-memory sequences to train on when `tag` is `"Texts"`. */
  texts?: Array<string> | undefined
}

export type NativeAddon = typeof import("./native-addon.js")
