// Generated from the Rust N-API exports by `pnpm generate:native-types`.
// Do not edit this file directly.

/**
 * Cooperative cancellation handle shared with async compute tasks.
 *
 * `cancel()` sets the flag and wakes the tokio notifier so a blocked
 * executor can abort. Kernels also poll the flag inside their loops
 * and return `Status::Cancelled` with "operation aborted".
 */
export declare class CancellationToken {
  constructor()
  cancel(): void
  get cancelled(): boolean
}

/**
 * A compiled CPU program exported to JavaScript. `ProgramCache` stores up to
 * 64 executables in an LRU cache keyed by structural hash. Compiling the same
 * graph reuses the cached artifact. Each hit revalidates generated bindings
 * against the cached signature.
 */
export declare class Executable {
  get stateful(): boolean
  get batch(): number
  get allowsWindowEviction(): boolean
  get diagnostics(): NativeExecutableDiagnostics
  get layers(): number
  get kvHeads(): number
  get headDim(): number
  get kdaLayers(): number
  get kdaHeads(): number
  get kdaHeadDim(): number
  get kdaValueDim(): number
  get convLayers(): number
  get convChannels(): number
  get convKernel(): number
  /**
   * Runs the program asynchronously on the worker pool.
   *
   * Stateless executables take `inputs` and optional `scalars`. Stateful
   * decode executables also take one [`NativeKvSequence`] and its new tokens
   * for each batch lane. They run under a `CpuState` transaction and commit
   * cache updates only if not cancelled. Cancellation returns
   * `Status::Cancelled` and leaves all sequence state uncommitted.
   */
  execute(inputs: Array<NativeTensor>, scalars: Array<number>, sequences?: Array<NativeKvSequence> | undefined | null, slots?: Array<number> | undefined | null, activeMask?: Array<boolean> | undefined | null, validLengths?: Array<number> | undefined | null, advances?: Array<number> | undefined | null, tokens?: Array<Array<number>> | undefined | null, cancellationToken?: CancellationToken | undefined | null): Promise<Array<NativeTensor>>
  /**
   * Runs a stateful program and samples its active outputs before committing
   * the sequence transaction. Does not publish output tensor wrappers.
   */
  executeSampled(inputs: Array<NativeTensor>, sequences: Array<NativeKvSequence>, slots: Array<number>, activeMask: Array<boolean>, validLengths: Array<number>, advances: Array<number>, tokens: Array<Array<number>>, sampling: Array<NativeSamplingOptions>, cancellationToken?: CancellationToken | undefined | null): Promise<Array<number>>
  executeSpeculative(proposer: Executable, targetSequences: Array<NativeKvSequence>, proposerSequences: Array<NativeKvSequence>, slots: Array<number>, pendingTokens: Array<number>, sampling: Array<NativeInferenceSamplingOptions>, sequenceIds: Array<NativeU64>, absolutePositions: Array<NativeU64>, maxDraftTokens: number, pageLimits: Array<number>, eosTokens: Array<Array<number>>, cancellationToken?: CancellationToken | undefined | null): Promise<Array<Array<number>>>
}

/**
 * A lazy CPU graph node whose methods build graph structure without running
 * it. Materialize it with `compile` and `execute`. Use `grad` for
 * reverse-mode gradients.
 */
export declare class LazyTensor {
  get shape(): Array<number>
  get dtype(): string
  metadata(): [Array<number>, string]
  static zeros(shape: Array<number>, dtype?: NativeDType | undefined | null): LazyTensor
  static ones(shape: Array<number>, dtype?: NativeDType | undefined | null): LazyTensor
  static full(shape: Array<number>, value: number, dtype?: NativeDType | undefined | null): LazyTensor
  static randn(shape: Array<number>, dtype?: NativeDType | undefined | null): LazyTensor
  static uniform(shape: Array<number>, lo: number, hi: number, dtype?: NativeDType | undefined | null): LazyTensor
  static arange(start: number, end: number, step: number, dtype?: NativeDType | undefined | null): LazyTensor
  static eye(n: number, dtype?: NativeDType | undefined | null): LazyTensor
  static constant(value: number, dtype?: NativeDType | undefined | null): LazyTensor
  static fromBytes(data: Uint8Array, shape: Array<number>, dtype?: NativeDType | undefined | null): LazyTensor
  static fromMaterialized(tensor: NativeTensor): LazyTensor
  static input(slot: number, shape: Array<number>, dtype?: NativeDType | undefined | null): LazyTensor
  static scalarInput(slot: number, dtype?: NativeDType | undefined | null): LazyTensor
  add(other: LazyTensor): LazyTensor
  sub(other: LazyTensor): LazyTensor
  mul(other: LazyTensor): LazyTensor
  div(other: LazyTensor): LazyTensor
  maximum(other: LazyTensor): LazyTensor
  minimum(other: LazyTensor): LazyTensor
  eq(other: LazyTensor): LazyTensor
  gt(other: LazyTensor): LazyTensor
  lt(other: LazyTensor): LazyTensor
  ge(other: LazyTensor): LazyTensor
  le(other: LazyTensor): LazyTensor
  matmul(other: LazyTensor): LazyTensor
  inverse(): LazyTensor
  det(): LazyTensor
  solve(other: LazyTensor): LazyTensor
  neg(): LazyTensor
  abs(): LazyTensor
  sqrt(): LazyTensor
  exp(): LazyTensor
  tanh(): LazyTensor
  gelu(approximate?: boolean | undefined | null): LazyTensor
  relu(): LazyTensor
  erf(): LazyTensor
  floor(): LazyTensor
  ceil(): LazyTensor
  round(): LazyTensor
  sign(): LazyTensor
  whereCond(a: LazyTensor, b: LazyTensor): LazyTensor
  argmax(dim: number): LazyTensor
  argmin(dim: number): LazyTensor
  cumsum(dim: number): LazyTensor
  indexSelect(dim: number, indexes: LazyTensor): LazyTensor
  scatterAdd(dim: number, indexes: LazyTensor, src: LazyTensor): LazyTensor
  gather(dim: number, indexes: LazyTensor): LazyTensor
  crossEntropy(target: LazyTensor, ignoreIndex: number): LazyTensor
  scaledDotProductAttention(k: LazyTensor, v: LazyTensor, scale: number, causal: boolean, window: number): LazyTensor
  kdaChunk(k: LazyTensor, v: LazyTensor, logDecay: LazyTensor, beta: LazyTensor, scale: number): LazyTensor
  shortConv1d(weight: LazyTensor): LazyTensor
  positionEmbedding(seqLen: number): LazyTensor
  rotaryEmbedding(seqLen: number, theta: number, layout: string): LazyTensor
  layerNorm(weight: LazyTensor, bias: LazyTensor, eps: number): LazyTensor
  rmsNorm(weight: LazyTensor | undefined | null, eps: number): LazyTensor
  linear(weight: LazyTensor, bias: LazyTensor): LazyTensor
  quantizedLinear(weight: LazyTensor, bias: LazyTensor | undefined | null, encoding: string, rows: number, columns: number): LazyTensor
  quantizedEmbedding(weight: LazyTensor, encoding: string, rows: number, columns: number, paddingIndex?: number | undefined | null): LazyTensor
  conv1d(weight: LazyTensor, stride: number, padding: number, dilation: number, groups: number): LazyTensor
  conv2d(weight: LazyTensor, stride: number, padding: number, dilation: number, groups: number): LazyTensor
  log(): LazyTensor
  sin(): LazyTensor
  cos(): LazyTensor
  pow(exp: number): LazyTensor
  cast(dtype: NativeDType): LazyTensor
  sum(dims: Array<number>, keepdims: boolean): LazyTensor
  prod(dims: Array<number>, keepdims: boolean): LazyTensor
  mean(dims: Array<number>, keepdims: boolean): LazyTensor
  max(dims: Array<number>, keepdims: boolean): LazyTensor
  min(dims: Array<number>, keepdims: boolean): LazyTensor
  reshape(shape: Array<number>): LazyTensor
  permute(dims: Array<number>): LazyTensor
  slice(ranges: Array<Array<number>>): LazyTensor
  concat(other: LazyTensor, dim: number): LazyTensor
  broadcastTo(shape: Array<number>): LazyTensor
  stopGradient(): LazyTensor
  expose(name: string): LazyTensor
  /**
   * Walks the lazy graph reachable from this node and returns each exposure's
   * name and wrapped tensor in deterministic first-visit order. Duplicate
   * names are a caller error.
   */
  exposures(): Array<NativeExposure>
  checkpoint(): LazyTensor
  vmap(x: LazyTensor, batchedX: LazyTensor, dim: number): LazyTensor
  adamwStep(grad: LazyTensor, m: LazyTensor, v: LazyTensor, lr: LazyTensor, c1: LazyTensor, c2: LazyTensor, beta1: number, beta2: number, eps: number, weightDecay: number): LazyTensor
  adamwOut(index: number): LazyTensor
  sgdStep(grad: LazyTensor, velocity: LazyTensor, first: LazyTensor, lr: LazyTensor, momentum: number, dampening: number, nesterov: boolean, weightDecay: number): LazyTensor
  sgdOut(index: number): LazyTensor
}

/**
 * One named exposure in a lazy graph. Contains the name and wrapped tensor
 * handle from the exposure node's child.
 */
export declare class NativeExposure {
  get name(): string
  get tensor(): LazyTensor
}

export declare class NativeInferenceArtifact {
  open(): NativeInferenceSession
  diagnostics(): NativeInferenceDiagnostics
}

export declare class NativeInferenceSequence {
  get sequenceId(): NativeU64
}

export declare class NativeInferenceSession {
  sequence(sequenceId: NativeU64): NativeInferenceSequence
  add(prompts: Array<NativeTensor>, sampling: Array<NativeInferenceSamplingOptions>, maxTokens: Array<number>, eosTokens: Array<Array<number>>, cancellationToken?: CancellationToken | undefined | null): Promise<NativeInferenceRoundResult>
  runRound(sequences: Array<NativeInferenceSequence>, sampling: Array<NativeInferenceSamplingOverrides>, cancellationToken?: CancellationToken | undefined | null): Promise<NativeInferenceRoundResult>
  acknowledge(roundId: NativeU64): void
  finish(sequences: Array<NativeInferenceSequence>): void
  inspect(sequence: NativeInferenceSequence): NativeInferenceInspection
  close(): void
}

/**
 * Paged KV-cache pool for stateful decoding.
 *
 * The pool owns per-layer key and value slabs of `max_tokens` positions in
 * `f32`, `f16`, `bf16`, or int8-quantized `u8`. Sequences lease
 * `block_size` pages. Identical token prefixes share cached blocks. The pool
 * also validates and allocates optional recurrent KDA and convolution state.
 */
export declare class NativeKvPool {
  /**
   * Creates a pool. Geometries must be all zero or all positive.
   * `max_tokens` must be a positive multiple of `block_size`, whose
   * default is 16.
   */
  constructor(layers: number, kvHeads: number, headDim: number, maxTokens: number, blockSize?: number | undefined | null, dtype?: NativeDType | undefined | null, recurrent?: NativeRecurrentStateSchema | undefined | null)
  get capacity(): number
  get freeBlocks(): number
  get cachedBlocks(): number
  makeSequence(): NativeKvSequence
}

/**
 * One decode sequence's handle into a [`NativeKvPool`]. It holds leased
 * blocks, the committed cursor, pending tokens, and recurrent or convolution
 * state. `release`, drop, or JS finalization returns blocks to the pool
 * exactly once. `run_lock` serializes execution against release.
 */
export declare class NativeKvSequence {
  get cursor(): number
  release(): void
  prefillMatch(tokens: Array<number>): number
}

/**
 * A materialized CPU tensor exported to JavaScript.
 *
 * Wraps the value in a graph [`LeafSlot`] so it can feed compiled programs
 * as a generated binding. Wrap, clear, and finalize mirror the tracked byte
 * size to V8's external memory accounting.
 */
export declare class NativeTensor {
  clear(): void
  get shape(): Array<number>
  get dtype(): string
  get device(): string
  readback(token?: CancellationToken | undefined | null): Promise<ArrayBuffer>
  sample(temperature: number, topK: number, topP: number, seed: number, counter: number, cancellationToken?: CancellationToken | undefined | null): Promise<number>
}

/**
 * Compiles lazy roots into an [`Executable`]. A KV `state` schema first
 * specializes the graph for paged KV attention and a state cursor, then
 * includes that state plan in the executable. `cache_key` enables the
 * process-wide executable cache.
 */
export declare function compile(roots: Array<LazyTensor>, options?: NativeCompileOptions | undefined | null, state?: NativeKvStateSchema | undefined | null, cacheKey?: string | undefined | null): Executable

export declare function compileInference(targetPrefill: Executable, targetDecode: Executable, targetVerify: Executable | undefined | null, targetPool: NativeKvPool, proposerPrefill: Executable | undefined | null, proposerDecode: Executable | undefined | null, proposerPool: NativeKvPool | undefined | null, maxDraftTokens: number, batchSize: number, tokenDtype: NativeDType, sampling: NativeInferenceSamplingOptions, proposerPlan?: NativeInferenceProposerPlan | undefined | null, sharedTensors?: Array<NativeTensor> | undefined | null, stageExecutables?: Array<Executable> | undefined | null, replayPrefill?: Executable | undefined | null, replayDecode?: Executable | undefined | null, replayVerify?: Executable | undefined | null, replayPool?: NativeKvPool | undefined | null): NativeInferenceArtifact

/**
 * Total bytes attributed to live [`NativeTensor`] values. V8's external
 * memory accounting mirrors this value.
 */
export declare function externalMemoryBytes(): number

/**
 * Reverse-mode gradients of `loss` with respect to each tensor in `wrt`,
 * in the same order.
 */
export declare function grad(loss: LazyTensor, wrt: Array<LazyTensor>): Array<LazyTensor>

/**
 * Parses the GGUF header at `path` and returns its metadata and tensor
 * catalog without reading payloads.
 */
export declare function inspectGguf(path: string, token?: CancellationToken | undefined | null): Promise<NativeGgufInspection>

/** Returns `true` because the CPU backend is available on every target. */
export declare function isAvailable(): boolean

/**
 * Loads every tensor of the GGUF archive at `path` into CPU tensors.
 * Direct f32 loading requires a little-endian target. Quantized formats use
 * packed `u8` payloads.
 */
export declare function loadGguf(path: string, token?: CancellationToken | undefined | null): Promise<NativeGgufArchive>

/**
 * Loads a safetensors archive, rejecting unsupported dtypes and malformed
 * byte lengths.
 */
export declare function loadTensors(path: string, token?: CancellationToken | undefined | null): Promise<NativeSafetensorsArchive>

export interface NativeCompileOptions {
  optimize?: boolean | undefined
  constantWeights?: boolean | undefined
}

export interface NativeCompilePhaseDiagnostics {
  phase: string
  nanoseconds: number
}

export declare const enum NativeCurrentBlockAttention {
  Causal = 'Causal',
  Bidirectional = 'Bidirectional'
}

export declare const enum NativeDecodeOutputSelection {
  AllRows = 'AllRows',
  SplitLastTokenRow = 'SplitLastTokenRow',
  BatchedLastTokenRow = 'BatchedLastTokenRow'
}

export declare const enum NativeDType {
  F32 = 'f32',
  F64 = 'f64',
  I64 = 'i64',
  U8 = 'u8',
  U32 = 'u32',
  F16 = 'f16',
  BF16 = 'bf16'
}

export interface NativeExecutableDiagnostics {
  semanticNodesBeforeOptimization: number
  semanticNodesAfterOptimization: number
  instructions: Array<NativeInstructionDiagnostics>
  pipelineCount: number
  commandCount: number
  synchronizationCount: number
  memory: NativeMemoryDiagnostics
  compilePhases: Array<NativeCompilePhaseDiagnostics>
}

export interface NativeGgufArchive {
  entries: Array<NativeGgufLoadedEntry>
}

export interface NativeGgufInspection {
  metadata: Array<NativeGgufMetadataEntry>
  tensors: Array<NativeGgufTensorDescriptor>
}

export interface NativeGgufLoadedEntry {
  descriptor: NativeGgufTensorDescriptor
  tensor: NativeTensor
}

export interface NativeGgufMetadataEntry {
  key: string
  kind: string
  numberValue?: number | undefined
  stringValue?: string | undefined
  booleanValue?: boolean | undefined
  numberArray?: Array<number> | undefined
  stringArray?: Array<string> | undefined
  booleanArray?: Array<boolean> | undefined
}

export interface NativeGgufTensorDescriptor {
  name: string
  format: string
  logicalShape: Array<number>
  logicalDtype: string
  physicalShape: Array<number>
  physicalDtype: string
}

export interface NativeHistoryLookupLayout {
  id: string
  minMatchTokens: number
  maxMatchTokens: number
}

export interface NativeInferenceDiagnostics {
  roundsStarted: NativeU64
  roundsCompleted: NativeU64
  roundsRecovered: NativeU64
  lastRoundId?: NativeU64 | undefined
  lastFailurePhase?: string | undefined
  ordinaryRounds: NativeU64
  speculativeRounds: NativeU64
  proposedTokens: NativeU64
  acceptedTokens: NativeU64
  emittedTokens: NativeU64
  provisionalBlocks: NativeU64
  rolledBackBlocks: NativeU64
  draftNanos: NativeU64
  verificationNanos: NativeU64
  acceptedLengthHistogram: Array<NativeU64>
  targetPoolHighWaterBlocks: NativeU64
  proposerPoolHighWaterBlocks?: NativeU64 | undefined
}

export interface NativeInferenceHiddenTap {
  name: string
  /** Root index in each target executable. Root zero remains target logits. */
  outputRoot: number
  value: NativeInferenceValueMetadata
}

export interface NativeInferenceInspection {
  sequenceId: NativeU64
  cursor: NativeU64
  terminal?: string | undefined
}

export interface NativeInferenceOutputPlan {
  topology: string
  probabilities: string
  tokenIds: NativeInferenceValueRef
  probabilityRows?: NativeInferenceValueRef | undefined
  parents?: NativeInferenceValueRef | undefined
  confidence?: NativeInferenceValueRef | undefined
}

export interface NativeInferenceProposerPlan {
  vocabulary: number
  tokenMapFingerprint: string
  hiddenTaps: Array<NativeInferenceHiddenTap>
  prefillHiddenTaps?: Array<NativeInferenceHiddenTap> | undefined
  verifyHiddenTaps?: Array<NativeInferenceHiddenTap> | undefined
  sharedTensors: Array<NativeInferenceSharedTensor>
  stages: Array<NativeInferenceStage>
  state: NativeInferenceStatePlan
  output: NativeInferenceOutputPlan
  tokenMap: NativeInferenceTokenMap
  trainedMaxRows: number
}

export interface NativeInferenceRoundResult {
  roundId: NativeU64
  recovered: boolean
  pages: Array<NativeInferenceTokenPage>
}

export interface NativeInferenceSamplingOptions {
  temperature: number
  topK: number
  topP: number
  seed: NativeU64
}

export interface NativeInferenceSamplingOverrides {
  temperature?: number | undefined
  topK?: number | undefined
  topP?: number | undefined
  seed?: NativeU64 | undefined
}

export interface NativeInferenceSharedTensor {
  /** `TokenEmbedding` or `LmHead`. */
  kind: string
  name: string
  value: NativeInferenceValueMetadata
}

export interface NativeInferenceStage {
  /** Stable operation identifier, for example `ParallelBlock`. */
  operationId: string
  /** Stable layout/search identifier when the operation has one. */
  layoutId?: string | undefined
  historyLookup?: NativeHistoryLookupLayout | undefined
  inputs: Array<NativeInferenceStageInput>
  outputs: Array<NativeInferenceValueMetadata>
}

export interface NativeInferenceStageInput {
  slot: number
  value: NativeInferenceValueRef
}

export interface NativeInferenceStatePlan {
  /** `None` or `Kv`. */
  kind: string
  schemaId?: string | undefined
  /** `None`, `AutoregressiveChain`, or `Replay`. */
  commitKind: string
  commitStages: Array<number>
}

export interface NativeInferenceTokenMap {
  /** `Identity` or `Table`. */
  kind: string
  fingerprint: string
  proposerVocabulary?: number | undefined
  targetIds?: Array<number> | undefined
}

export interface NativeInferenceTokenPage {
  sequenceId: NativeU64
  tokens: Array<number>
  stopReason?: string | undefined
}

export interface NativeInferenceValueMetadata {
  dtype: NativeDType
  shape: Array<number>
}

export interface NativeInferenceValueRef {
  /**
   * PendingTokens, CandidatePrefix, CommittedHistory, TargetHidden,
   * SharedTokenEmbedding, SharedLmHead, or StageOutput.
   */
  kind: string
  targetOutput?: number | undefined
  stage?: number | undefined
  output?: number | undefined
  /** Required concrete metadata for external token/history values. */
  value?: NativeInferenceValueMetadata | undefined
  /** Select `[physicalLane, ..]` as a one-row view. Valid only for TargetHidden. */
  selectTargetRow?: boolean | undefined
}

export interface NativeInstructionDiagnostics {
  kind: string
  count: number
}

export interface NativeKvStateSchema {
  maxTokens: number
  blockSize: number
  kvDtype: NativeDType
  window?: number | undefined
  batch: number
  packedCausalChains?: NativePackedCausalChainsLayout | undefined
  lastTokenRow?: boolean | undefined
  outputSelections?: Array<NativeDecodeOutputSelection> | undefined
  currentBlockAttention?: NativeCurrentBlockAttention | undefined
}

export interface NativeMemoryDiagnostics {
  externalBytes: number
  persistentBytes: number
  stateBytes: number
  outputBytes: number
  workspaceBytes: number
  transactionBytes: number
  peakLiveBytes: number
  packingOverheadBytes: number
}

export interface NativePackedCausalChainsLayout {
  rowsPerSequence: number
}

export interface NativeRecurrentStateSchema {
  kdaLayers: number
  kdaHeads: number
  kdaHeadDim: number
  kdaValueDim: number
  convLayers: number
  convChannels: number
  convKernel: number
}

/** A loaded safetensors archive with entries sorted by name and metadata. */
export interface NativeSafetensorsArchive {
  entries: Array<NativeSafetensorsEntry>
  metadata: Record<string, string>
}

/** One named tensor of a loaded safetensors archive. */
export interface NativeSafetensorsEntry {
  name: string
  tensor: NativeTensor
}

export interface NativeSamplingOptions {
  temperature: number
  topK: number
  topP: number
  seed: number
  counter: number
}

/**
 * Serializes tensors to a safetensors archive. Writes a temporary file and
 * renames it atomically after validating that names are unique.
 */
export declare function saveTensors(path: string, names: Array<string>, tensors: Array<NativeTensor>, metadata: Record<string, string>, token?: CancellationToken | undefined | null): Promise<void>

export type NativeAddon = typeof import("./native-addon.js")
