import { findMinimumForRange } from 'verkit'
import { resolveComma, toArray } from '../utils/general.ts'
import type { Logger } from '../utils/logger.ts'
import type { Ansis } from 'ansis'
import type { PackageJson } from 'pkg-types'

// Generated by `scripts/generate-target.ts`
const BASELINE_WIDELY_AVAILABLE_TARGET: string[] = [
  'chrome111',
  'edge111',
  'firefox114',
  'safari16.4',
  'ios16.4',
]

export function expandBaselineTarget(targets: string[]): string[] {
  return targets.flatMap((t) =>
    t === 'baseline-widely-available' ? BASELINE_WIDELY_AVAILABLE_TARGET : t,
  )
}

export function resolveTarget(
  logger: Logger,
  target: string | string[] | false | undefined,
  color: Ansis,
  pkg?: PackageJson,
  nameLabel?: string,
): string[] | undefined {
  if (target === false) return
  if (target == null) {
    const pkgTarget = resolvePackageTarget(pkg)
    if (pkgTarget) {
      target = pkgTarget
    } else {
      return
    }
  }

  if (typeof target === 'number') {
    throw new TypeError(`Invalid target: ${target}`)
  }
  const targets = expandBaselineTarget(resolveComma(toArray(target)))
  if (targets.length)
    logger.info(
      nameLabel,
      `target${targets.length > 1 ? 's' : ''}: ${color(targets.join(', '))}`,
    )

  return targets
}

export function resolvePackageTarget(pkg?: PackageJson): string | undefined {
  const nodeVersion = pkg?.engines?.node
  if (!nodeVersion) return
  const nodeMinVersion = findMinimumForRange(nodeVersion)
  if (!nodeMinVersion) return
  if (nodeMinVersion === '0.0.0') return
  return `node${nodeMinVersion}`
}
