// Code generated by packages/ttsc/tools/shim_audit -fix. DO NOT EDIT.
//
// Completes every exposed enum family: re-exports each member not already
// re-exported elsewhere in the shim package, so a plugin that can name the
// enum type can name all of its values. Prevents the #230 class (a sibling
// const silently missing). Regenerate after a typescript-go bump with
// `pnpm --filter ttsc shim:audit -fix`.

package checker

import innerchecker "github.com/microsoft/typescript-go/internal/checker"

const (
  ElementFlagsFixed                                     = innerchecker.ElementFlagsFixed
  ElementFlagsNonRequired                               = innerchecker.ElementFlagsNonRequired
  ElementFlagsNonRest                                   = innerchecker.ElementFlagsNonRest
  ElementFlagsVariable                                  = innerchecker.ElementFlagsVariable
  IterationTypeKindNext                                 = innerchecker.IterationTypeKindNext
  IterationTypeKindReturn                               = innerchecker.IterationTypeKindReturn
  IterationUseAllowsAsyncIterablesFlag                  = innerchecker.IterationUseAllowsAsyncIterablesFlag
  IterationUseAllowsStringInputFlag                     = innerchecker.IterationUseAllowsStringInputFlag
  IterationUseAllowsSyncIterablesFlag                   = innerchecker.IterationUseAllowsSyncIterablesFlag
  IterationUseAsyncGeneratorReturnType                  = innerchecker.IterationUseAsyncGeneratorReturnType
  IterationUseAsyncYieldStar                            = innerchecker.IterationUseAsyncYieldStar
  IterationUseCacheFlags                                = innerchecker.IterationUseCacheFlags
  IterationUseDestructuring                             = innerchecker.IterationUseDestructuring
  IterationUseDestructuringFlag                         = innerchecker.IterationUseDestructuringFlag
  IterationUseForAwaitOf                                = innerchecker.IterationUseForAwaitOf
  IterationUseForOf                                     = innerchecker.IterationUseForOf
  IterationUseForOfFlag                                 = innerchecker.IterationUseForOfFlag
  IterationUseGeneratorReturnType                       = innerchecker.IterationUseGeneratorReturnType
  IterationUsePossiblyOutOfBounds                       = innerchecker.IterationUsePossiblyOutOfBounds
  IterationUseSpread                                    = innerchecker.IterationUseSpread
  IterationUseSpreadFlag                                = innerchecker.IterationUseSpreadFlag
  IterationUseYieldStar                                 = innerchecker.IterationUseYieldStar
  IterationUseYieldStarFlag                             = innerchecker.IterationUseYieldStarFlag
  ObjectFlagsAnonymous                                  = innerchecker.ObjectFlagsAnonymous
  ObjectFlagsArrayLiteral                               = innerchecker.ObjectFlagsArrayLiteral
  ObjectFlagsContainsIntersections                      = innerchecker.ObjectFlagsContainsIntersections
  ObjectFlagsContainsObjectOrArrayLiteral               = innerchecker.ObjectFlagsContainsObjectOrArrayLiteral
  ObjectFlagsContainsSpread                             = innerchecker.ObjectFlagsContainsSpread
  ObjectFlagsContainsWideningType                       = innerchecker.ObjectFlagsContainsWideningType
  ObjectFlagsCouldContainTypeVariables                  = innerchecker.ObjectFlagsCouldContainTypeVariables
  ObjectFlagsCouldContainTypeVariablesComputed          = innerchecker.ObjectFlagsCouldContainTypeVariablesComputed
  ObjectFlagsEvolvingArray                              = innerchecker.ObjectFlagsEvolvingArray
  ObjectFlagsFreshLiteral                               = innerchecker.ObjectFlagsFreshLiteral
  ObjectFlagsFromTypeNode                               = innerchecker.ObjectFlagsFromTypeNode
  ObjectFlagsIdenticalBaseTypeCalculated                = innerchecker.ObjectFlagsIdenticalBaseTypeCalculated
  ObjectFlagsIdenticalBaseTypeExists                    = innerchecker.ObjectFlagsIdenticalBaseTypeExists
  ObjectFlagsInstantiated                               = innerchecker.ObjectFlagsInstantiated
  ObjectFlagsInstantiatedMapped                         = innerchecker.ObjectFlagsInstantiatedMapped
  ObjectFlagsInstantiationExpressionType                = innerchecker.ObjectFlagsInstantiationExpressionType
  ObjectFlagsIsClassInstanceClone                       = innerchecker.ObjectFlagsIsClassInstanceClone
  ObjectFlagsIsConstrainedTypeVariable                  = innerchecker.ObjectFlagsIsConstrainedTypeVariable
  ObjectFlagsIsGenericIndexType                         = innerchecker.ObjectFlagsIsGenericIndexType
  ObjectFlagsIsGenericObjectType                        = innerchecker.ObjectFlagsIsGenericObjectType
  ObjectFlagsIsGenericType                              = innerchecker.ObjectFlagsIsGenericType
  ObjectFlagsIsGenericTypeComputed                      = innerchecker.ObjectFlagsIsGenericTypeComputed
  ObjectFlagsIsNeverIntersection                        = innerchecker.ObjectFlagsIsNeverIntersection
  ObjectFlagsIsNeverIntersectionComputed                = innerchecker.ObjectFlagsIsNeverIntersectionComputed
  ObjectFlagsIsUnknownLikeUnion                         = innerchecker.ObjectFlagsIsUnknownLikeUnion
  ObjectFlagsIsUnknownLikeUnionComputed                 = innerchecker.ObjectFlagsIsUnknownLikeUnionComputed
  ObjectFlagsJSLiteral                                  = innerchecker.ObjectFlagsJSLiteral
  ObjectFlagsJsxAttributes                              = innerchecker.ObjectFlagsJsxAttributes
  ObjectFlagsMapped                                     = innerchecker.ObjectFlagsMapped
  ObjectFlagsMembersResolved                            = innerchecker.ObjectFlagsMembersResolved
  ObjectFlagsNonInferrableType                          = innerchecker.ObjectFlagsNonInferrableType
  ObjectFlagsNone                                       = innerchecker.ObjectFlagsNone
  ObjectFlagsObjectLiteral                              = innerchecker.ObjectFlagsObjectLiteral
  ObjectFlagsObjectLiteralPatternWithComputedProperties = innerchecker.ObjectFlagsObjectLiteralPatternWithComputedProperties
  ObjectFlagsObjectRestType                             = innerchecker.ObjectFlagsObjectRestType
  ObjectFlagsObjectTypeKindMask                         = innerchecker.ObjectFlagsObjectTypeKindMask
  ObjectFlagsPrimitiveUnion                             = innerchecker.ObjectFlagsPrimitiveUnion
  ObjectFlagsPropagatingFlags                           = innerchecker.ObjectFlagsPropagatingFlags
  ObjectFlagsRequiresWidening                           = innerchecker.ObjectFlagsRequiresWidening
  ObjectFlagsReverseMapped                              = innerchecker.ObjectFlagsReverseMapped
  ObjectFlagsSingleSignatureType                        = innerchecker.ObjectFlagsSingleSignatureType
  ObjectFlagsTuple                                      = innerchecker.ObjectFlagsTuple
  ObjectFlagsUnresolvedMembers                          = innerchecker.ObjectFlagsUnresolvedMembers
  SignatureKindConstruct                                = innerchecker.SignatureKindConstruct
  TypeFlagsAnyOrUnknown                                 = innerchecker.TypeFlagsAnyOrUnknown
  TypeFlagsBigInt                                       = innerchecker.TypeFlagsBigInt
  TypeFlagsBoolean                                      = innerchecker.TypeFlagsBoolean
  TypeFlagsConditional                                  = innerchecker.TypeFlagsConditional
  TypeFlagsDefinitelyFalsy                              = innerchecker.TypeFlagsDefinitelyFalsy
  TypeFlagsDefinitelyNonNullable                        = innerchecker.TypeFlagsDefinitelyNonNullable
  TypeFlagsDisjointDomains                              = innerchecker.TypeFlagsDisjointDomains
  TypeFlagsESSymbol                                     = innerchecker.TypeFlagsESSymbol
  TypeFlagsESSymbolLike                                 = innerchecker.TypeFlagsESSymbolLike
  TypeFlagsFreshable                                    = innerchecker.TypeFlagsFreshable
  TypeFlagsIncludesConstrainedTypeVariable              = innerchecker.TypeFlagsIncludesConstrainedTypeVariable
  TypeFlagsIncludesEmptyObject                          = innerchecker.TypeFlagsIncludesEmptyObject
  TypeFlagsIncludesError                                = innerchecker.TypeFlagsIncludesError
  TypeFlagsIncludesInstantiable                         = innerchecker.TypeFlagsIncludesInstantiable
  TypeFlagsIncludesMask                                 = innerchecker.TypeFlagsIncludesMask
  TypeFlagsIncludesMissingType                          = innerchecker.TypeFlagsIncludesMissingType
  TypeFlagsIncludesNonWideningType                      = innerchecker.TypeFlagsIncludesNonWideningType
  TypeFlagsIncludesWildcard                             = innerchecker.TypeFlagsIncludesWildcard
  TypeFlagsIndex                                        = innerchecker.TypeFlagsIndex
  TypeFlagsIndexedAccess                                = innerchecker.TypeFlagsIndexedAccess
  TypeFlagsInstantiable                                 = innerchecker.TypeFlagsInstantiable
  TypeFlagsInstantiableNonPrimitive                     = innerchecker.TypeFlagsInstantiableNonPrimitive
  TypeFlagsInstantiablePrimitive                        = innerchecker.TypeFlagsInstantiablePrimitive
  TypeFlagsIntrinsic                                    = innerchecker.TypeFlagsIntrinsic
  TypeFlagsNarrowable                                   = innerchecker.TypeFlagsNarrowable
  TypeFlagsNonPrimitive                                 = innerchecker.TypeFlagsNonPrimitive
  TypeFlagsNone                                         = innerchecker.TypeFlagsNone
  TypeFlagsNotPrimitiveUnion                            = innerchecker.TypeFlagsNotPrimitiveUnion
  TypeFlagsNullable                                     = innerchecker.TypeFlagsNullable
  TypeFlagsNumber                                       = innerchecker.TypeFlagsNumber
  TypeFlagsObjectFlagsType                              = innerchecker.TypeFlagsObjectFlagsType
  TypeFlagsPossiblyFalsy                                = innerchecker.TypeFlagsPossiblyFalsy
  TypeFlagsPrimitive                                    = innerchecker.TypeFlagsPrimitive
  TypeFlagsReserved1                                    = innerchecker.TypeFlagsReserved1
  TypeFlagsReserved2                                    = innerchecker.TypeFlagsReserved2
  TypeFlagsReserved3                                    = innerchecker.TypeFlagsReserved3
  TypeFlagsSimplifiable                                 = innerchecker.TypeFlagsSimplifiable
  TypeFlagsSingleton                                    = innerchecker.TypeFlagsSingleton
  TypeFlagsString                                       = innerchecker.TypeFlagsString
  TypeFlagsStringOrNumberLiteral                        = innerchecker.TypeFlagsStringOrNumberLiteral
  TypeFlagsStringOrNumberLiteralOrUnique                = innerchecker.TypeFlagsStringOrNumberLiteralOrUnique
  TypeFlagsStructuredOrInstantiable                     = innerchecker.TypeFlagsStructuredOrInstantiable
  TypeFlagsStructuredType                               = innerchecker.TypeFlagsStructuredType
  TypeFlagsSubstitution                                 = innerchecker.TypeFlagsSubstitution
  TypeFlagsTypeParameter                                = innerchecker.TypeFlagsTypeParameter
  TypeFlagsTypeVariable                                 = innerchecker.TypeFlagsTypeVariable
  TypeFlagsUnionOrIntersection                          = innerchecker.TypeFlagsUnionOrIntersection
  TypeFlagsUniqueESSymbol                               = innerchecker.TypeFlagsUniqueESSymbol
  TypeFlagsUnit                                         = innerchecker.TypeFlagsUnit
  TypeFlagsVoidLike                                     = innerchecker.TypeFlagsVoidLike
)
