// GENERATED by scripts/guards/generate-executor-vocabulary.ts — do not edit.
//
// Every value below is read off `Cell.vocabulary`, which is itself folded from a description the
// public constructors build. Regenerate with:
//
//   pnpm vocabulary:executor
//
// `pnpm check:executor-vocabulary` re-renders this file and fails on any differing byte, so an
// edit here is reverted by the gate rather than surviving as a second declaration.

/** The description package whose phases chain by type. */
export const DESCRIPTION_SOURCE = '@systemfsoftware/effect-cell-types'

/** Phase constructors whose bodies are pure: a store, adapter or clock call inside one is a violation. */
export const PURE_PHASES = ['decode', 'decide', 'encode'] as const

/** Cells whose calls are I/O. */
export const IO_CELLS = ['store', 'adapter'] as const

/** Non-cell module sources whose calls are I/O. */
export const IO_SOURCES = ['effect/Clock', 'effect/System'] as const

/** Every call on the description module that belongs to a description: each phase, plus the applier. */
export const DESCRIPTION_METHODS = ['read', 'decode', 'decide', 'encode', 'write', 'apply'] as const
