import { Tag } from '../constants/tags.ts';

interface ActiveFiltersInput {
  includedTagFilters?: readonly unknown[];
  excludedTagFilters?: readonly unknown[];
  includedStatusFilters?: readonly unknown[];
  excludedStatusFilters?: readonly unknown[];
}

export const getActiveFilterCount = ({
  includedTagFilters,
  excludedTagFilters,
  includedStatusFilters,
  excludedStatusFilters,
}: ActiveFiltersInput): number =>
  (includedTagFilters?.length ?? 0) +
  (excludedTagFilters?.length ?? 0) +
  (includedStatusFilters?.length ?? 0) +
  (excludedStatusFilters?.length ?? 0);

/** Was this docs entry generated by a `.mdx` file (as opposed to an autodocs page)? */
export function isMdxEntry({ tags }: { tags?: Tag[] }) {
  return tags?.includes(Tag.UNATTACHED_MDX) || tags?.includes(Tag.ATTACHED_MDX);
}
