approvedGitRepositories:
  - "**"

compressionLevel: 0

enableGlobalCache: true

enableScripts: true

installStatePath: ./.yarn/root-install-state.gz

logFilters:
  - code: YN0007
    level: discard
  - code: YN0005
    level: discard
  - code: YN0076
    level: discard

nodeLinker: node-modules

npmMinimalAgeGate: 10080

npmPublishAccess: public

npmRegistryServer: "https://registry.yarnpkg.com"

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - current
    - linux
    - darwin

tsEnableAutoTypes: true

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-4.18.0.cjs
