import * as Match from 'effect/Match'
import * as Option from 'effect/Option'
import * as Pipeable from 'effect/Pipeable'
import * as ts from 'typescript'

import { IndentedWriter } from '../analyzer/indented-writer.js'
import * as SourceFileLocationFormatter from '../analyzer/SourceFileLocationFormatter.js'
import { Span } from '../analyzer/Span.js'
import * as SyntaxHelpers from '../analyzer/SyntaxHelpers.js'
import { convertToLf } from '../analyzer/text.js'
import * as TypeScriptHelpers from '../analyzer/TypeScriptHelpers.js'
import * as Snapshot from '../collector/analysis-snapshot.js'
import type { ApiItemMetadata } from '../collector/ApiItemMetadata.js'
import type { CollectorEntity } from '../collector/CollectorEntity.js'
import { ExtractorMessageId } from '../collector/extractor-message-id.js'
import { ExtractorMessage } from '../collector/message-log.js'
import type { ApiReportVariant } from '../config/config-file.schema.js'
import { UnsupportedStarExportError } from '../errors/index.js'
import { ReleaseTag } from '../model/index.js'
import { invariant } from '../utils/invariant.js'
import { DtsEmitHelpers } from './dts-emit-helpers.js'

const requireSome = <A>(option: Option.Option<A>, message: string): A => {
  if (Option.isNone(option)) {
    throw invariant(message)
  }
  return option.value
}

interface IContext {
  readonly snapshot: Snapshot.AnalysisSnapshot
  readonly reportVariant: ApiReportVariant
  readonly alreadyProcessedSignatures: Set<Span>
}

const _trimSpacesRegExp: RegExp = / +$/gm

const DEFAULT_TAGS_TO_REPORT: Readonly<Record<string, boolean>> = {
  '@sealed': true,
  '@virtual': true,
  '@override': true,
  '@eventProperty': true,
  '@deprecated': true,
}

const capitalizeFirstLetter = (input: string): string =>
  input.length === 0 ? '' : `${input[0]?.toLocaleUpperCase() ?? ''}${input.slice(1)}`

const writeReportHeader = (writer: IndentedWriter, packageName: string, reportVariant: ApiReportVariant): void => {
  const releaseLevelPrefix = reportVariant === 'complete' ? '' : `${capitalizeFirstLetter(reportVariant)} `
  writer.writeLine(`## ${releaseLevelPrefix}API Report File for "${packageName}"\n`)
  writer.writeLine(
    `> Do not edit this file. It is a report generated by [API Extractor](https://api-extractor.com/).\n`,
  )
  writer.writeLine('```ts\n')
}

const writeTripleSlashDirectives = (writer: IndentedWriter, snapshot: Snapshot.AnalysisSnapshot): void => {
  for (const typeDirectiveReference of Array.from(Snapshot.dtsTypeReferenceDirectives(snapshot)).sort()) {
    writer.writeLine(`/// <reference types="${typeDirectiveReference}" />`)
  }
  for (const libDirectiveReference of Array.from(Snapshot.dtsLibReferenceDirectives(snapshot)).sort()) {
    writer.writeLine(`/// <reference lib="${libDirectiveReference}" />`)
  }
  writer.ensureSkippedLine()
}

const writeImports = (writer: IndentedWriter, snapshot: Snapshot.AnalysisSnapshot): void => {
  for (const entity of Snapshot.entities(snapshot)) {
    const astEntity = Snapshot.astEntityOf(entity)
    Match.value(Snapshot.refOf(astEntity)).pipe(
      Match.tag('AstImportRef', () =>
        DtsEmitHelpers.emitImport(
          writer,
          entity,
          requireSome(Snapshot.astImportOf(astEntity), 'Missing AstImport for an AstImportRef'),
        )),
      Match.orElse(() => undefined),
    )
  }
  writer.ensureSkippedLine()
}

const emitNamespaceExportClauses = (
  writer: IndentedWriter,
  snapshot: Snapshot.AnalysisSnapshot,
  exportedLocalEntities: ReadonlyMap<string, Snapshot.AstEntity>,
  namespaceName: string,
): void => {
  writer.increaseIndent()
  writer.writeLine('export {')
  writer.increaseIndent()

  const exportClauses: string[] = []
  for (const [exportedName, astEntity] of exportedLocalEntities) {
    const collectorEntity = requireSome(
      Snapshot.tryGetCollectorEntity(snapshot, astEntity),
      `Cannot find collector entity for ${namespaceName}.${Snapshot.localName(snapshot, astEntity)}`,
    )

    const nameForEmit = collectorEntity.nameForEmit ?? ''
    if (nameForEmit === exportedName) {
      exportClauses.push(nameForEmit)
    } else {
      const safeExportedName = SyntaxHelpers.isSafeUnquotedMemberIdentifier(exportedName)
        ? exportedName
        : JSON.stringify(exportedName)
      exportClauses.push(`${nameForEmit} as ${safeExportedName}`)
    }
  }
  writer.writeLine(exportClauses.join(',\n'))

  writer.decreaseIndent()
  writer.writeLine('}')
  writer.decreaseIndent()
  writer.writeLine('}')
}

const emitNamespaceEntity = (
  writer: IndentedWriter,
  snapshot: Snapshot.AnalysisSnapshot,
  entity: CollectorEntity,
  astEntity: Snapshot.AstNamespaceImport,
): void => {
  const astModuleExportInfo = Snapshot.fetchAstModuleExportInfo(snapshot, astEntity)

  if (entity.nameForEmit === undefined || entity.nameForEmit.length === 0) {
    throw invariant('referencedEntry.nameForEmit is undefined')
  }

  if (astModuleExportInfo.starExportedExternalModules.size > 0) {
    throw new UnsupportedStarExportError({
      namespaceName: entity.nameForEmit,
      moduleSpecifier: SourceFileLocationFormatter.formatDeclaration(Snapshot.declaration(snapshot, astEntity)),
    })
  }

  writer.ensureSkippedLine()
  writer.writeLine(`declare namespace ${entity.nameForEmit} {`)
  emitNamespaceExportClauses(writer, snapshot, astModuleExportInfo.exportedLocalEntities, entity.nameForEmit)
}

const emitSymbolDeclarations = (
  writer: IndentedWriter,
  snapshot: Snapshot.AnalysisSnapshot,
  entity: CollectorEntity,
  astEntity: Snapshot.AstSymbol,
  reportVariant: ApiReportVariant,
  context: IContext,
  exportsToEmit: Map<string, { readonly associatedMessages: ExtractorMessage[] }>,
): void => {
  for (const astDeclaration of Snapshot.astDeclarations(snapshot, astEntity)) {
    const fetchedMessages = Snapshot.reportMessages(snapshot).associatedReportMessages(astDeclaration)

    const messagesToReport: ExtractorMessage[] = []
    for (const message of fetchedMessages) {
      const exportName = message.properties.exportName
      const exportToEmit = exportName === undefined ? undefined : exportsToEmit.get(exportName)
      if (exportToEmit !== undefined) {
        exportToEmit.associatedMessages.push(message)
        continue
      }
      messagesToReport.push(message)
    }

    if (_shouldIncludeDeclaration(snapshot, astDeclaration, reportVariant)) {
      writer.ensureSkippedLine()
      writer.write(_getAedocSynopsis(snapshot, astDeclaration, messagesToReport))

      const span = new Span(Snapshot.declaration(snapshot, astDeclaration))
      const apiItemMetadata = Snapshot.fetchApiItemMetadata(snapshot, astDeclaration)
      if (apiItemMetadata.isPreapproved) {
        _modifySpanForPreapproved(span)
      } else {
        _modifySpan(snapshot, span, entity, astDeclaration, false, context)
      }

      span.writeModifiedText(writer)
      writer.ensureNewLine()
    }
  }
}

const emitEntity = (
  writer: IndentedWriter,
  snapshot: Snapshot.AnalysisSnapshot,
  entity: CollectorEntity,
  reportVariant: ApiReportVariant,
  context: IContext,
): void => {
  const astEntity = Snapshot.astEntityOf(entity)
  const maxEffectiveReleaseTag = Option.match(Snapshot.tryFetchMetadataForAstEntity(snapshot, astEntity), {
    onNone: () => ReleaseTag.None,
    onSome: (symbolMetadata) => symbolMetadata.maxEffectiveReleaseTag,
  })

  if (!_shouldIncludeReleaseTag(maxEffectiveReleaseTag, reportVariant)) {
    return
  }

  const includeForgotten = Snapshot.extractorConfig(snapshot).apiReport.includeForgottenExports ?? false
  if (!entity.consumable && !includeForgotten) {
    return
  }

  const exportsToEmit = new Map<
    string,
    { readonly exportName: string; readonly associatedMessages: ExtractorMessage[] }
  >()
  for (const exportName of entity.exportNames) {
    if (!entity.shouldInlineExport) {
      exportsToEmit.set(exportName, { exportName, associatedMessages: [] })
    }
  }

  Match.value(Snapshot.refOf(astEntity)).pipe(
    Match.tag('AstSymbolRef', () =>
      emitSymbolDeclarations(
        writer,
        snapshot,
        entity,
        requireSome(Snapshot.astSymbolOf(astEntity), 'Missing AstSymbol for an AstSymbolRef'),
        reportVariant,
        context,
        exportsToEmit,
      )),
    Match.tag('AstNamespaceImportRef', () =>
      emitNamespaceEntity(
        writer,
        snapshot,
        entity,
        requireSome(
          Snapshot.astNamespaceImportOf(astEntity),
          'Missing AstNamespaceImport for an AstNamespaceImportRef',
        ),
      )),
    Match.orElse(() => undefined),
  )

  for (const exportToEmit of exportsToEmit.values()) {
    if (exportToEmit.associatedMessages.length > 0) {
      writer.ensureSkippedLine()
      for (const message of exportToEmit.associatedMessages) {
        _writeLineAsComments(writer, 'Warning: ' + message.formatMessageWithoutLocation())
      }
    }
    DtsEmitHelpers.emitNamedExport(writer, exportToEmit.exportName, entity)
  }
  writer.ensureSkippedLine()
}

export class ApiReportGenerator extends Pipeable.Class {
  public static areEquivalentApiFileContents(
    actualFileContent: string,
    expectedFileContent: string,
  ): boolean {
    const normalizedActual = actualFileContent.replace(/\s+/g, ' ')
    const normalizedExpected = expectedFileContent.replace(/\s+/g, ' ')
    return normalizedActual === normalizedExpected
  }

  public static generateReviewFileContent(
    snapshot: Snapshot.AnalysisSnapshot,
    reportVariant: ApiReportVariant,
  ): string {
    const writer = new IndentedWriter()
    writer.trimLeadingSpaces = true

    writeReportHeader(writer, Snapshot.workingPackage(snapshot).name, reportVariant)
    writeTripleSlashDirectives(writer, snapshot)
    writeImports(writer, snapshot)

    const context: IContext = {
      snapshot,
      reportVariant,
      alreadyProcessedSignatures: new Set(),
    }

    for (const entity of Snapshot.entities(snapshot)) {
      emitEntity(writer, snapshot, entity, reportVariant, context)
    }

    DtsEmitHelpers.emitStarExports(writer, snapshot)

    const unassociatedMessages = Snapshot.reportMessages(snapshot).unassociatedReportMessages()
    if (unassociatedMessages.length > 0) {
      writer.ensureSkippedLine()
      _writeLineAsComments(writer, 'Warnings were encountered during analysis:')
      _writeLineAsComments(writer, '')
      for (const message of unassociatedMessages) {
        _writeLineAsComments(
          writer,
          message.formatMessageWithLocation(Snapshot.workingPackage(snapshot).packageFolder),
        )
      }
    }

    if (Snapshot.workingPackage(snapshot).tsdocComment === undefined) {
      writer.ensureSkippedLine()
      _writeLineAsComments(writer, '(No @packageDocumentation comment for this package)')
    }

    writer.ensureSkippedLine()
    writer.writeLine('```')

    return writer.toString().replace(_trimSpacesRegExp, '')
  }
}

const handleExportKeyword = (span: Span): void => {
  if (DtsEmitHelpers.isExportKeywordInNamespaceExportDeclaration(span.node)) {
    return
  }
  span.modification.skipAll()
}

const handleKeywordModifiers = (span: Span, entity: CollectorEntity): void => {
  let replacedModifiers = ''
  if (entity.shouldInlineExport) {
    replacedModifiers = 'export ' + replacedModifiers
  }
  const previousSpan = span.previousSibling
  if (previousSpan !== undefined && previousSpan.kind === ts.SyntaxKind.SyntaxList) {
    previousSpan.modification.prefix = replacedModifiers + previousSpan.modification.prefix
  } else {
    span.modification.prefix = replacedModifiers + span.modification.prefix
  }
}

const handleVariableDeclaration = (span: Span, entity: CollectorEntity): void => {
  if (span.parent !== undefined) {
    return
  }
  const list = TypeScriptHelpers.matchAncestor<ts.VariableDeclarationList>(span.node, [
    ts.SyntaxKind.VariableDeclarationList,
    ts.SyntaxKind.VariableDeclaration,
  ])
  if (list === undefined) {
    throw invariant('Unsupported variable declaration')
  }
  const sourceFile = list.getSourceFile()
  const firstDeclStart = list.declarations[0]?.getStart() ?? list.getStart()
  const listPrefix = sourceFile.text.substring(list.getStart(), firstDeclStart)
  span.modification.prefix = listPrefix + span.modification.prefix
  span.modification.suffix = ';'

  if (entity.shouldInlineExport) {
    span.modification.prefix = 'export ' + span.modification.prefix
  }
}

const handleParameter = (span: Span, context: IContext): void => {
  const signatureParent = span.parent
  if (signatureParent !== undefined) {
    if (!context.alreadyProcessedSignatures.has(signatureParent)) {
      context.alreadyProcessedSignatures.add(signatureParent)
      DtsEmitHelpers.normalizeParameterNames(signatureParent)
    }
  }
}

const handleIdentifier = (span: Span, snapshot: Snapshot.AnalysisSnapshot): void => {
  if (!ts.isIdentifier(span.node)) {
    return
  }
  Option.match(Snapshot.tryGetEntityForNode(snapshot, span.node), {
    onNone: () => undefined,
    onSome: (referencedEntity) => {
      if (referencedEntity.nameForEmit === undefined || referencedEntity.nameForEmit.length === 0) {
        throw invariant('referencedEntry.nameForEmit is undefined')
      }
      span.modification.prefix = referencedEntity.nameForEmit
    },
  })
}

const handleSyntaxList = (span: Span): boolean => {
  if (span.parent === undefined) {
    return false
  }
  return Snapshot.isSupportedDeclarationKind(span.parent.kind) || span.parent.kind === ts.SyntaxKind.ModuleBlock
}

const isKeywordNeedingModifiers = (kind: ts.SyntaxKind): boolean =>
  kind === ts.SyntaxKind.InterfaceKeyword ||
  kind === ts.SyntaxKind.ClassKeyword ||
  kind === ts.SyntaxKind.EnumKeyword ||
  kind === ts.SyntaxKind.NamespaceKeyword ||
  kind === ts.SyntaxKind.ModuleKeyword ||
  kind === ts.SyntaxKind.TypeKeyword ||
  kind === ts.SyntaxKind.FunctionKeyword

function _modifySpan(
  snapshot: Snapshot.AnalysisSnapshot,
  span: Span,
  entity: CollectorEntity,
  astDeclaration: Snapshot.AstDeclaration,
  insideTypeLiteral: boolean,
  context: IContext,
): void {
  const { reportVariant } = context

  if (!_shouldIncludeDeclaration(snapshot, astDeclaration, reportVariant)) {
    span.modification.skipAll()
    return
  }

  let recurseChildren = true
  let sortChildren = false
  let nextInsideTypeLiteral = insideTypeLiteral

  if (span.kind === ts.SyntaxKind.JSDocComment) {
    span.modification.skipAll()
    recurseChildren = false
  } else if (span.kind === ts.SyntaxKind.ExportKeyword) {
    handleExportKeyword(span)
  } else if (span.kind === ts.SyntaxKind.DefaultKeyword || span.kind === ts.SyntaxKind.DeclareKeyword) {
    span.modification.skipAll()
  } else if (isKeywordNeedingModifiers(span.kind)) {
    handleKeywordModifiers(span, entity)
  } else if (span.kind === ts.SyntaxKind.SyntaxList) {
    sortChildren = handleSyntaxList(span)
  } else if (span.kind === ts.SyntaxKind.VariableDeclaration) {
    handleVariableDeclaration(span, entity)
  } else if (span.kind === ts.SyntaxKind.Parameter) {
    handleParameter(span, context)
  } else if (span.kind === ts.SyntaxKind.Identifier) {
    handleIdentifier(span, snapshot)
  } else if (span.kind === ts.SyntaxKind.TypeLiteral) {
    nextInsideTypeLiteral = true
  } else if (span.kind === ts.SyntaxKind.ImportType) {
    DtsEmitHelpers.modifyImportTypeSpan(
      snapshot,
      span,
      astDeclaration,
      (childSpan, childAstDeclaration) => {
        _modifySpan(snapshot, childSpan, entity, childAstDeclaration, nextInsideTypeLiteral, context)
      },
    )
  }

  if (recurseChildren) {
    for (const child of span.children) {
      let childAstDeclaration: Snapshot.AstDeclaration = astDeclaration

      if (Snapshot.isSupportedDeclarationKind(child.kind)) {
        childAstDeclaration = Snapshot.childDeclarationByNode(snapshot, child.node, astDeclaration)

        if (_shouldIncludeDeclaration(snapshot, childAstDeclaration, reportVariant)) {
          if (sortChildren) {
            span.modification.sortChildren = true
            child.modification.sortKey = Snapshot.sortKeyIgnoringUnderscore(
              Snapshot.localName(snapshot, childAstDeclaration),
            )
          }

          if (!nextInsideTypeLiteral) {
            const messagesToReport = Snapshot.reportMessages(snapshot).associatedReportMessages(childAstDeclaration)
            const aedocSynopsis = _getAedocSynopsis(snapshot, childAstDeclaration, messagesToReport)
            child.modification.prefix = aedocSynopsis + child.modification.prefix
          }
        }
      }

      _modifySpan(snapshot, child, entity, childAstDeclaration, nextInsideTypeLiteral, context)
    }
  }
}

function _shouldIncludeDeclaration(
  snapshot: Snapshot.AnalysisSnapshot,
  astDeclaration: Snapshot.AstDeclaration,
  reportVariant: ApiReportVariant,
): boolean {
  // eslint-disable-next-line no-bitwise
  if ((Snapshot.modifierFlags(snapshot, astDeclaration) & ts.ModifierFlags.Private) !== 0) {
    return false
  }

  const apiItemMetadata = Snapshot.fetchApiItemMetadata(snapshot, astDeclaration)
  return _shouldIncludeReleaseTag(apiItemMetadata.effectiveReleaseTag, reportVariant)
}

function _shouldIncludeReleaseTag(releaseTag: ReleaseTag, reportVariant: ApiReportVariant): boolean {
  switch (reportVariant) {
    case 'complete':
      return true
    case 'alpha':
      return (
        releaseTag === ReleaseTag.Alpha ||
        releaseTag === ReleaseTag.Beta ||
        releaseTag === ReleaseTag.Public ||
        releaseTag === ReleaseTag.None
      )
    case 'beta':
      return (
        releaseTag === ReleaseTag.Beta ||
        releaseTag === ReleaseTag.Public ||
        releaseTag === ReleaseTag.None
      )
    case 'public':
      return (
        releaseTag === ReleaseTag.Public ||
        releaseTag === ReleaseTag.None
      )
  }
}

function _modifySpanForPreapproved(span: Span): void {
  let skipRest = false
  for (const child of span.children) {
    if (skipRest || child.kind === ts.SyntaxKind.SyntaxList || child.kind === ts.SyntaxKind.JSDocComment) {
      child.modification.skipAll()
    }
    if (child.kind === ts.SyntaxKind.Identifier) {
      skipRest = true
      child.modification.omitSeparatorAfter = true
      child.modification.suffix = ' { /* (preapproved) */ }'
    }
  }
}

interface StandardTagsConfig {
  readonly reportSealedTag?: boolean | undefined
  readonly reportVirtualTag?: boolean | undefined
  readonly reportOverrideTag?: boolean | undefined
  readonly reportEventPropertyTag?: boolean | undefined
  readonly reportDeprecatedTag?: boolean | undefined
}

const collectStandardTags = (
  apiItemMetadata: ApiItemMetadata,
  tags: StandardTagsConfig,
  parts: string[],
): void => {
  if (tags.reportSealedTag === true && apiItemMetadata.isSealed) parts.push('@sealed')
  if (tags.reportVirtualTag === true && apiItemMetadata.isVirtual) parts.push('@virtual')
  if (tags.reportOverrideTag === true && apiItemMetadata.isOverride) parts.push('@override')
  if (tags.reportEventPropertyTag === true && apiItemMetadata.isEventProperty) parts.push('@eventProperty')
  if (tags.reportDeprecatedTag === true && apiItemMetadata.tsdocComment?.deprecatedBlock !== undefined) {
    parts.push('@deprecated')
  }
}

const collectCustomTags = (
  apiItemMetadata: ApiItemMetadata,
  otherTags: Readonly<Record<string, boolean | undefined>>,
  parts: string[],
): void => {
  for (const [tag, shouldReport] of Object.entries(otherTags)) {
    if (shouldReport === true) {
      if (apiItemMetadata.tsdocComment?.customBlocks.some((b) => b.blockTag.tagName === tag) === true) {
        parts.push(tag)
      } else if (apiItemMetadata.tsdocComment?.modifierTagSet.hasTagName(tag) === true) {
        parts.push(tag)
      }
    }
  }
}

function _getAedocSynopsis(
  snapshot: Snapshot.AnalysisSnapshot,
  astDeclaration: Snapshot.AstDeclaration,
  messagesToReport: readonly ExtractorMessage[] = [],
): string {
  const writer = new IndentedWriter()

  if (Snapshot.isAncillaryDeclaration(snapshot, astDeclaration)) {
    return ''
  }

  for (const message of messagesToReport) {
    _writeLineAsComments(writer, 'Warning: ' + message.formatMessageWithoutLocation())
  }

  const footerParts: string[] = []
  const apiItemMetadata = Snapshot.fetchApiItemMetadata(snapshot, astDeclaration)

  if (!apiItemMetadata.releaseTagSameAsParent && apiItemMetadata.effectiveReleaseTag !== ReleaseTag.None) {
    footerParts.push(ReleaseTag.getTagName(apiItemMetadata.effectiveReleaseTag))
  }

  const configTags = Snapshot.extractorConfig(snapshot).apiReport.tagsToReport ?? {}
  const tagsToReport = {
    ...DEFAULT_TAGS_TO_REPORT,
    ...configTags,
  }

  const {
    '@sealed': reportSealedTag,
    '@virtual': reportVirtualTag,
    '@override': reportOverrideTag,
    '@eventProperty': reportEventPropertyTag,
    '@deprecated': reportDeprecatedTag,
    ...otherTagsToReport
  } = tagsToReport

  collectStandardTags(
    apiItemMetadata,
    { reportSealedTag, reportVirtualTag, reportOverrideTag, reportEventPropertyTag, reportDeprecatedTag },
    footerParts,
  )
  collectCustomTags(apiItemMetadata, otherTagsToReport, footerParts)

  if (apiItemMetadata.undocumented) {
    footerParts.push('(undocumented)')
    Snapshot.addAnalyzerIssue(
      snapshot,
      ExtractorMessageId.Undocumented,
      `Missing documentation for "${Snapshot.localName(snapshot, astDeclaration)}".`,
      astDeclaration,
    )
  }

  if (footerParts.length > 0) {
    if (messagesToReport.length > 0) {
      _writeLineAsComments(writer, '')
    }

    _writeLineAsComments(writer, footerParts.join(' '))
  }

  return writer.toString()
}

function _writeLineAsComments(writer: IndentedWriter, line: string): void {
  const lines: string[] = convertToLf(line).split('\n')
  for (const realLine of lines) {
    writer.write('// ')
    writer.write(realLine)
    writer.writeLine()
  }
}
