import { HashSet, Option, Result } from 'effect'
import * as Arr from 'effect/Array'
import * as Match from 'effect/Match'
import * as Order from 'effect/Order'
import * as ts from 'typescript'

import * as SourceFileLocationFormatter from '../analyzer/SourceFileLocationFormatter.js'
import * as SyntaxHelpers from '../analyzer/SyntaxHelpers.js'
import type { NodeId } from '../analyzer/TypeScriptInternals.js'
import * as Snapshot from '../collector/analysis-snapshot.js'
import type { CollectorEntity } from '../collector/CollectorEntity.js'
import type { ExtractorMessage } from '../collector/message-log.js'
import type { ApiReportVariant } from '../config/config-file.schema.js'
import { UnsupportedStarExportError } from '../errors/index.js'
import { ReleaseTag } from '../model/index.js'
import {
  associatedMessagesOf,
  type ExportToEmit,
  getAedocSynopsis,
  internalInvariantOf,
  planDeclarationSpan,
  planForPreapproved,
  type PlanState,
  type ReportRenderFailure,
  shouldIncludeDeclaration,
  unassociatedMessagesOf,
  writeLineAsComments,
} from './declaration-span-plan.js'
import * as RenderSpan from './render-span.js'
import * as SpanPlan from './span-plan.js'
import * as SpanTreeModule from './span-tree.js'
import * as TextWriter from './text-writer.js'

/**
 * The outcome of one api-report render: the finished document plus the indices of the log messages it
 * consumed, so the next variant renders against an updated handled set.
 */
export interface RenderedApiReport {
  readonly text: string
  readonly consumed: HashSet.HashSet<number>
}

interface ReportState {
  readonly writer: TextWriter.TextWriter
  readonly snapshot: Snapshot.AnalysisSnapshot
  readonly reportVariant: ApiReportVariant
  readonly handled: HashSet.HashSet<number>
  readonly consumed: HashSet.HashSet<number>
  readonly processedSignatures: HashSet.HashSet<NodeId>
}

interface EntityEmit {
  readonly writer: TextWriter.TextWriter
  readonly planState: PlanState
}

const _trimSpacesRegExp: RegExp = / +$/gm

const capitalizeFirstLetter = (input: string): string =>
  Match.value(input.length > 0).pipe(
    Match.when(true, () => `${input.slice(0, 1).toLocaleUpperCase()}${input.slice(1)}`),
    Match.when(false, () => ''),
    Match.exhaustive,
  )

const writeReportHeader = (
  writer: TextWriter.TextWriter,
  packageName: string,
  reportVariant: ApiReportVariant,
): TextWriter.TextWriter => {
  const releaseLevelPrefix = Match.value(reportVariant === 'complete').pipe(
    Match.when(true, () => ''),
    Match.when(false, () => `${capitalizeFirstLetter(reportVariant)} `),
    Match.exhaustive,
  )
  return TextWriter.writeLine(
    TextWriter.writeLine(
      TextWriter.writeLine(writer, `## ${releaseLevelPrefix}API Report File for "${packageName}"\n`),
      '> Do not edit this file. It is a report generated by [API Extractor](https://api-extractor.com/).\n',
    ),
    '```ts\n',
  )
}

const writeTripleSlashDirectives = (
  writer: TextWriter.TextWriter,
  snapshot: Snapshot.AnalysisSnapshot,
): TextWriter.TextWriter => {
  const withTypeDirectives = Arr.reduce(
    Arr.sort(Arr.fromIterable(Snapshot.dtsTypeReferenceDirectives(snapshot)), Order.String),
    writer,
    (current, typeDirectiveReference) =>
      TextWriter.writeLine(current, `/// <reference types="${typeDirectiveReference}" />`),
  )
  const withLibDirectives = Arr.reduce(
    Arr.sort(Arr.fromIterable(Snapshot.dtsLibReferenceDirectives(snapshot)), Order.String),
    withTypeDirectives,
    (current, libDirectiveReference) =>
      TextWriter.writeLine(current, `/// <reference lib="${libDirectiveReference}" />`),
  )
  return TextWriter.ensureSkippedLine(withLibDirectives)
}

const entityNameOf = (entity: CollectorEntity): string => entity.nameForEmit ?? ''

const defaultImportLineOf = (prefix: string, entity: CollectorEntity, astImport: Snapshot.AstImport): string => {
  const name = entityNameOf(entity)
  return Match.value(name === astImport.exportName).pipe(
    Match.when(true, () => `${prefix} ${astImport.exportName} from '${astImport.modulePath}';`),
    Match.when(false, () => `${prefix} { default as ${name} } from '${astImport.modulePath}';`),
    Match.exhaustive,
  )
}

const namedImportLineOf = (prefix: string, entity: CollectorEntity, astImport: Snapshot.AstImport): string => {
  const name = entityNameOf(entity)
  return Match.value(name === astImport.exportName).pipe(
    Match.when(true, () => `${prefix} { ${astImport.exportName} } from '${astImport.modulePath}';`),
    Match.when(false, () => `${prefix} { ${astImport.exportName} as ${name} } from '${astImport.modulePath}';`),
    Match.exhaustive,
  )
}

const starImportLineOf = (prefix: string, entity: CollectorEntity, astImport: Snapshot.AstImport): string =>
  `${prefix} * as ${entityNameOf(entity)} from '${astImport.modulePath}';`

const equalsImportLineOf = (prefix: string, entity: CollectorEntity, astImport: Snapshot.AstImport): string =>
  `${prefix} ${entityNameOf(entity)} = require('${astImport.modulePath}');`

const importTypeLineOf = (prefix: string, entity: CollectorEntity, astImport: Snapshot.AstImport): string =>
  Match.value(astImport.exportName.length === 0).pipe(
    Match.when(true, () => `${prefix} * as ${entityNameOf(entity)} from '${astImport.modulePath}';`),
    Match.when(false, () => {
      const topExportName = Option.getOrElse(Arr.head(astImport.exportName.split('.')), () => '')
      const name = entityNameOf(entity)
      return Match.value(name === topExportName).pipe(
        Match.when(true, () => `${prefix} { ${topExportName} } from '${astImport.modulePath}';`),
        Match.when(false, () => `${prefix} { ${topExportName} as ${name} } from '${astImport.modulePath}';`),
        Match.exhaustive,
      )
    }),
    Match.exhaustive,
  )

type ImportLineBuilder = (prefix: string, entity: CollectorEntity, astImport: Snapshot.AstImport) => string

const importLineBuilders: Readonly<Record<Snapshot.AstImportKind, ImportLineBuilder>> = {
  [Snapshot.AstImportKind.DefaultImport]: defaultImportLineOf,
  [Snapshot.AstImportKind.NamedImport]: namedImportLineOf,
  [Snapshot.AstImportKind.StarImport]: starImportLineOf,
  [Snapshot.AstImportKind.EqualsImport]: equalsImportLineOf,
  [Snapshot.AstImportKind.ImportType]: importTypeLineOf,
}

const importPrefixOf = (astImport: Snapshot.AstImport): string =>
  Match.value(astImport.isTypeOnlyEverywhere).pipe(
    Match.when(true, () => 'import type'),
    Match.when(false, () => 'import'),
    Match.exhaustive,
  )

const emitImportLine = (
  writer: TextWriter.TextWriter,
  entity: CollectorEntity,
  astImport: Snapshot.AstImport,
): TextWriter.TextWriter =>
  TextWriter.writeLine(writer, importLineBuilders[astImport.importKind](importPrefixOf(astImport), entity, astImport))

const writeImports = (
  writer: TextWriter.TextWriter,
  snapshot: Snapshot.AnalysisSnapshot,
): Result.Result<TextWriter.TextWriter, ReportRenderFailure> => {
  const initial: Result.Result<TextWriter.TextWriter, ReportRenderFailure> = Result.succeed(writer)
  const afterImports = Arr.reduce(
    Snapshot.entities(snapshot),
    initial,
    (accumulated, entity) =>
      Result.flatMap(accumulated, (current) =>
        Match.value(Snapshot.refOf(Snapshot.astEntityOf(entity))).pipe(
          Match.tag('AstImportRef', () =>
            Option.match(Snapshot.astImportOf(Snapshot.astEntityOf(entity)), {
              onNone: () => internalInvariantOf('Missing AstImport for an AstImportRef'),
              onSome: (astImport) => Result.succeed(emitImportLine(current, entity, astImport)),
            })),
          Match.orElse((): Result.Result<TextWriter.TextWriter, ReportRenderFailure> => Result.succeed(current)),
        )),
  )
  return Result.map(afterImports, (current) => TextWriter.ensureSkippedLine(current))
}

const clauseLineOf = (exportedName: string, collectorEntity: CollectorEntity): string => {
  const nameForEmit = entityNameOf(collectorEntity)
  return Match.value(nameForEmit === exportedName).pipe(
    Match.when(true, () => nameForEmit),
    Match.when(false, () => {
      const safeExportedName = Match.value(SyntaxHelpers.isSafeUnquotedMemberIdentifier(exportedName)).pipe(
        Match.when(true, () => exportedName),
        Match.when(false, () => JSON.stringify(exportedName)),
        Match.exhaustive,
      )
      return `${nameForEmit} as ${safeExportedName}`
    }),
    Match.exhaustive,
  )
}

const exportClauseOf = (
  emit: EntityEmit,
  exportedName: string,
  exportedEntity: Snapshot.AstEntity,
  namespaceName: string,
): Result.Result<string, ReportRenderFailure> =>
  Option.match(Snapshot.tryGetCollectorEntity(emit.planState.snapshot, exportedEntity), {
    onNone: () =>
      internalInvariantOf(
        `Cannot find collector entity for ${namespaceName}.${
          Snapshot.localName(emit.planState.snapshot, exportedEntity)
        }`,
      ),
    onSome: (collectorEntity) => Result.succeed(clauseLineOf(exportedName, collectorEntity)),
  })

const exportClauseLinesOf = (
  emit: EntityEmit,
  exportedLocalEntities: ReadonlyMap<string, Snapshot.AstEntity>,
  namespaceName: string,
): Result.Result<ReadonlyArray<string>, ReportRenderFailure> => {
  const initial: Result.Result<ReadonlyArray<string>, ReportRenderFailure> = Result.succeed([])
  return Arr.reduce(
    Arr.fromIterable(exportedLocalEntities),
    initial,
    (accumulated, [exportedName, exportedEntity]) =>
      Result.flatMap(
        accumulated,
        (lines) =>
          Result.map(exportClauseOf(emit, exportedName, exportedEntity, namespaceName), (clause) =>
            Arr.append(lines, clause)),
      ),
  )
}

const emitNamespaceExportClauses = (
  emit: EntityEmit,
  exportedLocalEntities: ReadonlyMap<string, Snapshot.AstEntity>,
  namespaceName: string,
): Result.Result<EntityEmit, ReportRenderFailure> =>
  Result.map(exportClauseLinesOf(emit, exportedLocalEntities, namespaceName), (clauseLines) => {
    const level1 = TextWriter.increaseIndent(emit.writer)
    const afterOpen = TextWriter.writeLine(level1, 'export {')
    const level2 = TextWriter.increaseIndent(afterOpen)
    const afterClauses = TextWriter.writeLine(level2, Arr.join(clauseLines, ',\n'))
    const afterInnerClose = TextWriter.writeLine(TextWriter.decreaseIndent(afterClauses), '}')
    const afterOuterClose = TextWriter.writeLine(TextWriter.decreaseIndent(afterInnerClose), '}')
    return { writer: afterOuterClose, planState: emit.planState }
  })

const emitNamespaceEntity = (
  emit: EntityEmit,
  entity: CollectorEntity,
  astEntity: Snapshot.AstNamespaceImport,
): Result.Result<EntityEmit, ReportRenderFailure> => {
  const astModuleExportInfo = Snapshot.fetchAstModuleExportInfo(emit.planState.snapshot, astEntity)
  return Option.match(Option.filter(Option.fromNullishOr(entity.nameForEmit), (name) => name.length > 0), {
    onNone: () => internalInvariantOf('referencedEntry.nameForEmit is undefined'),
    onSome: (namespaceName) =>
      Match.value(astModuleExportInfo.starExportedExternalModules.size > 0).pipe(
        Match.when(true, (): Result.Result<EntityEmit, ReportRenderFailure> =>
          Result.fail(
            new UnsupportedStarExportError({
              namespaceName,
              moduleSpecifier: SourceFileLocationFormatter.formatDeclaration(
                Snapshot.declaration(emit.planState.snapshot, astEntity),
              ),
            }),
          )),
        Match.when(false, () => {
          const afterSkippedLine: EntityEmit = { ...emit, writer: TextWriter.ensureSkippedLine(emit.writer) }
          const afterHeader: EntityEmit = {
            ...afterSkippedLine,
            writer: TextWriter.writeLine(afterSkippedLine.writer, `declare namespace ${namespaceName} {`),
          }
          return emitNamespaceExportClauses(
            afterHeader,
            astModuleExportInfo.exportedLocalEntities,
            namespaceName,
          )
        }),
        Match.exhaustive,
      ),
  })
}

interface AssociatedPartition {
  readonly entries: ReadonlyArray<ExportToEmit>
  readonly standalone: ReadonlyArray<ExtractorMessage>
}

const partitionAssociatedMessages = (
  messages: ReadonlyArray<ExtractorMessage>,
  entries: ReadonlyArray<ExportToEmit>,
): AssociatedPartition => {
  const initial: AssociatedPartition = { entries, standalone: [] }
  return Arr.reduce(messages, initial, (partition, message) =>
    Option.match(
      Arr.findFirstIndex(partition.entries, (entry) => entry.exportName === message.properties.exportName),
      {
        onNone: () => ({ entries: partition.entries, standalone: Arr.append(partition.standalone, message) }),
        onSome: (index) => ({
          entries: Option.getOrElse(
            Arr.modify(partition.entries, index, (entry) => ({
              ...entry,
              associatedMessages: Arr.append(entry.associatedMessages, message),
            })),
            () => partition.entries,
          ),
          standalone: partition.standalone,
        }),
      },
    ))
}

const emitSymbolDeclarations = (
  emit: EntityEmit,
  astSymbol: Snapshot.AstSymbol,
): Result.Result<EntityEmit, ReportRenderFailure> => {
  const initial: Result.Result<EntityEmit, ReportRenderFailure> = Result.succeed(emit)
  return Arr.reduce(
    Snapshot.astDeclarations(emit.planState.snapshot, astSymbol),
    initial,
    (accumulated, astDeclaration) =>
      Result.flatMap(accumulated, (current) => emitSymbolDeclaration(current, astDeclaration)),
  )
}

const emitSymbolDeclaration = (
  emit: EntityEmit,
  astDeclaration: Snapshot.AstDeclaration,
): Result.Result<EntityEmit, ReportRenderFailure> => {
  const selected = associatedMessagesOf(emit.planState, astDeclaration)
  const partitioned = partitionAssociatedMessages(selected.messages, emit.planState.exportsToEmit)
  const withEntries: EntityEmit = {
    writer: emit.writer,
    planState: { ...emit.planState, consumed: selected.consumed, exportsToEmit: partitioned.entries },
  }
  return Match.value(shouldIncludeDeclaration(withEntries.planState, astDeclaration)).pipe(
    Match.when(false, (): Result.Result<EntityEmit, ReportRenderFailure> => Result.succeed(withEntries)),
    Match.when(true, () => emitIncludedDeclaration(withEntries, astDeclaration, partitioned.standalone)),
    Match.exhaustive,
  )
}

const emitIncludedDeclaration = (
  emit: EntityEmit,
  astDeclaration: Snapshot.AstDeclaration,
  standalone: ReadonlyArray<ExtractorMessage>,
): Result.Result<EntityEmit, ReportRenderFailure> => {
  const tree = SpanTreeModule.build(Snapshot.declaration(emit.planState.snapshot, astDeclaration))
  const afterSynopsis = TextWriter.write(
    TextWriter.ensureSkippedLine(emit.writer),
    getAedocSynopsis(emit.planState.snapshot, astDeclaration, standalone),
  )
  return Result.map(plannedDeclarationOf(emit.planState, tree, astDeclaration), (plannedState) => ({
    writer: TextWriter.ensureNewLine(RenderSpan.writeSpan(tree, plannedState.plan, afterSynopsis)),
    planState: plannedState,
  }))
}

const plannedDeclarationOf = (
  planState: PlanState,
  tree: SpanTreeModule.SpanTree,
  astDeclaration: Snapshot.AstDeclaration,
): Result.Result<PlanState, ReportRenderFailure> =>
  Match.value(Snapshot.fetchApiItemMetadata(planState.snapshot, astDeclaration).isPreapproved).pipe(
    Match.when(
      true,
      (): Result.Result<PlanState, ReportRenderFailure> =>
        Result.succeed({ ...planState, plan: planForPreapproved(planState.plan, tree) }),
    ),
    Match.when(false, () => planDeclarationSpan(planState, tree, Option.none(), Option.none(), astDeclaration, false)),
    Match.exhaustive,
  )

const emitEntityDeclarations = (
  emit: EntityEmit,
  entity: CollectorEntity,
): Result.Result<EntityEmit, ReportRenderFailure> => {
  const astEntity = Snapshot.astEntityOf(entity)
  return Match.value(Snapshot.refOf(astEntity)).pipe(
    Match.tag('AstSymbolRef', () =>
      Option.match(Snapshot.astSymbolOf(astEntity), {
        onNone: () => internalInvariantOf('Missing AstSymbol for an AstSymbolRef'),
        onSome: (astSymbol) => emitSymbolDeclarations(emit, astSymbol),
      })),
    Match.tag('AstNamespaceImportRef', () =>
      Option.match(Snapshot.astNamespaceImportOf(astEntity), {
        onNone: () => internalInvariantOf('Missing AstNamespaceImport for an AstNamespaceImportRef'),
        onSome: (astNamespaceImport) => emitNamespaceEntity(emit, entity, astNamespaceImport),
      })),
    Match.orElse((): Result.Result<EntityEmit, ReportRenderFailure> => Result.succeed(emit)),
  )
}

const maxEffectiveReleaseTagOf = (report: ReportState, entity: CollectorEntity): ReleaseTag =>
  Option.match(Snapshot.tryFetchMetadataForAstEntity(report.snapshot, Snapshot.astEntityOf(entity)), {
    onNone: () => ReleaseTag.None,
    onSome: (symbolMetadata) => symbolMetadata.maxEffectiveReleaseTag,
  })

const includeForgottenExportsOf = (report: ReportState): boolean =>
  Option.getOrElse(
    Option.fromNullishOr(Snapshot.extractorConfig(report.snapshot).apiReport.includeForgottenExports),
    () => false,
  )

const emitReleaseEligibleEntity = (
  report: ReportState,
  entity: CollectorEntity,
): Result.Result<ReportState, ReportRenderFailure> =>
  Match.value(entity.consumable || includeForgottenExportsOf(report)).pipe(
    Match.when(false, (): Result.Result<ReportState, ReportRenderFailure> => Result.succeed(report)),
    Match.when(true, () => emitConsumableEntity(report, entity)),
    Match.exhaustive,
  )

const emitEntity = (report: ReportState, entity: CollectorEntity): Result.Result<ReportState, ReportRenderFailure> =>
  Match.value(shouldIncludeReleaseTagOf(maxEffectiveReleaseTagOf(report, entity), report.reportVariant)).pipe(
    Match.when(false, (): Result.Result<ReportState, ReportRenderFailure> => Result.succeed(report)),
    Match.when(true, () => emitReleaseEligibleEntity(report, entity)),
    Match.exhaustive,
  )

const shouldIncludeReleaseTagOf = (releaseTag: ReleaseTag, reportVariant: ApiReportVariant): boolean =>
  Match.value(reportVariant).pipe(
    Match.when('complete', () => true),
    Match.when(
      'alpha',
      () => releaseTagAdmittedOf(releaseTag, [ReleaseTag.Alpha, ReleaseTag.Beta, ReleaseTag.Public, ReleaseTag.None]),
    ),
    Match.when('beta', () => releaseTagAdmittedOf(releaseTag, [ReleaseTag.Beta, ReleaseTag.Public, ReleaseTag.None])),
    Match.when('public', () => releaseTagAdmittedOf(releaseTag, [ReleaseTag.Public, ReleaseTag.None])),
    Match.exhaustive,
  )

const releaseTagAdmittedOf = (releaseTag: ReleaseTag, admitted: ReadonlyArray<ReleaseTag>): boolean =>
  Arr.some(admitted, (candidate) => candidate === releaseTag)

const entriesOf = (entity: CollectorEntity): ReadonlyArray<ExportToEmit> =>
  Arr.map(
    Arr.filter(Arr.fromIterable(entity.exportNames), () => !entity.shouldInlineExport),
    (exportName): ExportToEmit => ({ exportName, associatedMessages: [] }),
  )

const emitConsumableEntity = (
  report: ReportState,
  entity: CollectorEntity,
): Result.Result<ReportState, ReportRenderFailure> => {
  const initial: Result.Result<EntityEmit, ReportRenderFailure> = Result.succeed({
    writer: report.writer,
    planState: {
      ...report,
      entity,
      plan: SpanPlan.empty,
      exportsToEmit: entriesOf(entity),
    },
  })
  return Result.flatMap(
    initial,
    (emit) => Result.map(emitEntityDeclarations(emit, entity), (emitted) => writeEntityExports(emitted, entity)),
  )
}

const writeWarningComments = (
  writer: TextWriter.TextWriter,
  messages: ReadonlyArray<ExtractorMessage>,
): TextWriter.TextWriter =>
  Arr.reduce(
    messages,
    writer,
    (current, message) => writeLineAsComments(current, `Warning: ${message.formatMessageWithoutLocation()}`),
  )

const formatNamedExport = (exportName: string, name: string): string =>
  Match.value(exportName === ts.InternalSymbolName.Default).pipe(
    Match.when(true, () => `export default ${name};`),
    Match.when(false, () =>
      Match.value(name === exportName).pipe(
        Match.when(true, () => `export { ${exportName} }`),
        Match.when(false, () => `export { ${name} as ${exportName} }`),
        Match.exhaustive,
      )),
    Match.exhaustive,
  )

const writeExportClause = (
  writer: TextWriter.TextWriter,
  exportToEmit: ExportToEmit,
  entity: CollectorEntity,
): TextWriter.TextWriter => {
  const withWarnings = Match.value(exportToEmit.associatedMessages.length > 0).pipe(
    Match.when(true, () => writeWarningComments(TextWriter.ensureSkippedLine(writer), exportToEmit.associatedMessages)),
    Match.when(false, () => writer),
    Match.exhaustive,
  )
  return TextWriter.writeLine(withWarnings, formatNamedExport(exportToEmit.exportName, entityNameOf(entity)))
}

const writeEntityExports = (emit: EntityEmit, entity: CollectorEntity): ReportState => {
  const afterClauses = Arr.reduce(
    emit.planState.exportsToEmit,
    emit.writer,
    (writer, exportToEmit) => writeExportClause(writer, exportToEmit, entity),
  )
  return {
    writer: TextWriter.ensureSkippedLine(afterClauses),
    snapshot: emit.planState.snapshot,
    reportVariant: emit.planState.reportVariant,
    handled: emit.planState.handled,
    consumed: emit.planState.consumed,
    processedSignatures: emit.planState.processedSignatures,
  }
}

const emitStarExports = (writer: TextWriter.TextWriter, snapshot: Snapshot.AnalysisSnapshot): TextWriter.TextWriter =>
  Match.value(Snapshot.starExportedExternalModulePaths(snapshot)).pipe(
    Match.when((modulePaths) => modulePaths.length === 0, () => writer),
    Match.orElse((modulePaths) =>
      Arr.reduce(
        modulePaths,
        TextWriter.writeLine(writer),
        (current, modulePath) => TextWriter.writeLine(current, `export * from "${modulePath}";`),
      )
    ),
  )

const writeUnassociatedWarnings = (
  writer: TextWriter.TextWriter,
  messages: ReadonlyArray<ExtractorMessage>,
  snapshot: Snapshot.AnalysisSnapshot,
): TextWriter.TextWriter =>
  Match.value(messages.length === 0).pipe(
    Match.when(true, () => writer),
    Match.when(false, () => {
      const afterHeader = writeLineAsComments(
        TextWriter.ensureSkippedLine(writer),
        'Warnings were encountered during analysis:',
      )
      const afterBlank = writeLineAsComments(afterHeader, '')
      return Arr.reduce(messages, afterBlank, (current, message) =>
        writeLineAsComments(
          current,
          message.formatMessageWithLocation(Snapshot.workingPackage(snapshot).packageFolder),
        ))
    }),
    Match.exhaustive,
  )

const finishReport = (report: ReportState): RenderedApiReport => {
  const withStarExports = { ...report, writer: emitStarExports(report.writer, report.snapshot) }
  const selected = unassociatedMessagesOf(withStarExports)
  const withUnassociated = {
    ...withStarExports,
    consumed: selected.consumed,
    writer: writeUnassociatedWarnings(withStarExports.writer, selected.messages, withStarExports.snapshot),
  }
  const withPackageComment = Match.value(
    Snapshot.workingPackage(withUnassociated.snapshot).tsdocComment === undefined,
  ).pipe(
    Match.when(true, () => ({
      ...withUnassociated,
      writer: writeLineAsComments(
        TextWriter.ensureSkippedLine(withUnassociated.writer),
        '(No @packageDocumentation comment for this package)',
      ),
    })),
    Match.when(false, () => withUnassociated),
    Match.exhaustive,
  )
  const closed = TextWriter.writeLine(TextWriter.ensureSkippedLine(withPackageComment.writer), '```')
  return {
    text: TextWriter.getText(closed).replace(_trimSpacesRegExp, ''),
    consumed: HashSet.union(withPackageComment.handled, HashSet.fromIterable(withPackageComment.consumed)),
  }
}

export const areEquivalentApiFileContents = (actualFileContent: string, expectedFileContent: string): boolean => {
  const normalizedActual = actualFileContent.replace(/\s+/g, ' ')
  const normalizedExpected = expectedFileContent.replace(/\s+/g, ' ')
  return normalizedActual === normalizedExpected
}

export const generateReviewFileContent = (
  snapshot: Snapshot.AnalysisSnapshot,
  reportVariant: ApiReportVariant,
  handled: HashSet.HashSet<number>,
): Result.Result<RenderedApiReport, ReportRenderFailure> => {
  const header = writeReportHeader(
    TextWriter.make({ trimLeadingSpaces: true }),
    Snapshot.workingPackage(snapshot).name,
    reportVariant,
  )
  return Result.flatMap(writeImports(writeTripleSlashDirectives(header, snapshot), snapshot), (writer) => {
    const initial: Result.Result<ReportState, ReportRenderFailure> = Result.succeed({
      writer,
      snapshot,
      reportVariant,
      handled,
      consumed: HashSet.empty(),
      processedSignatures: HashSet.empty(),
    })
    return Result.map(
      Arr.reduce(
        Snapshot.entities(snapshot),
        initial,
        (accumulated, entity) => Result.flatMap(accumulated, (current) => emitEntity(current, entity)),
      ),
      finishReport,
    )
  })
}
