import * as Pipeable from 'effect/Pipeable'
import * as ts from 'typescript'

import { AstDeclaration } from '../analyzer/AstDeclaration.js'
import type { AstEntity } from '../analyzer/AstEntity.js'
import { AstImport } from '../analyzer/AstImport.js'
import { AstNamespaceImport } from '../analyzer/AstNamespaceImport.js'
import { AstSymbol } from '../analyzer/AstSymbol.js'
import { IndentedWriter } from '../analyzer/indented-writer.js'
import { SourceFileLocationFormatter } from '../analyzer/SourceFileLocationFormatter.js'
import { Span } from '../analyzer/Span.js'
import { SyntaxHelpers } from '../analyzer/SyntaxHelpers.js'
import { convertToLf } from '../analyzer/text.js'
import { TypeScriptHelpers } from '../analyzer/TypeScriptHelpers.js'
import type { ApiItemMetadata } from '../collector/ApiItemMetadata.js'
import { Collector } from '../collector/Collector.js'
import type { CollectorEntity } from '../collector/CollectorEntity.js'
import { ExtractorMessageId } from '../collector/extractor-message-id.js'
import { ExtractorMessage } from '../collector/message-log.js'
import type { ApiReportVariant } from '../config/config-file.schema.js'
import { UnsupportedStarExportError } from '../errors/index.js'
import { ReleaseTag } from '../model/index.js'
import { invariant } from '../utils/invariant.js'
import { DtsEmitHelpers } from './dts-emit-helpers.js'

interface IContext {
  readonly collector: Collector
  readonly reportVariant: ApiReportVariant
  readonly alreadyProcessedSignatures: Set<Span>
}

const _trimSpacesRegExp: RegExp = / +$/gm

const DEFAULT_TAGS_TO_REPORT: Readonly<Record<string, boolean>> = {
  '@sealed': true,
  '@virtual': true,
  '@override': true,
  '@eventProperty': true,
  '@deprecated': true,
}

const capitalizeFirstLetter = (input: string): string =>
  input.length === 0 ? '' : `${input[0]?.toLocaleUpperCase() ?? ''}${input.slice(1)}`

const writeReportHeader = (writer: IndentedWriter, packageName: string, reportVariant: ApiReportVariant): void => {
  const releaseLevelPrefix = reportVariant === 'complete' ? '' : `${capitalizeFirstLetter(reportVariant)} `
  writer.writeLine(`## ${releaseLevelPrefix}API Report File for "${packageName}"\n`)
  writer.writeLine(
    `> Do not edit this file. It is a report generated by [API Extractor](https://api-extractor.com/).\n`,
  )
  writer.writeLine('```ts\n')
}

const writeTripleSlashDirectives = (writer: IndentedWriter, collector: Collector): void => {
  for (const typeDirectiveReference of Array.from(collector.dtsTypeReferenceDirectives).sort()) {
    writer.writeLine(`/// <reference types="${typeDirectiveReference}" />`)
  }
  for (const libDirectiveReference of Array.from(collector.dtsLibReferenceDirectives).sort()) {
    writer.writeLine(`/// <reference lib="${libDirectiveReference}" />`)
  }
  writer.ensureSkippedLine()
}

const writeImports = (writer: IndentedWriter, collector: Collector): void => {
  for (const entity of collector.entities) {
    if (entity.astEntity instanceof AstImport) {
      DtsEmitHelpers.emitImport(writer, entity, entity.astEntity)
    }
  }
  writer.ensureSkippedLine()
}

const emitNamespaceExportClauses = (
  writer: IndentedWriter,
  collector: Collector,
  exportedLocalEntities: ReadonlyMap<string, AstEntity>,
  namespaceName: string,
): void => {
  writer.increaseIndent()
  writer.writeLine('export {')
  writer.increaseIndent()

  const exportClauses: string[] = []
  for (const [exportedName, astEntity] of exportedLocalEntities) {
    const collectorEntity = collector.tryGetCollectorEntity(astEntity)
    if (collectorEntity === undefined) {
      throw invariant(`Cannot find collector entity for ${namespaceName}.${astEntity.localName}`)
    }

    const nameForEmit = collectorEntity.nameForEmit ?? ''
    if (nameForEmit === exportedName) {
      exportClauses.push(nameForEmit)
    } else {
      const safeExportedName = SyntaxHelpers.isSafeUnquotedMemberIdentifier(exportedName)
        ? exportedName
        : JSON.stringify(exportedName)
      exportClauses.push(`${nameForEmit} as ${safeExportedName}`)
    }
  }
  writer.writeLine(exportClauses.join(',\n'))

  writer.decreaseIndent()
  writer.writeLine('}')
  writer.decreaseIndent()
  writer.writeLine('}')
}

const emitNamespaceEntity = (
  writer: IndentedWriter,
  collector: Collector,
  entity: CollectorEntity,
  astEntity: AstNamespaceImport,
): void => {
  const astModuleExportInfo = astEntity.fetchAstModuleExportInfo(collector)

  if (entity.nameForEmit === undefined || entity.nameForEmit.length === 0) {
    throw invariant('referencedEntry.nameForEmit is undefined')
  }

  if (astModuleExportInfo.starExportedExternalModules.size > 0) {
    throw new UnsupportedStarExportError({
      namespaceName: entity.nameForEmit,
      moduleSpecifier: SourceFileLocationFormatter.formatDeclaration(astEntity.declaration),
    })
  }

  writer.ensureSkippedLine()
  writer.writeLine(`declare namespace ${entity.nameForEmit} {`)
  emitNamespaceExportClauses(writer, collector, astModuleExportInfo.exportedLocalEntities, entity.nameForEmit)
}

const emitSymbolDeclarations = (
  writer: IndentedWriter,
  collector: Collector,
  entity: CollectorEntity,
  astEntity: AstSymbol,
  reportVariant: ApiReportVariant,
  context: IContext,
  exportsToEmit: Map<string, { readonly associatedMessages: ExtractorMessage[] }>,
): void => {
  for (const astDeclaration of astEntity.astDeclarations) {
    const fetchedMessages = collector.reportMessages.associatedReportMessages(astDeclaration)

    const messagesToReport: ExtractorMessage[] = []
    for (const message of fetchedMessages) {
      const exportName = message.properties.exportName
      const exportToEmit = exportName === undefined ? undefined : exportsToEmit.get(exportName)
      if (exportToEmit !== undefined) {
        exportToEmit.associatedMessages.push(message)
        continue
      }
      messagesToReport.push(message)
    }

    if (_shouldIncludeDeclaration(collector, astDeclaration, reportVariant)) {
      writer.ensureSkippedLine()
      writer.write(_getAedocSynopsis(collector, astDeclaration, messagesToReport))

      const span = new Span(astDeclaration.declaration)
      const apiItemMetadata = collector.fetchApiItemMetadata(astDeclaration)
      if (apiItemMetadata.isPreapproved) {
        _modifySpanForPreapproved(span)
      } else {
        _modifySpan(span, entity, astDeclaration, false, context)
      }

      span.writeModifiedText(writer)
      writer.ensureNewLine()
    }
  }
}

const emitEntity = (
  writer: IndentedWriter,
  collector: Collector,
  entity: CollectorEntity,
  reportVariant: ApiReportVariant,
  context: IContext,
): void => {
  const astEntity = entity.astEntity
  const symbolMetadata = collector.tryFetchMetadataForAstEntity(astEntity)
  const maxEffectiveReleaseTag = symbolMetadata?.maxEffectiveReleaseTag ?? ReleaseTag.None

  if (!_shouldIncludeReleaseTag(maxEffectiveReleaseTag, reportVariant)) {
    return
  }

  const includeForgotten = collector.extractorConfig.apiReport.includeForgottenExports ?? false
  if (!entity.consumable && !includeForgotten) {
    return
  }

  const exportsToEmit = new Map<
    string,
    { readonly exportName: string; readonly associatedMessages: ExtractorMessage[] }
  >()
  for (const exportName of entity.exportNames) {
    if (!entity.shouldInlineExport) {
      exportsToEmit.set(exportName, { exportName, associatedMessages: [] })
    }
  }

  if (astEntity instanceof AstSymbol) {
    emitSymbolDeclarations(writer, collector, entity, astEntity, reportVariant, context, exportsToEmit)
  }

  if (astEntity instanceof AstNamespaceImport) {
    emitNamespaceEntity(writer, collector, entity, astEntity)
  }

  for (const exportToEmit of exportsToEmit.values()) {
    if (exportToEmit.associatedMessages.length > 0) {
      writer.ensureSkippedLine()
      for (const message of exportToEmit.associatedMessages) {
        _writeLineAsComments(writer, 'Warning: ' + message.formatMessageWithoutLocation())
      }
    }
    DtsEmitHelpers.emitNamedExport(writer, exportToEmit.exportName, entity)
  }
  writer.ensureSkippedLine()
}

export class ApiReportGenerator extends Pipeable.Class {
  public static areEquivalentApiFileContents(
    actualFileContent: string,
    expectedFileContent: string,
  ): boolean {
    const normalizedActual = actualFileContent.replace(/\s+/g, ' ')
    const normalizedExpected = expectedFileContent.replace(/\s+/g, ' ')
    return normalizedActual === normalizedExpected
  }

  public static generateReviewFileContent(collector: Collector, reportVariant: ApiReportVariant): string {
    const writer = new IndentedWriter()
    writer.trimLeadingSpaces = true

    writeReportHeader(writer, collector.workingPackage.name, reportVariant)
    writeTripleSlashDirectives(writer, collector)
    writeImports(writer, collector)

    const context: IContext = {
      collector,
      reportVariant,
      alreadyProcessedSignatures: new Set(),
    }

    for (const entity of collector.entities) {
      emitEntity(writer, collector, entity, reportVariant, context)
    }

    DtsEmitHelpers.emitStarExports(writer, collector)

    const unassociatedMessages = collector.reportMessages.unassociatedReportMessages()
    if (unassociatedMessages.length > 0) {
      writer.ensureSkippedLine()
      _writeLineAsComments(writer, 'Warnings were encountered during analysis:')
      _writeLineAsComments(writer, '')
      for (const message of unassociatedMessages) {
        _writeLineAsComments(
          writer,
          message.formatMessageWithLocation(collector.workingPackage.packageFolder),
        )
      }
    }

    if (collector.workingPackage.tsdocComment === undefined) {
      writer.ensureSkippedLine()
      _writeLineAsComments(writer, '(No @packageDocumentation comment for this package)')
    }

    writer.ensureSkippedLine()
    writer.writeLine('```')

    return writer.toString().replace(_trimSpacesRegExp, '')
  }
}

const handleExportKeyword = (span: Span): void => {
  if (DtsEmitHelpers.isExportKeywordInNamespaceExportDeclaration(span.node)) {
    return
  }
  span.modification.skipAll()
}

const handleKeywordModifiers = (span: Span, entity: CollectorEntity): void => {
  let replacedModifiers = ''
  if (entity.shouldInlineExport) {
    replacedModifiers = 'export ' + replacedModifiers
  }
  const previousSpan = span.previousSibling
  if (previousSpan !== undefined && previousSpan.kind === ts.SyntaxKind.SyntaxList) {
    previousSpan.modification.prefix = replacedModifiers + previousSpan.modification.prefix
  } else {
    span.modification.prefix = replacedModifiers + span.modification.prefix
  }
}

const handleVariableDeclaration = (span: Span, entity: CollectorEntity): void => {
  if (span.parent !== undefined) {
    return
  }
  const list = TypeScriptHelpers.matchAncestor<ts.VariableDeclarationList>(span.node, [
    ts.SyntaxKind.VariableDeclarationList,
    ts.SyntaxKind.VariableDeclaration,
  ])
  if (list === undefined) {
    throw invariant('Unsupported variable declaration')
  }
  const sourceFile = list.getSourceFile()
  const firstDeclStart = list.declarations[0]?.getStart() ?? list.getStart()
  const listPrefix = sourceFile.text.substring(list.getStart(), firstDeclStart)
  span.modification.prefix = listPrefix + span.modification.prefix
  span.modification.suffix = ';'

  if (entity.shouldInlineExport) {
    span.modification.prefix = 'export ' + span.modification.prefix
  }
}

const handleParameter = (span: Span, context: IContext): void => {
  const signatureParent = span.parent
  if (signatureParent !== undefined) {
    if (!context.alreadyProcessedSignatures.has(signatureParent)) {
      context.alreadyProcessedSignatures.add(signatureParent)
      DtsEmitHelpers.normalizeParameterNames(signatureParent)
    }
  }
}

const handleIdentifier = (span: Span, collector: Collector): void => {
  if (!ts.isIdentifier(span.node)) {
    return
  }
  const referencedEntity = collector.tryGetEntityForNode(span.node)
  if (referencedEntity !== undefined) {
    if (referencedEntity.nameForEmit === undefined || referencedEntity.nameForEmit.length === 0) {
      throw invariant('referencedEntry.nameForEmit is undefined')
    }
    span.modification.prefix = referencedEntity.nameForEmit
  }
}

const handleSyntaxList = (span: Span): boolean => {
  if (span.parent === undefined) {
    return false
  }
  return AstDeclaration.isSupportedSyntaxKind(span.parent.kind) || span.parent.kind === ts.SyntaxKind.ModuleBlock
}

const isKeywordNeedingModifiers = (kind: ts.SyntaxKind): boolean =>
  kind === ts.SyntaxKind.InterfaceKeyword ||
  kind === ts.SyntaxKind.ClassKeyword ||
  kind === ts.SyntaxKind.EnumKeyword ||
  kind === ts.SyntaxKind.NamespaceKeyword ||
  kind === ts.SyntaxKind.ModuleKeyword ||
  kind === ts.SyntaxKind.TypeKeyword ||
  kind === ts.SyntaxKind.FunctionKeyword

function _modifySpan(
  span: Span,
  entity: CollectorEntity,
  astDeclaration: AstDeclaration,
  insideTypeLiteral: boolean,
  context: IContext,
): void {
  const { collector, reportVariant } = context

  if (!_shouldIncludeDeclaration(collector, astDeclaration, reportVariant)) {
    span.modification.skipAll()
    return
  }

  let recurseChildren = true
  let sortChildren = false
  let nextInsideTypeLiteral = insideTypeLiteral

  if (span.kind === ts.SyntaxKind.JSDocComment) {
    span.modification.skipAll()
    recurseChildren = false
  } else if (span.kind === ts.SyntaxKind.ExportKeyword) {
    handleExportKeyword(span)
  } else if (span.kind === ts.SyntaxKind.DefaultKeyword || span.kind === ts.SyntaxKind.DeclareKeyword) {
    span.modification.skipAll()
  } else if (isKeywordNeedingModifiers(span.kind)) {
    handleKeywordModifiers(span, entity)
  } else if (span.kind === ts.SyntaxKind.SyntaxList) {
    sortChildren = handleSyntaxList(span)
  } else if (span.kind === ts.SyntaxKind.VariableDeclaration) {
    handleVariableDeclaration(span, entity)
  } else if (span.kind === ts.SyntaxKind.Parameter) {
    handleParameter(span, context)
  } else if (span.kind === ts.SyntaxKind.Identifier) {
    handleIdentifier(span, collector)
  } else if (span.kind === ts.SyntaxKind.TypeLiteral) {
    nextInsideTypeLiteral = true
  } else if (span.kind === ts.SyntaxKind.ImportType) {
    DtsEmitHelpers.modifyImportTypeSpan(
      collector,
      span,
      astDeclaration,
      (childSpan, childAstDeclaration) => {
        _modifySpan(childSpan, entity, childAstDeclaration, nextInsideTypeLiteral, context)
      },
    )
  }

  if (recurseChildren) {
    for (const child of span.children) {
      let childAstDeclaration: AstDeclaration = astDeclaration

      if (AstDeclaration.isSupportedSyntaxKind(child.kind)) {
        childAstDeclaration = collector.astSymbolTable.getChildAstDeclarationByNode(
          child.node,
          astDeclaration,
        )

        if (_shouldIncludeDeclaration(collector, childAstDeclaration, reportVariant)) {
          if (sortChildren) {
            span.modification.sortChildren = true
            child.modification.sortKey = Collector.getSortKeyIgnoringUnderscore(
              childAstDeclaration.astSymbol.localName,
            )
          }

          if (!nextInsideTypeLiteral) {
            const messagesToReport = collector.reportMessages.associatedReportMessages(childAstDeclaration)
            const aedocSynopsis = _getAedocSynopsis(collector, childAstDeclaration, messagesToReport)
            child.modification.prefix = aedocSynopsis + child.modification.prefix
          }
        }
      }

      _modifySpan(child, entity, childAstDeclaration, nextInsideTypeLiteral, context)
    }
  }
}

function _shouldIncludeDeclaration(
  collector: Collector,
  astDeclaration: AstDeclaration,
  reportVariant: ApiReportVariant,
): boolean {
  // eslint-disable-next-line no-bitwise
  if ((astDeclaration.modifierFlags & ts.ModifierFlags.Private) !== 0) {
    return false
  }

  const apiItemMetadata = collector.fetchApiItemMetadata(astDeclaration)
  return _shouldIncludeReleaseTag(apiItemMetadata.effectiveReleaseTag, reportVariant)
}

function _shouldIncludeReleaseTag(releaseTag: ReleaseTag, reportVariant: ApiReportVariant): boolean {
  switch (reportVariant) {
    case 'complete':
      return true
    case 'alpha':
      return (
        releaseTag === ReleaseTag.Alpha ||
        releaseTag === ReleaseTag.Beta ||
        releaseTag === ReleaseTag.Public ||
        releaseTag === ReleaseTag.None
      )
    case 'beta':
      return (
        releaseTag === ReleaseTag.Beta ||
        releaseTag === ReleaseTag.Public ||
        releaseTag === ReleaseTag.None
      )
    case 'public':
      return (
        releaseTag === ReleaseTag.Public ||
        releaseTag === ReleaseTag.None
      )
  }
}

function _modifySpanForPreapproved(span: Span): void {
  let skipRest = false
  for (const child of span.children) {
    if (skipRest || child.kind === ts.SyntaxKind.SyntaxList || child.kind === ts.SyntaxKind.JSDocComment) {
      child.modification.skipAll()
    }
    if (child.kind === ts.SyntaxKind.Identifier) {
      skipRest = true
      child.modification.omitSeparatorAfter = true
      child.modification.suffix = ' { /* (preapproved) */ }'
    }
  }
}

interface StandardTagsConfig {
  readonly reportSealedTag?: boolean | undefined
  readonly reportVirtualTag?: boolean | undefined
  readonly reportOverrideTag?: boolean | undefined
  readonly reportEventPropertyTag?: boolean | undefined
  readonly reportDeprecatedTag?: boolean | undefined
}

const collectStandardTags = (
  apiItemMetadata: ApiItemMetadata,
  tags: StandardTagsConfig,
  parts: string[],
): void => {
  if (tags.reportSealedTag === true && apiItemMetadata.isSealed) parts.push('@sealed')
  if (tags.reportVirtualTag === true && apiItemMetadata.isVirtual) parts.push('@virtual')
  if (tags.reportOverrideTag === true && apiItemMetadata.isOverride) parts.push('@override')
  if (tags.reportEventPropertyTag === true && apiItemMetadata.isEventProperty) parts.push('@eventProperty')
  if (tags.reportDeprecatedTag === true && apiItemMetadata.tsdocComment?.deprecatedBlock !== undefined) {
    parts.push('@deprecated')
  }
}

const collectCustomTags = (
  apiItemMetadata: ApiItemMetadata,
  otherTags: Readonly<Record<string, boolean | undefined>>,
  parts: string[],
): void => {
  for (const [tag, shouldReport] of Object.entries(otherTags)) {
    if (shouldReport === true) {
      if (apiItemMetadata.tsdocComment?.customBlocks.some((b) => b.blockTag.tagName === tag) === true) {
        parts.push(tag)
      } else if (apiItemMetadata.tsdocComment?.modifierTagSet.hasTagName(tag) === true) {
        parts.push(tag)
      }
    }
  }
}

function _getAedocSynopsis(
  collector: Collector,
  astDeclaration: AstDeclaration,
  messagesToReport: readonly ExtractorMessage[] = [],
): string {
  const writer = new IndentedWriter()

  if (collector.isAncillaryDeclaration(astDeclaration)) {
    return ''
  }

  for (const message of messagesToReport) {
    _writeLineAsComments(writer, 'Warning: ' + message.formatMessageWithoutLocation())
  }

  const footerParts: string[] = []
  const apiItemMetadata = collector.fetchApiItemMetadata(astDeclaration)

  if (!apiItemMetadata.releaseTagSameAsParent && apiItemMetadata.effectiveReleaseTag !== ReleaseTag.None) {
    footerParts.push(ReleaseTag.getTagName(apiItemMetadata.effectiveReleaseTag))
  }

  const configTags = collector.extractorConfig.apiReport.tagsToReport ?? {}
  const tagsToReport = {
    ...DEFAULT_TAGS_TO_REPORT,
    ...configTags,
  }

  const {
    '@sealed': reportSealedTag,
    '@virtual': reportVirtualTag,
    '@override': reportOverrideTag,
    '@eventProperty': reportEventPropertyTag,
    '@deprecated': reportDeprecatedTag,
    ...otherTagsToReport
  } = tagsToReport

  collectStandardTags(
    apiItemMetadata,
    { reportSealedTag, reportVirtualTag, reportOverrideTag, reportEventPropertyTag, reportDeprecatedTag },
    footerParts,
  )
  collectCustomTags(apiItemMetadata, otherTagsToReport, footerParts)

  if (apiItemMetadata.undocumented) {
    footerParts.push('(undocumented)')
    collector.addAnalyzerIssue(
      ExtractorMessageId.Undocumented,
      `Missing documentation for "${astDeclaration.astSymbol.localName}".`,
      astDeclaration,
    )
  }

  if (footerParts.length > 0) {
    if (messagesToReport.length > 0) {
      _writeLineAsComments(writer, '')
    }

    _writeLineAsComments(writer, footerParts.join(' '))
  }

  return writer.toString()
}

function _writeLineAsComments(writer: IndentedWriter, line: string): void {
  const lines: string[] = convertToLf(line).split('\n')
  for (const realLine of lines) {
    writer.write('// ')
    writer.write(realLine)
    writer.writeLine()
  }
}
