export enum ProjectType {
  ANGULAR = 'angular',
  EMBER = 'ember',
  HTML = 'html',
  NEXTJS = 'nextjs',
  NUXT = 'nuxt',
  NX = 'nx',
  PREACT = 'preact',
  QWIK = 'qwik',
  REACT = 'react',
  TANSTACK_REACT = 'tanstack_react',
  REACT_NATIVE = 'react_native',
  REACT_NATIVE_AND_RNW = 'react_native_and_rnw',
  REACT_NATIVE_WEB = 'react_native_web',
  REACT_SCRIPTS = 'react_scripts',
  SERVER = 'server',
  SOLID = 'solid',
  SVELTE = 'svelte',
  SVELTEKIT = 'sveltekit',
  UNDETECTED = 'undetected',
  UNSUPPORTED = 'unsupported',
  VUE3 = 'vue3',
  WEB_COMPONENTS = 'web_components',
}
