/**
 * Generated by tsnapi — public API snapshot of `tsdown/internal`
 */
// #region Interfaces
export interface Logger {
  level: LogLevel;
  options?: LoggerOptions;
  info: (..._: any[]) => void;
  warn: (..._: any[]) => void;
  warnOnce: (..._: any[]) => void;
  error: (..._: any[]) => void;
  success: (..._: any[]) => void;
  clearScreen: (_: LogType) => void;
}
// #endregion

// #region Types
export type MarkPartial<T, K extends keyof T> = Omit<Required<T>, K> & Partial<Pick<T, K>>;
export type Overwrite<T, U> = Omit<T, keyof U> & U;
// #endregion

// #region Functions
export declare function expandBaselineTarget(_: string[]): string[];
export declare function fsExists(_: string): Promise<boolean>;
export declare function fsRemove(_: string): Promise<void>;
export declare function importWithError<T>(_: string): Promise<T>;
export declare function resolveComma<T extends string>(_: T[]): T[];
export declare function toArray<T>(_: T | T[] | null | undefined, _?: T): T[];
// #endregion

// #region Variables
export declare const NODE_SEA_MIN_VERSION: string;
export declare const NODE_SEA_MIN_VERSION_PARSED: SemVer;
// #endregion