/**
 * Generated by tsnapi — public API snapshot of `tsdown/plugins`
 */
// #region Functions
export declare function DepsPlugin({ pkg, deps: { neverBundle, alwaysBundle: jsAlwaysBundle, onlyBundle, onlyImport, resolveDepSubpath: shouldResolveDepSubpath, dts }, logger, nameLabel, platform }: ResolvedConfig, _: TsdownBundle): Plugin;
export declare function NodeProtocolPlugin(_: "strip" | true): Plugin;
export declare function ReportPlugin(_: ResolvedConfig, _?: boolean, _?: boolean): Plugin;
export declare function ShebangPlugin(_: Logger, _: string, _?: string, _?: boolean): Plugin;
export declare function WatchPlugin(_: Set<string>, { config, chunks }: TsdownBundle): Plugin;
// #endregion