#!/usr/bin/env -S deno run --allow-read=packages,node_modules --allow-write=packages/oxlint-plugins/effect-executor/src/rules
// The executor rules' phase/purity/I/O vocabulary, generated by walking a Cell description.
//
// `packages/oxlint-plugins/effect-executor` cannot import the description: turbo reports the cycle
// `effect-executor -> effect-cell-types -> effect-gherkin-spec -> oxlint-config -> effect-dmmf ->
// effect-executor`, and names that first edge as the only breakable one. So the vocabulary arrives
// as a committed generated module instead, and `--check` is what makes it a derivation rather than a
// copy: it re-renders from a fresh walk and fails on any differing byte, so the constants cannot
// drift from the description while the rules keep judging every package the aggregate reaches.
//
//   deno run --allow-read=packages,node_modules \
//     --allow-write=packages/oxlint-plugins/effect-executor/src/rules \
//     scripts/guards/generate-executor-vocabulary.ts [--check]

// Mapped in scripts/guards/deno.jsonc to the description's source. This file is the walk's only
// input: nothing about a phase is written down here.
import * as Cell from '@systemfsoftware/effect-cell-types'

const OUT = new URL(
  '../../packages/oxlint-plugins/effect-executor/src/rules/vocabulary.generated.ts',
  import.meta.url,
)

const quoted = (value: string): string => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
const tuple = (values: readonly string[]): string => `[${values.map(quoted).join(', ')}] as const`

const { applier, byKind, ioCells, module, phases } = Cell.vocabulary

// A walk that yields nothing is not a permissive rule, it is a disarmed one: every predicate these
// constants feed is set membership, so an empty set matches no call and both rules go quiet while
// staying registered at error. Refusing to render is the only honest failure.
//
// Only the pure partition needs a runtime check. The I/O classification is a `const` tuple, so
// `ioCells.cells.length === 0` is a comparison the compiler rejects as impossible — the type already
// carries what a guard here would re-assert.
if (byKind.pure.length === 0) {
  throw new Error('generate-executor-vocabulary: the walked vocabulary reports no pure phase')
}

const body = `// GENERATED by scripts/guards/generate-executor-vocabulary.ts — do not edit.
//
// Every value below is read off \`Cell.vocabulary\`, which is itself folded from a description the
// public constructors build. Regenerate with:
//
//   pnpm vocabulary:executor
//
// \`pnpm check:executor-vocabulary\` re-renders this file and fails on any differing byte, so an
// edit here is reverted by the gate rather than surviving as a second declaration.

/** The description package whose phases chain by type. */
export const DESCRIPTION_SOURCE = ${quoted(module)}

/** Phase constructors whose bodies are pure: a store, adapter or clock call inside one is a violation. */
export const PURE_PHASES = ${tuple(byKind.pure)}

/** Cells whose calls are I/O. */
export const IO_CELLS = ${tuple(ioCells.cells)}

/** Non-cell module sources whose calls are I/O. */
export const IO_SOURCES = ${tuple(ioCells.sources)}

/** Every call on the description module that belongs to a description: each phase, plus the applier. */
export const DESCRIPTION_METHODS = ${tuple([...phases.map((phase) => phase.name), applier])}
`

const existing = await Deno.readTextFile(OUT).catch(() => undefined)

if (Deno.args.includes('--check')) {
  if (existing === undefined) {
    console.error(`generate-executor-vocabulary: ${OUT.pathname} is missing — run \`pnpm vocabulary:executor\``)
    Deno.exit(1)
  }
  if (existing !== body) {
    console.error(
      `generate-executor-vocabulary: ${OUT.pathname} does not reproduce from a walk of ${phases.length} phases, ${ioCells.cells.length} I/O cells and ${ioCells.sources.length} I/O sources.\n` +
        'It is generated — run `pnpm vocabulary:executor` and commit the result rather than editing it.',
    )
    Deno.exit(1)
  }
  console.log(
    `generate-executor-vocabulary: reproduces byte-for-byte from a walk of ${phases.length} phases, ${byKind.pure.length} pure`,
  )
} else {
  await Deno.writeTextFile(OUT, body)
  console.log(
    `generate-executor-vocabulary: wrote ${OUT.pathname} from a walk of ${phases.length} phases, ${byKind.pure.length} pure, ${ioCells.cells.length} I/O cells`,
  )
}
