// Generated from the Rust N-API exports by `pnpm generate:native-types`.
// Do not edit this file directly.

export declare class CancellationToken {
  constructor()
  cancel(): void
  get cancelled(): boolean
}

export declare class Executable {
  get diagnostics(): NativeExecutableDiagnostics
  get stateful(): boolean
  get batch(): number
  get packedRowsPerSequence(): number | null
  get allowsWindowEviction(): boolean
  get layers(): number
  get kvHeads(): number
  get headDim(): number
  get kdaLayers(): number
  get kdaHeads(): number
  get kdaHeadDim(): number
  get kdaValueDim(): number
  get convLayers(): number
  get convChannels(): number
  get convKernel(): number
  execute(inputs: Array<NativeTensor>, scalars: Array<number>, sequences?: Array<NativeKvSequence> | undefined | null, slots?: Array<number> | undefined | null, activeMask?: Array<boolean> | undefined | null, validLengths?: Array<number> | undefined | null, advances?: Array<number> | undefined | null, tokens?: Array<Array<number>> | undefined | null, token?: CancellationToken | undefined | null): Promise<Array<NativeTensor>>
  executeSampled(inputs: Array<NativeTensor>, sequences: Array<NativeKvSequence>, slots: Array<number>, activeMask: Array<boolean>, validLengths: Array<number>, advances: Array<number>, tokens: Array<Array<number>>, sampling: Array<NativeSamplingOptions>, cancellationToken?: CancellationToken | undefined | null): Promise<Array<number>>
  executeSpeculative(proposer: Executable, targetSequences: Array<NativeKvSequence>, proposerSequences: Array<NativeKvSequence>, slots: Array<number>, pendingTokens: Array<number>, sampling: Array<NativeSamplingOptions>, maxDraftTokens: number, pageLimits: Array<number>, eosTokens: Array<Array<number>>, cancellationToken?: CancellationToken | undefined | null): Promise<Array<Array<number>>>
}

export declare class LazyTensor {
  get shape(): Array<number>
  get dtype(): string
  metadata(): [Array<number>, string]
  static zeros(shape: Array<number>, dtype?: NativeDType | undefined | null, deviceOrdinal?: number | undefined | null): LazyTensor
  static ones(shape: Array<number>, dtype?: NativeDType | undefined | null, deviceOrdinal?: number | undefined | null): LazyTensor
  static full(shape: Array<number>, value: number, dtype?: NativeDType | undefined | null, deviceOrdinal?: number | undefined | null): LazyTensor
  static randn(shape: Array<number>, dtype?: NativeDType | undefined | null, deviceOrdinal?: number | undefined | null): LazyTensor
  static uniform(shape: Array<number>, lo: number, hi: number, dtype?: NativeDType | undefined | null, deviceOrdinal?: number | undefined | null): LazyTensor
  static arange(start: number, end: number, step: number, dtype?: NativeDType | undefined | null, deviceOrdinal?: number | undefined | null): LazyTensor
  static eye(n: number, dtype?: NativeDType | undefined | null, deviceOrdinal?: number | undefined | null): LazyTensor
  static constant(value: number, dtype?: NativeDType | undefined | null, deviceOrdinal?: number | undefined | null): LazyTensor
  static fromBytes(data: Uint8Array, shape: Array<number>, dtype?: NativeDType | undefined | null, deviceOrdinal?: number | undefined | null): LazyTensor
  static fromMaterialized(tensor: NativeTensor): LazyTensor
  static input(slot: number, shape: Array<number>, dtype?: NativeDType | undefined | null, deviceOrdinal?: number | undefined | null): LazyTensor
  static scalarInput(slot: number, dtype?: NativeDType | undefined | null, deviceOrdinal?: number | undefined | null): LazyTensor
  add(other: LazyTensor): LazyTensor
  sub(other: LazyTensor): LazyTensor
  mul(other: LazyTensor): LazyTensor
  div(other: LazyTensor): LazyTensor
  maximum(other: LazyTensor): LazyTensor
  minimum(other: LazyTensor): LazyTensor
  eq(other: LazyTensor): LazyTensor
  gt(other: LazyTensor): LazyTensor
  lt(other: LazyTensor): LazyTensor
  ge(other: LazyTensor): LazyTensor
  le(other: LazyTensor): LazyTensor
  matmul(other: LazyTensor): LazyTensor
  inverse(): LazyTensor
  det(): LazyTensor
  solve(other: LazyTensor): LazyTensor
  neg(): LazyTensor
  abs(): LazyTensor
  sqrt(): LazyTensor
  exp(): LazyTensor
  tanh(): LazyTensor
  gelu(approximate?: boolean | undefined | null): LazyTensor
  relu(): LazyTensor
  erf(): LazyTensor
  floor(): LazyTensor
  ceil(): LazyTensor
  round(): LazyTensor
  sign(): LazyTensor
  whereCond(a: LazyTensor, b: LazyTensor): LazyTensor
  argmax(dim: number): LazyTensor
  argmin(dim: number): LazyTensor
  cumsum(dim: number): LazyTensor
  indexSelect(dim: number, indexes: LazyTensor): LazyTensor
  scatterAdd(dim: number, indexes: LazyTensor, src: LazyTensor): LazyTensor
  gather(dim: number, indexes: LazyTensor): LazyTensor
  crossEntropy(target: LazyTensor, ignoreIndex: number): LazyTensor
  scaledDotProductAttention(k: LazyTensor, v: LazyTensor, scale: number, causal: boolean, window: number): LazyTensor
  kdaChunk(k: LazyTensor, v: LazyTensor, logDecay: LazyTensor, beta: LazyTensor, scale: number): LazyTensor
  shortConv1d(weight: LazyTensor): LazyTensor
  positionEmbedding(seqLen: number): LazyTensor
  rotaryEmbedding(seqLen: number, theta: number, layout: string): LazyTensor
  layerNorm(weight: LazyTensor, bias: LazyTensor, eps: number): LazyTensor
  rmsNorm(weight: LazyTensor | undefined | null, eps: number): LazyTensor
  linear(weight: LazyTensor, bias: LazyTensor): LazyTensor
  quantizedLinear(weight: LazyTensor, bias: LazyTensor | undefined | null, encoding: string, rows: number, columns: number): LazyTensor
  quantizedEmbedding(weight: LazyTensor, encoding: string, rows: number, columns: number, paddingIndex?: number | undefined | null): LazyTensor
  conv1d(w: LazyTensor, stride: number, padding: number, dilation: number, groups: number): LazyTensor
  conv2d(w: LazyTensor, stride: number, padding: number, dilation: number, groups: number): LazyTensor
  log(): LazyTensor
  sin(): LazyTensor
  cos(): LazyTensor
  pow(exp: number): LazyTensor
  cast(dtype: NativeDType): LazyTensor
  sum(dims: Array<number>, keepdims: boolean): LazyTensor
  prod(dims: Array<number>, keepdims: boolean): LazyTensor
  mean(dims: Array<number>, keepdims: boolean): LazyTensor
  max(dims: Array<number>, keepdims: boolean): LazyTensor
  min(dims: Array<number>, keepdims: boolean): LazyTensor
  reshape(shape: Array<number>): LazyTensor
  permute(dims: Array<number>): LazyTensor
  slice(ranges: Array<Array<number>>): LazyTensor
  concat(other: LazyTensor, dim: number): LazyTensor
  broadcastTo(shape: Array<number>): LazyTensor
  stopGradient(): LazyTensor
  expose(name: string): LazyTensor
  /**
   * Walks the lazy graph reachable from this node and returns every
   * exposure (name plus the wrapped tensor) in deterministic first-visit
   * order; duplicate names are a caller error.
   */
  exposures(): Array<NativeExposure>
  checkpoint(): LazyTensor
  vmap(x: LazyTensor, batchedX: LazyTensor, dim: number): LazyTensor
  adamwStep(grad: LazyTensor, m: LazyTensor, v: LazyTensor, lr: LazyTensor, c1: LazyTensor, c2: LazyTensor, beta1: number, beta2: number, eps: number, weightDecay: number): LazyTensor
  adamwOut(index: number): LazyTensor
  sgdStep(grad: LazyTensor, velocity: LazyTensor, first: LazyTensor, lr: LazyTensor, momentum: number, dampening: number, nesterov: boolean, weightDecay: number): LazyTensor
  sgdOut(index: number): LazyTensor
}

/**
 * One named exposure discovered in a lazy graph: the name and the wrapped
 * tensor handle (the exposure node's child).
 */
export declare class NativeExposure {
  get name(): string
  get tensor(): LazyTensor
}

export declare class NativeInferenceArtifact {
  constructor(targetPrefill: Executable, targetDecode: Executable, targetVerify: Array<Executable>, targetPool: NativeKvPool, proposerPrefill: Executable | undefined | null, proposerDecode: Executable | undefined | null, proposerPool: NativeKvPool | undefined | null, maxDraftTokens: number | undefined | null, batchSize: number, tokenDtype: NativeDType, sampling: NativeInferenceSamplingOptions, proposerPlan: NativeProposerPlan | undefined | null, stageExecutables: Array<Executable> | undefined | null, sharedTargetTensors: Array<NativeTensor> | undefined | null, replayPrefill: Executable | undefined | null, replayDecode: Executable | undefined | null, replayVerify: Array<Executable>, replayPool?: NativeKvPool | undefined | null, prefillBuckets?: Array<Executable> | undefined | null, replayPrefillBuckets?: Array<Executable> | undefined | null)
  open(): NativeInferenceSession
  get proposerPlan(): NativeProposerPlan | null
  get inferenceDiagnostics(): NativeInferenceDiagnostics
}

export declare class NativeInferenceSequence {
  get sequenceId(): bigint
}

export declare class NativeInferenceSession {
  add(prompts: Array<NativeTensor>, sampling: Array<NativeInferenceSamplingOverride>, maxTokens: Array<number | undefined | null>, eosTokens: Array<Array<number>>, cancellationToken?: CancellationToken | undefined | null): Promise<NativeInferenceRoundResult>
  runRound(sequences: Array<NativeInferenceSequence>, sampling: Array<NativeInferenceSamplingOverride>, cancellationToken?: CancellationToken | undefined | null): Promise<NativeInferenceRoundResult>
  acknowledge(roundId: bigint): void
  sequence(sequenceId: bigint): NativeInferenceSequence
  finish(sequences: Array<NativeInferenceSequence>): void
  inspect(sequence: NativeInferenceSequence): NativeInferenceInspection
  close(): void
}

export declare class NativeKvPool {
  constructor(layers: number, kvHeads: number, headDim: number, maxTokens: number, blockSize?: number | undefined | null, dtype?: NativeDType | undefined | null, recurrent?: NativeRecurrentStateSchema | undefined | null)
  static forDevice(layers: number, kvHeads: number, headDim: number, maxTokens: number, blockSize: number | undefined | null, dtype: NativeDType | undefined | null, recurrent: NativeRecurrentStateSchema | undefined | null, deviceOrdinal: number): NativeKvPool
  get capacity(): number
  get freeBlocks(): number
  get cachedBlocks(): number
  makeSequence(): NativeKvSequence
}

export declare class NativeKvSequence {
  get cursor(): number
  release(): void
  prefillMatch(tokens: Array<number>): number
}

export declare class NativeTensor {
  /**
   * Releases the tensor's buffer before garbage collection. Later use of the
   * handle or a lazy graph built from it returns a typed error.
   */
  clear(): void
  get shape(): Array<number>
  get dtype(): string
  get device(): string
  readback(token?: CancellationToken | undefined | null): Promise<ArrayBuffer>
  sample(temperature: number, topK: number, topP: number, seed: number, counter: number, cancellationToken?: CancellationToken | undefined | null): Promise<number>
}

export declare function compile(roots: Array<LazyTensor>, options?: NativeCompileOptions | undefined | null, state?: NativeKvStateSchema | undefined | null, cacheKey?: string | undefined | null): Executable

export declare function compileForDevice(roots: Array<LazyTensor>, options: NativeCompileOptions | undefined | null, state: NativeKvStateSchema | undefined | null, cacheKey: string | undefined | null, deviceOrdinal: number): Executable

export declare function externalMemoryBytes(): number

export declare function externalMemoryBytesForDevice(deviceOrdinal: number): number

export declare function grad(loss: LazyTensor, wrt: Array<LazyTensor>): Array<LazyTensor>

/** Parses and validates a GGUF file without loading tensor payloads. */
export declare function inspectGguf(path: string, token?: CancellationToken | undefined | null): Promise<NativeGgufInspection>

export declare function isAvailable(): boolean

export declare function isDeviceAvailable(deviceOrdinal: number): boolean

/** Parses a GGUF file and loads every supported tensor into Metal storage. */
export declare function loadGguf(path: string, token?: CancellationToken | undefined | null): Promise<NativeGgufArchive>

export declare function loadGgufForDevice(path: string, deviceOrdinal: number, token?: CancellationToken | undefined | null): Promise<NativeGgufArchive>

export declare function loadTensors(path: string, token?: CancellationToken | undefined | null): Promise<NativeSafetensorsArchive>

export declare function loadTensorsForDevice(path: string, deviceOrdinal: number, token?: CancellationToken | undefined | null): Promise<NativeSafetensorsArchive>

export interface NativeCompileOptions {
  optimize?: boolean | undefined
  constantWeights?: boolean | undefined
}

export interface NativeCompilePhaseDiagnostics {
  phase: string
  nanoseconds: number
}

export declare const enum NativeCurrentBlockAttention {
  Causal = 'Causal',
  Bidirectional = 'Bidirectional'
}

export declare const enum NativeDecodeOutputSelection {
  AllRows = 'AllRows',
  SplitLastTokenRow = 'SplitLastTokenRow',
  BatchedLastTokenRow = 'BatchedLastTokenRow'
}

export declare const enum NativeDType {
  F32 = 'f32',
  F64 = 'f64',
  I64 = 'i64',
  U8 = 'u8',
  U32 = 'u32',
  F16 = 'f16',
  BF16 = 'bf16'
}

export interface NativeExecutableDiagnostics {
  semanticNodesBeforeOptimization: number
  semanticNodesAfterOptimization: number
  instructions: Array<NativeInstructionDiagnostics>
  pipelineCount: number
  commandCount: number
  synchronizationCount: number
  memory: NativeMemoryDiagnostics
  compilePhases: Array<NativeCompilePhaseDiagnostics>
}

/** Complete loaded archive returned atomically to JavaScript. */
export interface NativeGgufArchive {
  entries: Array<NativeGgufLoadedEntry>
}

/** Header/catalog inspection result without loaded tensor data. */
export interface NativeGgufInspection {
  metadata: Array<NativeGgufMetadataEntry>
  tensors: Array<NativeGgufTensorDescriptor>
}

/** One loaded tensor paired with the descriptor used to validate it. */
export interface NativeGgufLoadedEntry {
  descriptor: NativeGgufTensorDescriptor
  tensor: NativeTensor
}

/** JavaScript representation of one scalar or homogeneous-array metadata item. */
export interface NativeGgufMetadataEntry {
  key: string
  kind: string
  numberValue?: number | undefined
  stringValue?: string | undefined
  booleanValue?: boolean | undefined
  numberArray?: Array<number> | undefined
  stringArray?: Array<string> | undefined
  booleanArray?: Array<boolean> | undefined
}

/** JavaScript-safe logical and physical description of one GGUF tensor. */
export interface NativeGgufTensorDescriptor {
  name: string
  format: string
  logicalShape: Array<number>
  logicalDtype: string
  physicalShape: Array<number>
  physicalDtype: string
}

export interface NativeHistoryLookupLayout {
  id: string
  minMatchTokens: number
  maxMatchTokens: number
}

export interface NativeInferenceDiagnostics {
  roundsStarted: bigint
  roundsCompleted: bigint
  roundsRecovered: bigint
  ordinaryRounds: bigint
  speculativeRounds: bigint
  proposedTokens: bigint
  acceptedTokens: bigint
  emittedTokens: bigint
  provisionalBlocks: bigint
  rolledBackBlocks: bigint
  draftNanos: bigint
  verificationNanos: bigint
  acceptedLengthHistogram: Array<bigint>
  targetPoolHighWaterBlocks: bigint
  proposerPoolHighWaterBlocks?: bigint | undefined
  lastRoundId?: bigint | undefined
  lastFailurePhase?: string | undefined
}

export interface NativeInferenceInspection {
  sequenceId: bigint
  cursor: bigint
  terminal?: string | undefined
}

export interface NativeInferencePage {
  sequenceId: bigint
  tokens: Array<number>
  stopReason?: string | undefined
}

export interface NativeInferenceRoundResult {
  roundId: bigint
  recovered: boolean
  pages: Array<NativeInferencePage>
}

export interface NativeInferenceSamplingOptions {
  temperature: number
  topK: number
  topP: number
  seed: bigint
}

export interface NativeInferenceSamplingOverride {
  temperature?: number | undefined
  topK?: number | undefined
  topP?: number | undefined
  seed?: bigint | undefined
}

export interface NativeInstructionDiagnostics {
  kind: string
  count: number
}

export interface NativeKvStateSchema {
  maxTokens: number
  blockSize: number
  kvDtype: NativeDType
  window?: number | undefined
  batch: number
  packedCausalChains?: NativePackedCausalChainsLayout | undefined
  lastTokenRow?: boolean | undefined
  outputSelections?: Array<NativeDecodeOutputSelection> | undefined
  currentBlockAttention?: NativeCurrentBlockAttention | undefined
}

export interface NativeMemoryDiagnostics {
  externalBytes: number
  persistentBytes: number
  stateBytes: number
  outputBytes: number
  workspaceBytes: number
  transactionBytes: number
  peakLiveBytes: number
  packingOverheadBytes: number
}

export interface NativePackedCausalChainsLayout {
  rowsPerSequence: number
}

export interface NativeProposerCommitPlan {
  kind: string
  stage?: number | undefined
  stages?: Array<number> | undefined
}

export interface NativeProposerOutputPlan {
  topology: string
  probabilities: string
  tokenIds: NativeValueRef
  probabilityRows?: NativeValueRef | undefined
  parents?: NativeValueRef | undefined
  confidence?: NativeValueRef | undefined
}

export interface NativeProposerPlan {
  targetPrefillTaps: Array<NativeTargetHiddenTap>
  targetDecodeTaps: Array<NativeTargetHiddenTap>
  targetVerifyTaps: Array<NativeTargetHiddenTap>
  sharedTargetBindings: Array<NativeSharedTargetBinding>
  stages: Array<NativeProposerStage>
  state: NativeProposerStatePlan
  commit?: NativeProposerCommitPlan | undefined
  output: NativeProposerOutputPlan
  tokenMap: NativeTokenMapPlan
  trainedMaxRows: number
}

export interface NativeProposerStage {
  executable?: number | undefined
  operationId: string
  layoutId?: string | undefined
  historyLookup?: NativeHistoryLookupLayout | undefined
  inputs: Array<NativeStageInputBinding>
  outputs: Array<NativeProposerValueSchema>
}

export interface NativeProposerStatePlan {
  kind: string
  schemaId?: string | undefined
}

export interface NativeProposerValueSchema {
  shape: Array<number>
  dtype: NativeDType
}

export interface NativeRecurrentStateSchema {
  kdaLayers: number
  kdaHeads: number
  kdaHeadDim: number
  kdaValueDim: number
  convLayers: number
  convChannels: number
  convKernel: number
}

export interface NativeSafetensorsArchive {
  entries: Array<NativeSafetensorsEntry>
  metadata: Record<string, string>
}

export interface NativeSafetensorsEntry {
  name: string
  tensor: NativeTensor
}

export interface NativeSamplingOptions {
  temperature: number
  topK: number
  topP: number
  seed: number
  counter: number
}

export interface NativeSharedTargetBinding {
  kind: string
  name: string
  tensor: number
  shape: Array<number>
  dtype: NativeDType
}

export interface NativeStageInputBinding {
  slot: number
  value: NativeValueRef
}

export interface NativeTargetHiddenTap {
  name: string
  output: number
  shape: Array<number>
  dtype: NativeDType
}

export interface NativeTokenMapPlan {
  kind: string
  fingerprint: string
  proposerVocabulary?: number | undefined
  targetIds?: Array<number> | undefined
}

export interface NativeValueRef {
  kind: string
  name?: string | undefined
  binding?: number | undefined
  stage?: number | undefined
  output?: number | undefined
  row?: number | undefined
  selectRow?: boolean | undefined
}

export declare function saveTensors(path: string, names: Array<string>, tensors: Array<NativeTensor>, metadata: Record<string, string>, token?: CancellationToken | undefined | null): Promise<void>

export type NativeAddon = typeof import("./native-addon.js")
