import type { Channel } from 'storybook/internal/channels';
import {
  AI_SETUP_ANALYTICS_REQUEST,
  AI_SETUP_ANALYTICS_RESPONSE,
} from 'storybook/internal/core-events';
import {
  getLastEvents,
  getStorybookMetadata,
  isStoryCreatedByAISetup,
  telemetry,
} from 'storybook/internal/telemetry';
import type { Options } from 'storybook/internal/types';
import { logger } from 'storybook/internal/node-logger';

import { runStoryTests } from '../utils/ghost-stories/run-story-tests.ts';
import type { StoryIndexGenerator } from 'storybook/internal/core-server';
import { waitForIdleVitest } from '../utils/wait-for-idle-vitest.ts';
import { getAiSetupRunId } from '../../shared/utils/ai-checklist-flags.ts';

export function initAIAnalyticsChannel(
  channel: Channel,
  options: Options,
  getStoryIndexGeneratorPromise?: () => Promise<StoryIndexGenerator> | undefined
) {
  /** Send analytics about the ai setup workflow when requested*/
  channel.on(AI_SETUP_ANALYTICS_REQUEST, async () => {
    const stats: {
      fileCount?: number;
      storyCount?: number;
      testRunDuration?: number;
    } = {};

    let runId: string | undefined;

    try {
      const lastEvents = await getLastEvents();
      const lastAISetup = lastEvents?.['ai-setup'];
      const lastSetupStoryScoringRun = lastEvents?.['ai-setup-final-scoring'];
      runId = await getAiSetupRunId(options.configDir);

      // Only run if sb ai setup has been called
      if (!lastAISetup) {
        return;
      }

      // Already ran once for this project and `ai setup` session — never run again
      if (
        lastSetupStoryScoringRun &&
        lastSetupStoryScoringRun.body.payload.runId === lastAISetup.body.payload.runId
      ) {
        return;
      }

      const metadata = await getStorybookMetadata(options.configDir);
      const isReactStorybook = metadata?.renderer?.includes('@storybook/react');
      const hasVitestAddon =
        !!metadata?.addons &&
        Object.keys(metadata.addons).some((addonKey) =>
          addonKey.includes('@storybook/addon-vitest')
        );

      // For now this is gated by React + Vitest
      if (!isReactStorybook || !hasVitestAddon) {
        return;
      }

      // Wait for any running tests to finish before launching scoring, so we don't
      // disturb end user activities.
      const isIdle = await waitForIdleVitest();
      if (!isIdle) {
        logger.debug('AI_SETUP_ANALYTICS_REQUEST timed out waiting for vitest to be available.');
        return;
      }

      // Fetch AI-generated stories and score them with the ghost stories metrics, if any are found.
      const generatorPromise = getStoryIndexGeneratorPromise?.();
      if (!generatorPromise) {
        logger.debug(
          'AI_SETUP_ANALYTICS_REQUEST could not proceed as the index generator is not ready.'
        );
        return;
      }

      const generator = await generatorPromise;
      const indexAndStats = await generator.getIndexAndStats();
      if (!indexAndStats) {
        logger.debug('AI_SETUP_ANALYTICS_REQUEST could not proceed as the index is not ready.');
        return;
      }

      const aiStoryFiles = new Set<string>();
      let aiStoryCount = 0;
      for (const entry of Object.values(indexAndStats.storyIndex.entries)) {
        if (isStoryCreatedByAISetup(entry)) {
          aiStoryFiles.add(entry.importPath);
          aiStoryCount++;
        }
      }

      if (aiStoryFiles.size > 0) {
        const aiTestRunResult = await runStoryTests([...aiStoryFiles]);
        telemetry('ai-setup-final-scoring', {
          stats: {
            fileCount: aiStoryFiles.size,
            storyCount: aiStoryCount,
            testRunDuration: aiTestRunResult.duration,
          },
          runId,
          results: aiTestRunResult.summary,
          ...(aiTestRunResult.runError ? { runError: aiTestRunResult.runError } : {}),
        });
      } else {
        telemetry('ai-setup-final-scoring', {
          stats: {
            fileCount: 0,
            storyCount: 0,
            testRunDuration: 0,
          },
          runId,
          runError: 'No stories found that were generated by ai setup',
        });
      }
    } catch {
      telemetry('ai-setup-final-scoring', {
        stats,
        runId,
        runError: 'Unknown error during AI story scoring',
      });
    } finally {
      // we don't currently do anything with this, but will be useful in the future
      channel.emit(AI_SETUP_ANALYTICS_RESPONSE);
    }
  });

  return channel;
}
