// CI gate for the flag schema, in two phases.
//
// 1. Re-run gen-flags.mts and fail if any generated file changed on disk
//    relative to the committed copy. Mirrors the pattern used by the gen_shims
//    tool — committed output is the spec, drift means someone edited a
//    generated file by hand without updating schema.ts.
// 2. Run check-flag-kinds.mts, which fails when a declared `kind` contradicts
//    the arity the compiler ttsc forwards to implements. Phase 1 only proves
//    the layers agree with the schema; phase 2 proves the schema agrees with
//    the tool, which is the half that let `--pretty` ship declared as a
//    value-taking flag and swallow the input file after it.

"use strict";

const child = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");

const {
  STRIP_TYPES_NODE_ARGS,
} = require("../../../scripts/node-strip-types.cjs");

const here = __dirname;
const ttscRoot = path.resolve(here, "..");
const repoRoot = path.resolve(ttscRoot, "../..");

const targets = [
  path.join(ttscRoot, "cmd/ttsc/flags_gen.go"),
  path.join(ttscRoot, "utility/flags_gen.go"),
  path.join(repoRoot, "packages/lint/linthost/flags_gen.go"),
  path.join(repoRoot, "website/src/content/docs/ttsc/flags.mdx"),
];

function main() {
  const before = snapshot(targets);

  const result = child.spawnSync(
    process.execPath,
    [...STRIP_TYPES_NODE_ARGS, path.join(here, "gen-flags.mts")],
    { stdio: "inherit" },
  );
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }

  // gofmt the generated Go files so alignment matches the committed copy. The
  // generator emits raw key:value entries and gofmt aligns the `:` column;
  // skipping this step here would surface as drift on any local edit.
  for (const target of targets) {
    if (!target.endsWith(".go")) continue;
    const script = path.join(repoRoot, ".vscode/gofmt-2spaces.sh");
    const gofmt = child.spawnSync(
      ...shellScriptCommand(script, ["-w", target]),
      {
        stdio: "inherit",
      },
    );
    if (gofmt.error) {
      throw gofmt.error;
    }
    if (gofmt.status !== 0) {
      process.exit(gofmt.status ?? 1);
    }
  }

  const after = snapshot(targets);
  const drift = computeDrift(before, after, targets);
  if (drift.length !== 0) {
    process.stderr.write(
      "ttsc flag schema: generated output drifted from src/flags/schema.ts:\n",
    );
    for (const file of drift) {
      process.stderr.write(`  ${path.relative(repoRoot, file)}\n`);
    }
    process.stderr.write(
      "run `pnpm format` to regenerate and commit the result.\n",
    );
    process.exit(1);
  }

  process.stdout.write("ttsc flag schema: generated output matches schema.\n");

  const kinds = child.spawnSync(
    process.execPath,
    [...STRIP_TYPES_NODE_ARGS, path.join(here, "check-flag-kinds.mts")],
    { stdio: "inherit" },
  );
  if (kinds.error) {
    throw kinds.error;
  }
  if (kinds.status !== 0) {
    process.exit(kinds.status ?? 1);
  }
}

function snapshot(files) {
  const out = {};
  for (const file of files) {
    out[file] = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
  }
  return out;
}

// Compare the content Git treats as committed, not the raw bytes on disk. A
// clean Windows checkout with core.autocrlf=true materializes the committed LF
// generated files as CRLF, while the Node generator and gofmt always emit LF;
// those two representations are the same committed content. Normalizing CRLF
// (and lone CR) to LF before comparing makes the gate independent of Git's
// configured checkout conversion while preserving sensitivity to every real
// generated byte or content change — only line terminators are folded, never
// other whitespace.
function normalizeEol(text) {
  return text.replace(/\r\n?/g, "\n");
}

// Decide which targets genuinely drifted between the committed snapshot and the
// freshly regenerated one. Line terminators are folded first (see normalizeEol)
// so a checkout's CRLF materialization is not mistaken for content drift, but
// every other byte still counts. A target absent from `before` (never committed)
// normalizes to "" and so drifts against any regenerated content.
function computeDrift(before, after, files) {
  const keys = files ?? Object.keys(after);
  const drift = [];
  for (const key of keys) {
    if (normalizeEol(before[key] ?? "") !== normalizeEol(after[key] ?? "")) {
      drift.push(key);
    }
  }
  return drift;
}

function shellScriptCommand(script, args) {
  if (process.platform === "win32") {
    return ["bash", [script, ...args]];
  }
  return [script, args];
}

if (require.main === module) {
  main();
}

module.exports = { computeDrift, normalizeEol, snapshot, targets };
