#!/usr/bin/env -S deno run --allow-read=.,../effect-cell-types,../../node_modules --allow-write=test-types

// The type-level observer of a Cell description.
//
// It holds a description value and its type and nothing else: the phase names, their
// kinds, their conventions, their chain order, the module name the description package
// carries and the I/O-cell classification are all read off `Cell.vocabulary` here, at
// generation time, and every assertion in the emitted suite is a function of that walk.
// Adding a phase changes the emitted suite; no phase is named in this file.
//
// The suite it writes is an oracle the runtime consumers do not share: tstyche decides
// assignability, so a claim here fails on a signature the property generator and the lint
// rule cannot observe at all.
//
// Deno APIs rather than `node:fs/promises`: with a Deno shebang the repo's edit hook routes
// this file to `deno check`, whose type-reference resolution looks in this config root's
// `node_modules` and so cannot find `@types/node` under pnpm's layout. Reading and writing
// through `Deno` keeps the file checkable by the toolchain that owns it.

import { Cell } from '@systemfsoftware/effect-cell-types'

const OUT = new URL('../test-types/Vocabulary.tst.ts', import.meta.url)

/** A phase name is the prefix its node, phase and stage types are spelled with. */
const typePrefix = (name: string): string => `${name.slice(0, 1).toUpperCase()}${name.slice(1)}`

const quoted = (values: ReadonlyArray<string>): string => values.map((value) => `'${value}'`).join(' | ')

const { byKind, ioCells, module, phases } = Cell.vocabulary

if (phases.length === 0) {
  throw new Error(
    'effect-cell-type-tests: the walked vocabulary carries no phases, so the generated suite would assert nothing',
  )
}

const names: ReadonlyArray<string> = phases.map((phase) => phase.name)
const opener = names[0]
if (opener === undefined) throw new Error('effect-cell-type-tests: the walked vocabulary has no opening phase')

const declarations = phases
  .flatMap((phase) => [
    `declare const ${phase.name}Phase: Cell.${typePrefix(phase.name)}Phase<Cell.Phases>`,
    `declare const ${phase.name}Stage: Cell.${typePrefix(phase.name)}Done<Cell.Phases>`,
  ])
  .join('\n')

const factBlock = (axis: string, member: string, expected: (phase: Cell.PhaseFact) => string): string =>
  phases
    .map((phase) =>
      `  it('Should_Carry${axis}_When_ReadingThe${typePrefix(phase.name)}NodeType', () => {\n` +
      `    expect<Cell.${typePrefix(phase.name)}Node<Cell.Phases>['${member}']>().type.toBe<'${expected(phase)}'>()\n` +
      `  })`
    )
    .join('\n')

// Axis 3. Each phase after the opener must accept its predecessor's stage, so the walked
// order becomes N-1 accepted call shapes.
//
// Only the positive is emitted. A rejection matrix was tried and removed: the walk carries
// the order phases run in, never the set of stages a constructor refuses, so asserting
// "every other stage is rejected" claimed more than the walked value licenses — and it is
// false as soon as one phase legitimately accepts two predecessors. The positives still
// pin the order: reverse the walk and each one names a pairing the constructors reject.
const orderBlock = names
  .map((name, index) => {
    const predecessor = names[index - 1]
    if (predecessor === undefined) {
      return `  it('Should_OpenTheChain_When_${typePrefix(name)}IsCalledWithItsPhaseAlone', () => {\n` +
        `    expect(Cell.${name}).type.toBeCallableWith(${name}Phase)\n` +
        `  })`
    }
    return `  it('Should_Extend${typePrefix(predecessor)}_When_${typePrefix(name)}IsCalled', () => {\n` +
      `    expect(Cell.${name}).type.toBeCallableWith(${predecessor}Stage, ${name}Phase)\n` +
      `  })`
  })
  .join('\n\n')

const stage = `Cell.${typePrefix(opener)}Done<Cell.Phases>`

const body = `// GENERATED by scripts/generate-type-tests.ts — do not edit.
//
// Every claim is a function of \`Cell.vocabulary\`, walked at generation time: ${phases.length} phases,
// ${byKind.pure.length} of them pure. Regenerate with
// \`pnpm --filter @systemfsoftware/effect-cell-type-tests generate\`.

import { Cell } from '@systemfsoftware/effect-cell-types'
import { describe, expect, it } from 'tstyche'

${declarations}

describe('axis 1 — phase names', () => {
${factBlock('Name', 'name', (phase) => phase.name)}
})

describe('axis 2 — phase kinds', () => {
${factBlock('Kind', 'kind', (phase) => phase.kind)}
})

describe('axis 2 — invocation conventions', () => {
${factBlock('Convention', 'convention', (phase) => phase.convention)}
})

describe('axis 3 — intra-layer phase order', () => {
${orderBlock}
})

describe('axis 4 — the module name the description package carries', () => {
  it('Should_CarryTheDescriptionModule_When_ReadingAStageType', () => {
    expect<${stage}['module']>().type.toBe<'${module}'>()
  })
})

describe('axis 5 — the I/O-cell classification', () => {
  it('Should_CarryTheIoCells_When_ReadingAStageType', () => {
    expect<${stage}['ioCells']['cells'][number]>().type.toBe<${quoted(ioCells.cells)}>()
  })

  it('Should_CarryTheIoSources_When_ReadingAStageType', () => {
    expect<${stage}['ioCells']['sources'][number]>().type.toBe<${quoted(ioCells.sources)}>()
  })
})
`

const walk =
  `a walk of ${phases.length} phases, ${ioCells.cells.length} I/O cells, ${ioCells.sources.length} I/O sources`

// The suite is rebuilt on every `test:types` run and never committed. That is not a storage
// preference: F2 counts any content change outside the description module as a hand edit,
// whatever the mechanism, so a tracked artifact that must be regenerated when a phase is added
// would fail propagation by construction. Untracked, adding a phase changes one file — the
// one where the authoring belongs — and this suite simply comes out different.
await Deno.mkdir(new URL('../test-types/', import.meta.url), { recursive: true })
await Deno.writeTextFile(OUT, body)
console.log(`effect-cell-type-tests: wrote ${OUT.pathname} from ${walk}`)
