import fs from "node:fs";
import path from "node:path";

import {
  FIRST_BUILD_TIMEOUT,
  type IRunResult,
  type ITtscEvidenceProject,
  type IWatchSession,
  assertExcludes,
  assertIncludes,
  assertStatus,
  createProject,
  startWatch,
} from "../internal/index";

/**
 * Verifies an edit to a declared local Swagger document refreshes the graph
 * under `ttsc check --watch`.
 *
 * A Swagger reference is published as one exact path rather than a population,
 * which is a different branch of the declaration and a different watcher in the
 * host — so the Markdown cases prove nothing about it. It is also the artifact
 * most likely to change with no TypeScript edit at all, because the document is
 * usually generated by the service it describes rather than written by the
 * author of this graph.
 *
 * 1. Watch a project whose citation covers the one declared operation.
 * 2. Add a second operation to the document and nothing else.
 * 3. Assert the next rebuild demands an acknowledgement for it.
 * 4. Remove it again and assert the graph closes from that event alone.
 */
export const test_evidence_watch_refreshes_declared_swagger =
  async (): Promise<void> => {
    const project: ITtscEvidenceProject = createProject({
      name: "watch-swagger",
      lintConfig: SWAGGER_LINT_CONFIG,
      files: {
        "api/swagger.json": swaggerWith(["post"]),
        "src/members.ts": MEMBER_CITATION,
      },
    });
    const session: IWatchSession = startWatch(project.directory);
    try {
      assertStatus(
        await session.nextBuild(FIRST_BUILD_TIMEOUT),
        0,
        "The first watch build must prove the operation graph is complete before freshness is tested.",
      );

      write(project, "api/swagger.json", swaggerWith(["post", "get"]));
      const widened: IRunResult = await session.nextBuild();
      assertStatus(
        widened,
        2,
        "A new operation in the declared document must fail the next build with no TypeScript file touched.",
      );
      assertIncludes(
        widened,
        "Missing acknowledgement for 'GET:/members'",
        "The rebuild must renormalize the edited document rather than reuse the previous cycle's operations.",
      );

      write(project, "api/swagger.json", swaggerWith(["post"]));
      const restored: IRunResult = await session.nextBuild();
      assertStatus(
        restored,
        0,
        "Removing the operation must close the graph from the Swagger event alone.",
      );
      assertExcludes(
        restored,
        "Missing acknowledgement",
        "A withdrawn operation must not survive as an obligation in the next cycle.",
      );
    } finally {
      await session.close();
      project.cleanup();
    }
  };

const SWAGGER_LINT_CONFIG: string = [
  'import evidence from "@ttsc/evidence";',
  "",
  "export default {",
  '  plugins: { "evidence": evidence },',
  "  rules: {",
  '    "evidence/graph": ["error", {',
  "      claims: [",
  "        {",
  '          type: "typescript",',
  '          files: ["src/**/*.ts"],',
  '          symbol: "type",',
  '          reference: { type: "swagger", file: "api/swagger.json" },',
  "        },",
  "      ],",
  "    }],",
  "  },",
  "};",
  "",
].join("\n");

const MEMBER_CITATION: string = [
  "/** @evidence POST:/members Creates members through the declared API operation. */",
  "export interface IMemberCreation {}",
  "",
].join("\n");

/** Builds an OpenAPI document declaring one path with the given methods. */
const swaggerWith = (methods: readonly string[]): string =>
  `${JSON.stringify(
    {
      openapi: "3.1.0",
      info: { title: "Members", version: "1.0.0" },
      paths: {
        "/members": Object.fromEntries(
          methods.map((method: string) => [
            method,
            { responses: { "200": { description: "OK" } } },
          ]),
        ),
      },
    },
    null,
    2,
  )}\n`;

const write = (
  project: ITtscEvidenceProject,
  relative: string,
  content: string,
): void => {
  const location: string = path.join(project.directory, relative);
  fs.mkdirSync(path.dirname(location), { recursive: true });
  fs.writeFileSync(location, content, "utf8");
};
