# see https://github.com/nrwl/nx/blob/master/.nx/workflows/dynamic-changesets.yaml for inspiration
distribute-on:
  small-changeset: 5 linux-browsers-js, 1 linux-js # Distribute on small if 1-25% of projects affected in PR
  medium-changeset: 10 linux-browsers-js, 1 linux-js # Distribute on medium if 26-50% of projects affected in PR
  large-changeset: 20 linux-browsers-js, 1 linux-js # Distribute on large if 51-75% of projects affected in PR
  extra-large-changeset: 30 linux-browsers-js, 1 linux-js # Distribute on extra-large if 76-100% of projects affected in PR
assignment-rules:
  - targets:
      - compile
    projects:
      - core
    run-on:
      - agent: linux-js
        parallelism: 1
  - targets:
      - compile
    run-on:
      - agent: linux-js
        parallelism: 1
      - agent: linux-browsers-js
        parallelism: 1
  - targets:
      - check
      - lint
      - knip
    run-on:
      - agent: linux-js
        parallelism: 6
  - targets:
      - '*'
    run-on:
      - agent: linux-browsers-js
        parallelism: 1
