//! Compact dense identifiers for compiler/runtime tables.
//!
//! Compiled programs exchange flat tables (bindings, values, instructions,
//! segments, and others) between the compiler and backends. Each table uses
//! its own `u32` newtype from [`dense_ids!`] instead of `usize`. Mixing ids
//! from different tables is therefore a type error.
//!
//! Id *i* indexes element *i* of its table. Tables can hold at most
//! `u32::MAX` entries. Constructors that take a `usize`
//! ([`DenseId::from_index`], [`TableRange::from_indexes`]) return `None`
//! instead of truncating when the value does not fit.
//!
//! [`TableRange<I>`] describes a typed, contiguous half-open table range.
//! Its accessors return `None` on bounds or arithmetic errors. Malformed
//! plans can then produce validation errors instead of panics.

use std::fmt;
use std::marker::PhantomData;
use std::ops::Range;

/// Common behavior of the dense `u32` table ids generated by `dense_ids!`.
pub trait DenseId: Copy + Eq {
    fn from_u32(value: u32) -> Self;
    fn as_u32(self) -> u32;

    /// Converts a table index into an id, or `None` if it exceeds `u32::MAX`.
    fn from_index(index: usize) -> Option<Self> {
        u32::try_from(index).ok().map(Self::from_u32)
    }

    /// The table index this id refers to.
    fn index(self) -> usize {
        self.as_u32() as usize
    }
}

macro_rules! dense_ids {
    ($($name:ident),+ $(,)?) => {
        $(
            #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
            pub struct $name(u32);

            impl $name {
                pub const fn new(value: u32) -> Self {
                    Self(value)
                }

                pub const fn get(self) -> u32 {
                    self.0
                }

                pub const fn index(self) -> usize {
                    self.0 as usize
                }

                pub fn from_index(index: usize) -> Option<Self> {
                    u32::try_from(index).ok().map(Self)
                }
            }

            impl DenseId for $name {
                fn from_u32(value: u32) -> Self {
                    Self(value)
                }

                fn as_u32(self) -> u32 {
                    self.0
                }
            }

            impl fmt::Display for $name {
                fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                    self.0.fmt(f)
                }
            }
        )+
    };
}

// Each flat table in a compiled program has its own id type. `BindingId`,
// `ScalarId`, and `RuntimeValueId` index signature declarations. `ValueId`
// indexes intermediate values. `InstructionId`, `PipelineId`, and `CommandId`
// index the executable. `SegmentId` and `LocationId` index the memory plan.
// `OutputId` indexes output slots.
dense_ids!(
    BindingId,
    ScalarId,
    RuntimeValueId,
    ValueId,
    InstructionId,
    PipelineId,
    CommandId,
    SegmentId,
    LocationId,
    OutputId,
);

/// A checked half-open range `start..start + len` into a table indexed by `I`.
///
/// The `usize` constructor and the `end`, `as_range`, and `get` accessors
/// return `None` on arithmetic overflow. Only
/// [`new`](Self::new), which takes an existing id and length, is unchecked.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct TableRange<I> {
    start: u32,
    len: u32,
    marker: PhantomData<fn() -> I>,
}

impl<I: DenseId> TableRange<I> {
    /// Creates a range starting at `start` spanning `len` entries.
    ///
    /// Does not check that `start + len` fits in `u32`. Use
    /// [`from_indexes`](Self::from_indexes) to check during construction.
    pub fn new(start: I, len: u32) -> Self {
        Self {
            start: start.as_u32(),
            len,
            marker: PhantomData,
        }
    }

    /// Creates a range from raw indexes, or returns `None` if either operand
    /// or `start + len` overflows `u32`.
    pub fn from_indexes(start: usize, len: usize) -> Option<Self> {
        let start = u32::try_from(start).ok()?;
        let len = u32::try_from(len).ok()?;
        start.checked_add(len)?;
        Some(Self {
            start,
            len,
            marker: PhantomData,
        })
    }

    /// Id of the first entry in the range.
    pub fn start(self) -> I {
        I::from_u32(self.start)
    }

    pub const fn len(self) -> usize {
        self.len as usize
    }

    pub const fn is_empty(self) -> bool {
        self.len == 0
    }

    /// Id one past the last entry, or `None` if it would overflow `u32`.
    pub fn end(self) -> Option<I> {
        self.start.checked_add(self.len).map(I::from_u32)
    }

    /// The range as `usize` indexes, or `None` on overflow.
    pub fn as_range(self) -> Option<Range<usize>> {
        Some(self.start as usize..self.end()?.index())
    }

    /// Bounds-checked sub-slice of `table`, or `None` if the range is out
    /// of bounds or overflows.
    pub fn get<'a, T>(self, table: &'a [T]) -> Option<&'a [T]> {
        table.get(self.as_range()?)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_ranges_are_checked() {
        let range = TableRange::new(CommandId::new(1), 2);
        assert_eq!(range.as_range(), Some(1..3));
        assert_eq!(range.get(&[0, 1, 2, 3]), Some(&[1, 2][..]));
        assert_eq!(TableRange::<CommandId>::from_indexes(0, usize::MAX), None);

        let overflow = TableRange::new(CommandId::new(u32::MAX), 1);
        assert_eq!(overflow.end(), None);
        assert_eq!(overflow.get(&[0]), None);
    }
}
