export { disableTypeChecks } from './Instrument.js'
export type { File, InstrumenterOptions, InstrumentResult } from './Instrument.js'
export { instrument } from './Instrument.js'
export { coreFormatOf, createParser, ParseFailed, ParserNotFound } from './Parser.js'
export type { CoreFormat, InstrumentParser, ParseFile, ParserContribution } from './Parser.js'
export { isAst } from './Syntax.js'
export type { Ast, AstByFormat, AstFormat, ScriptAst, ScriptFormat } from './Syntax.js'
export { angularIgnorer } from './Transformer.js'
export type { InstrumentIgnorer } from './Transformer.js'
