// Embedded compatibility dataset for `unicorn/no-unnecessary-polyfills`.
//
// `polyfill_data_gen.json` is generated by
// `packages/lint/tools/polyfilldata/generate.mjs` from pinned upstream
// packages (core-js-compat, caniuse-lite, node-releases,
// electron-to-chromium, browserslist) and must never be edited by hand; the
// provenance block inside the file names the exact versions. This file only
// decodes the artifact into the shapes the browserslist and core-js-compat
// ports consume.
package linthost

import (
  _ "embed"
  "encoding/json"
  "fmt"
  "sync"
)

//go:embed polyfill_data_gen.json
var polyfillDataJSON []byte

// polyfillBrowserslistConstants carries the version-pinned constants baked
// into browserslist's query engine.
type polyfillBrowserslistConstants struct {
  AndroidEvergreenFirst string            `json:"androidEvergreenFirst"`
  OpMobBlinkFirst       int               `json:"opMobBlinkFirst"`
  Dead                  []string          `json:"dead"`
  Defaults              []string          `json:"defaults"`
  Aliases               map[string]string `json:"aliases"`
  DesktopNames          map[string]string `json:"desktopNames"`
  FirefoxEsr            string            `json:"firefoxEsr"`
}

// polyfillCoreJsTables carries the engine alias and valid-target tables of
// core-js-compat's targets parser.
type polyfillCoreJsTables struct {
  Aliases      map[string]string `json:"aliases"`
  ValidTargets []string          `json:"validTargets"`
}

// polyfillUsageEntry is one "version → global usage percentage" pair in the
// JS object-key order browserslist iterates.
type polyfillUsageEntry struct {
  Version string  `json:"v"`
  Usage   float64 `json:"u"`
}

// polyfillReleaseDateEntry is one "version → release epoch seconds" pair in
// the JS object-key order browserslist iterates.
type polyfillReleaseDateEntry struct {
  Version string  `json:"v"`
  Date    float64 `json:"d"`
}

// polyfillAgent is one caniuse-lite browser record normalized the way
// browserslist normalizes it at load time.
type polyfillAgent struct {
  Name        string                     `json:"name"`
  Versions    []string                   `json:"versions"`
  Released    []string                   `json:"released"`
  Usage       []polyfillUsageEntry       `json:"usage"`
  ReleaseDate []polyfillReleaseDateEntry `json:"releaseDate"`
}

// polyfillNodeScheduleEntry is one node-releases EOL schedule row; only the
// bounds participate in `maintained node versions`.
type polyfillNodeScheduleEntry struct {
  Start string `json:"start"`
  End   string `json:"end"`
}

// polyfillData is the decoded artifact.
type polyfillData struct {
  Browserslist       polyfillBrowserslistConstants        `json:"browserslist"`
  CoreJs             polyfillCoreJsTables                 `json:"coreJs"`
  Modules            []string                             `json:"modules"`
  Compat             map[string]map[string]string         `json:"compat"`
  Entries            map[string][]string                  `json:"entries"`
  EsModulesTargets   map[string]string                    `json:"esModulesTargets"`
  Agents             []polyfillAgent                      `json:"agents"`
  NodeVersions       []string                             `json:"nodeVersions"`
  NodeSchedule       map[string]polyfillNodeScheduleEntry `json:"nodeSchedule"`
  ElectronToChromium [][2]string                          `json:"electronToChromium"`
}

var (
  polyfillDataOnce  sync.Once
  polyfillDataValue *polyfillData
  polyfillDataError error
)

// loadPolyfillData decodes the embedded artifact once. A decode failure is a
// packaging bug (the artifact is checked in and covered by tests), so callers
// treat the error as fatal for the rule; the engine's panic barrier keeps a
// corrupted build from taking down the whole run.
func loadPolyfillData() *polyfillData {
  polyfillDataOnce.Do(func() {
    data := &polyfillData{}
    if err := json.Unmarshal(polyfillDataJSON, data); err != nil {
      polyfillDataError = fmt.Errorf("polyfill_data_gen.json is corrupted: %w", err)
      return
    }
    if len(data.Modules) == 0 || len(data.Agents) == 0 || len(data.NodeVersions) == 0 {
      polyfillDataError = fmt.Errorf("polyfill_data_gen.json is missing required sections")
      return
    }
    polyfillDataValue = data
  })
  if polyfillDataError != nil {
    panic(polyfillDataError)
  }
  return polyfillDataValue
}
