/**
 * Generated by tsnapi — public API snapshot of `tsdown`
 */
// #region Interfaces
export interface AttwOptions extends CheckPackageOptions {
  module?: typeof import("@arethetypeswrong/core");
  profile?: "strict" | "node16" | "esm-only";
  level?: "error" | "warn";
  ignoreRules?: ("no-resolution" | "untyped-resolution" | "false-cjs" | "false-esm" | "cjs-resolves-to-esm" | "fallback-condition" | "cjs-only-exports-default" | "named-exports" | "false-export-default" | "missing-export-equals" | "unexpected-module-syntax" | "internal-resolution-error" | (string & {}))[];
}
export interface BuildContext {
  options: ResolvedConfig;
  hooks: Hookable<TsdownHooks>;
}
export interface ChunkAddonObject {
  js?: string;
  css?: string;
  dts?: string;
}
export interface CopyEntry {
  from: string | string[];
  to?: string;
  flatten?: boolean;
  verbose?: boolean;
  rename?: string | ((_: string, _: string, _: string) => string);
}
export interface DepsConfig {
  neverBundle?: true | ExternalOption;
  alwaysBundle?: Arrayable<string | RegExp> | NoExternalFn;
  onlyBundle?: Arrayable<string | RegExp> | false;
  onlyImport?: Arrayable<string | RegExp>;
  onlyAllowBundle?: Arrayable<string | RegExp> | false;
  skipNodeModulesBundle?: boolean;
  resolveDepSubpath?: boolean;
  dts?: Pick<DepsConfig, "alwaysBundle" | "neverBundle">;
}
export interface DevtoolsOptions extends NonNullable<InputOptions["devtools"]> {
  ui?: boolean | Partial<StartOptions>;
  clean?: boolean;
}
export interface DtsOptions extends Options$1 {
  cjsReexport?: boolean;
}
export interface ExeOptions extends ExeExtensionOptions {
  seaConfig?: Omit<SeaConfig, "main" | "output" | "mainFormat">;
  fileName?: string | ((_: RolldownChunk) => string);
  outDir?: string;
}
export interface ExportsOptions {
  devExports?: boolean | string;
  packageJson?: boolean;
  all?: boolean;
  exclude?: (RegExp | string)[];
  legacy?: boolean;
  customExports?: Record<string, any> | ((_: Record<string, any>, _: {
    pkg: PackageJson;
    chunks: ChunksByFormat;
    isPublish: boolean;
  }) => Awaitable<Record<string, any>>);
  inlinedDependencies?: boolean;
  extensions?: boolean;
  bin?: boolean | string | Record<string, string>;
}
export interface InlineConfig extends UserConfig {
  config?: boolean | string;
  configLoader?: "auto" | "native" | "tsx" | "unrun";
  filter?: RegExp | Arrayable<string>;
  concurrency?: number;
}
export interface Logger {
  level: LogLevel;
  options?: LoggerOptions;
  info: (..._: any[]) => void;
  warn: (..._: any[]) => void;
  warnOnce: (..._: any[]) => void;
  error: (..._: any[]) => void;
  success: (..._: any[]) => void;
  clearScreen: (_: LogType) => void;
}
export interface OutExtensionContext {
  options: InputOptions;
  format: NormalizedFormat;
  pkgType?: PackageType;
}
export interface OutExtensionObject {
  js?: string;
  dts?: string;
}
export interface PackageJsonWithPath extends PackageJson {
  packageJsonPath: string;
}
export interface PublintOptions extends Omit<Options, "pack" | "pkgDir"> {
  module?: [typeof import("publint"), typeof import("publint/utils")];
}
export interface ReportOptions {
  gzip?: boolean;
  brotli?: boolean;
  maxCompressSize?: number;
}
export interface ResolvedDepsConfig extends Pick<DepsConfig, "neverBundle" | "skipNodeModulesBundle" | "resolveDepSubpath"> {
  alwaysBundle?: NoExternalFn;
  onlyBundle?: Array<string | RegExp> | false;
  onlyImport?: Array<string | RegExp>;
  dts: Pick<ResolvedDepsConfig, "alwaysBundle" | "neverBundle">;
}
export interface RolldownContext {
  buildOptions: BuildOptions;
}
export interface SeaConfig {
  main?: string;
  executable?: string;
  output?: string;
  mainFormat?: "commonjs" | "module";
  disableExperimentalSEAWarning?: boolean;
  useSnapshot?: boolean;
  useCodeCache?: boolean;
  execArgv?: string[];
  execArgvExtension?: "none" | "env" | "cli";
  assets?: Record<string, string>;
}
export interface TsdownBundle extends AsyncDisposable {
  chunks: RolldownChunk[];
  config: ResolvedConfig;
  inlinedDeps: Map<string, Set<string>>;
}
export interface TsdownHooks {
  "build:prepare": (_: BuildContext) => void | Promise<void>;
  "build:before": (_: BuildContext & RolldownContext) => void | Promise<void>;
  "build:done": (_: BuildContext & {
    chunks: RolldownChunk[];
  }) => void | Promise<void>;
}
export interface TsdownPlugin<A = any> extends Plugin<A> {
  tsdownConfig?: (_: UserConfig, _: InlineConfig) => Awaitable<UserConfig | void | null>;
  tsdownConfigResolved?: (_: ResolvedConfig) => Awaitable<void>;
}
export interface UserConfig {
  entry?: TsdownInputOption;
  deps?: DepsConfig;
  alias?: Record<string, string>;
  tsconfig?: string | boolean;
  platform?: "node" | "neutral" | "browser";
  target?: string | string[] | false;
  env?: Record<string, any>;
  envFile?: string;
  envPrefix?: string | string[];
  define?: Record<string, string>;
  shims?: boolean;
  treeshake?: boolean | TreeshakingOptions;
  loader?: ModuleTypes;
  nodeProtocol?: "strip" | boolean;
  checks?: ChecksOptions & {
    legacyCjs?: boolean;
  };
  plugins?: TsdownPluginOption;
  inputOptions?: InputOptions | ((_: InputOptions, _: NormalizedFormat, _: {
    cjsDts: boolean;
  }) => Awaitable<InputOptions | void | null>);
  format?: Format | Format[] | Partial<Record<Format, Partial<ResolvedConfig>>>;
  globalName?: string;
  outDir?: string;
  write?: boolean;
  sourcemap?: Sourcemap;
  clean?: boolean | string[];
  minify?: boolean | "dce-only" | MinifyOptions;
  footer?: ChunkAddon;
  banner?: ChunkAddon;
  unbundle?: boolean;
  root?: string;
  fixedExtension?: boolean;
  outExtensions?: OutExtensionFactory;
  hash?: boolean;
  cjsDefault?: boolean;
  outputOptions?: OutputOptions | ((_: OutputOptions, _: NormalizedFormat, _: {
    cjsDts: boolean;
  }) => Awaitable<OutputOptions | void | null>);
  cwd?: string;
  name?: string;
  logLevel?: LogLevel;
  failOnWarn?: boolean | CIOption;
  suppressWarnings?: Arrayable<RegExp | string> | ((_: string) => boolean);
  customLogger?: Logger;
  fromVite?: boolean | "vitest";
  watch?: boolean | Arrayable<string>;
  ignoreWatch?: Arrayable<string | RegExp>;
  devtools?: WithEnabled<DevtoolsOptions>;
  onSuccess?: string | ((_: ResolvedConfig, _: AbortSignal) => void | Promise<void>);
  dts?: WithEnabled<DtsOptions>;
  unused?: WithEnabled<UnusedOptions>;
  publint?: WithEnabled<PublintOptions>;
  attw?: WithEnabled<AttwOptions>;
  report?: WithEnabled<ReportOptions>;
  globImport?: boolean;
  exports?: WithEnabled<ExportsOptions>;
  css?: CssOptions;
  copy?: CopyOptions | CopyOptionsFn;
  hooks?: Partial<TsdownHooks> | ((_: Hookable<TsdownHooks>) => Awaitable<void>);
  exe?: WithEnabled<ExeOptions>;
  workspace?: Workspace | Arrayable<string> | true;
  external?: ExternalOption;
  noExternal?: Arrayable<string | RegExp> | NoExternalFn;
  inlineOnly?: Arrayable<string | RegExp> | false;
  skipNodeModulesBundle?: boolean;
  removeNodeProtocol?: boolean;
  bundle?: boolean;
  outExtension?: OutExtensionFactory;
  injectStyle?: boolean;
  publicDir?: CopyOptions | CopyOptionsFn;
}
export interface Workspace {
  include?: "auto" | (string & {}) | string[];
  exclude?: Arrayable<string>;
  config?: boolean | string;
}
// #endregion

// #region Types
export type ChunkAddon = ChunkAddonObject | ChunkAddonFunction | string;
export type ChunkAddonFunction = (_: {
  format: Format;
  fileName: string;
}) => ChunkAddonObject | string | undefined;
export type CIOption = "ci-only" | "local-only";
export type CopyOptions = Arrayable<string | CopyEntry>;
export type CopyOptionsFn = (_: ResolvedConfig) => Awaitable<CopyOptions>;
export type Format = ModuleFormat;
export type NoExternalFn = (_: string, _: string | undefined) => boolean | null | undefined | void;
export type NormalizedFormat = InternalModuleFormat;
export type OutExtensionFactory = (_: OutExtensionContext) => OutExtensionObject | undefined;
export type PackageType = "module" | "commonjs" | undefined;
export type ResolvedConfig = Overwrite<MarkPartial<Omit<UserConfig, "workspace" | "fromVite" | "publicDir" | "bundle" | "injectStyle" | "removeNodeProtocol" | "outExtension" | "external" | "noExternal" | "inlineOnly" | "skipNodeModulesBundle" | "logLevel" | "failOnWarn" | "suppressWarnings" | "customLogger" | "envFile" | "envPrefix">, "globalName" | "inputOptions" | "outputOptions" | "minify" | "define" | "alias" | "onSuccess" | "outExtensions" | "hooks" | "copy" | "loader" | "name" | "banner" | "footer" | "checks" | "css">, {
  entry: Record<string, string>;
  rawEntry?: TsdownInputOption;
  nameLabel: string | undefined;
  format: NormalizedFormat;
  target?: string[];
  clean: string[];
  pkg?: PackageJsonWithPath;
  nodeProtocol: "strip" | boolean;
  logger: Logger;
  ignoreWatch: Array<string | RegExp>;
  deps: ResolvedDepsConfig;
  root: string;
  configDeps: Set<string>;
  runBuild: ConcurrencyExecutor;
  dts: false | DtsOptions;
  report: false | ReportOptions;
  tsconfig: false | string;
  exports: false | ExportsOptions;
  devtools: false | DevtoolsOptions;
  publint: false | PublintOptions;
  attw: false | AttwOptions;
  unused: false | UnusedOptions;
  exe: false | ExeOptions;
}>;
export type RolldownChunk = (OutputChunk | OutputAsset) & {
  outDir: string;
};
export type Sourcemap = boolean | "inline" | "hidden";
export type TsdownInputOption = Arrayable<string | Record<string, Arrayable<string>>>;
export type TsdownPluginOption<A = any> = Awaitable<TsdownPlugin<A> | RolldownPlugin<A> | {
  name: string;
} | undefined | null | void | false | TsdownPluginOption<A>[]>;
export type UserConfigExport = Awaitable<Arrayable<UserConfig> | UserConfigFn>;
export type UserConfigFn = (_: InlineConfig, _: {
  ci: boolean;
  rootConfig?: UserConfig;
}) => Awaitable<Arrayable<UserConfig>>;
export type WithEnabled<T> = boolean | undefined | CIOption | (T & {
  enabled?: boolean | CIOption;
});
// #endregion

// #region Functions
export declare function build(_?: InlineConfig): Promise<TsdownBundle[]>;
export declare function buildWithConfigs(_: ResolvedConfig[], _: Set<string>, _: () => void): Promise<TsdownBundle[]>;
export declare function defineConfig(_: UserConfig): UserConfig;
export declare function defineConfig(_: UserConfig[]): UserConfig[];
export declare function defineConfig(_: UserConfigFn): UserConfigFn;
export declare function defineConfig(_: UserConfigExport): UserConfigExport;
export declare function enableDebug(_?: boolean | Arrayable<string>): void;
export declare function mergeConfig(_: UserConfig, ..._: UserConfig[]): UserConfig;
export declare function mergeConfig(_: InlineConfig, ..._: InlineConfig[]): InlineConfig;
export declare function resolveUserConfig(_: UserConfig, _: InlineConfig, _: Set<string>, _?: ConcurrencyExecutor): Promise<ResolvedConfig[]>;
// #endregion

// #region Variables
export declare const globalLogger: Logger;
export declare const version: string;
// #endregion

// #region Other
export { Rolldown }
export { TreeshakingOptions }
export { UnusedOptions }
// #endregion