// Generated from the Rust N-API exports by `pnpm generate:native-types`.
// Do not edit this file directly.

export declare class CancellationToken {
  constructor()
  cancel(): void
  get cancelled(): boolean
}

export declare class CudaRuntime {
  constructor(device?: number | undefined | null)
  get device(): string
  constant(value: number, dtype: string): LazyTensor
  zeros(dimensions: Array<number>, dtype: string): LazyTensor
  ones(dimensions: Array<number>, dtype: string): LazyTensor
  full(dimensions: Array<number>, value: number, dtype: string): LazyTensor
  fromBytes(data: Uint8Array, dimensions: Array<number>, dtype: string): LazyTensor
  uploadBytes(data: Uint8Array, dimensions: Array<number>, dtype: string): NativeTensor
  fromMaterialized(tensor: NativeTensor): LazyTensor
  graphNode(operation: string, inputs: Array<LazyTensor>, encodedAttributes: string): LazyTensor
  add(a: LazyTensor, b: LazyTensor): LazyTensor
  compile(roots: Array<LazyTensor>, options?: NativeCompileOptions | undefined | null, state?: NativeKvStateSchema | undefined | null): Executable
}

export declare class Executable {
  get diagnostics(): NativeExecutableDiagnostics
  get stateful(): boolean
  get batch(): number
  get allowsWindowEviction(): boolean
  get layers(): number
  get kvHeads(): number
  get headDim(): number
  get kdaLayers(): number
  get kdaHeads(): number
  get kdaHeadDim(): number
  get kdaValueDim(): number
  get convLayers(): number
  get convChannels(): number
  get convKernel(): number
  get device(): string
  get instructionCount(): number
  execute(bindings: Array<NativeTensor>, scalars: Array<number>, token?: CancellationToken | undefined | null): Promise<Array<NativeTensor>>
  executeStateful(bindings: Array<NativeTensor>, sequences: Array<NativeKvSequence>, slots: Array<number>, activeMask: Array<boolean>, validLengths: Array<number>, advances: Array<number>, tokens: Array<Array<number>>, token?: CancellationToken | undefined | null): Promise<Array<NativeTensor>>
  executeSampled(bindings: Array<NativeTensor>, sequences: Array<NativeKvSequence>, slots: Array<number>, activeMask: Array<boolean>, validLengths: Array<number>, advances: Array<number>, tokens: Array<Array<number>>, sampling: Array<NativeSamplingOptions>, token?: CancellationToken | undefined | null): Promise<Array<number>>
  executeSampledSteps(bindings: Array<NativeTensor>, sequences: Array<NativeKvSequence>, slots: Array<number>, activeMask: Array<boolean>, validLengths: Array<number>, advances: Array<number>, tokens: Array<Array<number>>, sampling: Array<Array<NativeSamplingOptions>>, token?: CancellationToken | undefined | null): Promise<Array<Array<number>>>
  executeTargetMatching(sequences: Array<NativeKvSequence>, slots: Array<number>, tokens: Array<Array<number>>, sampling: Array<Array<NativeSamplingOptions>>, pageLimits: Array<number>, eosTokens: Array<Array<number>>, proposalProbabilities?: NativeTensor | undefined | null, token?: CancellationToken | undefined | null): Promise<NativeTargetMatchingOutput>
}

export declare class LazyTensor {
  get shape(): Array<number>
  get dtype(): string
  get device(): string
  exposures(): Array<NativeExposure>
}

export declare class NativeExposure {
  get name(): string
  get tensor(): LazyTensor
}

export declare class NativeKvPool {
  constructor(device: number, layers: number, kvHeads: number, headDim: number, maxTokens: number, blockSize?: number | undefined | null, dtype?: string | undefined | null, recurrent?: NativeRecurrentStateSchema | undefined | null)
  get capacity(): number
  get freeBlocks(): number
  get cachedBlocks(): number
  makeSequence(): NativeKvSequence
}

export declare class NativeKvSequence {
  get cursor(): number
  fork(): NativeKvSequence
  release(): void
  prefillMatch(tokens: Array<number>): number
}

export declare class NativeTargetMatchingOutput {
  get pages(): Array<Array<number>>
  get accepted(): Array<number>
  get outputs(): Array<NativeTensor>
}

export declare class NativeTensor {
  clear(): void
  writeBytes(data: Uint8Array): void
  get shape(): Array<number>
  get dtype(): string
  get device(): string
  readback(token?: CancellationToken | undefined | null): Promise<Buffer>
  sample(temperature: number, topK: number, topP: number, seed: number, counter: number, token?: CancellationToken | undefined | null): Promise<number>
}

/** Number of CUDA devices visible to this process. */
export declare function deviceCount(): number

/** Reverse-mode gradients of `loss` with respect to each tensor in `wrt`. */
export declare function grad(loss: LazyTensor, wrt: Array<LazyTensor>): Array<LazyTensor>

export declare function inspectGguf(path: string, token?: CancellationToken | undefined | null): Promise<NativeGgufInspection>

/** Whether a usable CUDA device and `compute_120` NVRTC compiler are present. */
export declare function isAvailable(): boolean

export declare function loadGgufForDevice(path: string, deviceOrdinal: number, token?: CancellationToken | undefined | null): Promise<NativeGgufArchive>

export declare function loadTensors(path: string, device: number, token?: CancellationToken | undefined | null): Promise<NativeSafetensorsArchive>

export interface NativeCompileOptions {
  optimize?: boolean | undefined
  constantWeights?: boolean | undefined
}

export interface NativeCompilePhaseDiagnostics {
  phase: string
  nanoseconds: number
}

export declare const enum NativeCurrentBlockAttention {
  Causal = 'Causal',
  Bidirectional = 'Bidirectional'
}

export declare const enum NativeDecodeOutputSelection {
  AllRows = 'AllRows',
  SplitLastTokenRow = 'SplitLastTokenRow',
  BatchedLastTokenRow = 'BatchedLastTokenRow'
}

export interface NativeExecutableDiagnostics {
  semanticNodesBeforeOptimization: number
  semanticNodesAfterOptimization: number
  instructions: Array<NativeInstructionDiagnostics>
  pipelineCount: number
  commandCount: number
  synchronizationCount: number
  memory: NativeMemoryDiagnostics
  compilePhases: Array<NativeCompilePhaseDiagnostics>
}

export interface NativeGgufArchive {
  entries: Array<NativeGgufLoadedEntry>
}

export interface NativeGgufInspection {
  metadata: Array<NativeGgufMetadataEntry>
  tensors: Array<NativeGgufTensorDescriptor>
}

export interface NativeGgufLoadedEntry {
  descriptor: NativeGgufTensorDescriptor
  tensor: NativeTensor
}

export interface NativeGgufMetadataEntry {
  key: string
  kind: string
  numberValue?: number | undefined
  stringValue?: string | undefined
  booleanValue?: boolean | undefined
  numberArray?: Array<number> | undefined
  stringArray?: Array<string> | undefined
  booleanArray?: Array<boolean> | undefined
}

export interface NativeGgufTensorDescriptor {
  name: string
  format: string
  logicalShape: Array<number>
  logicalDtype: string
  physicalShape: Array<number>
  physicalDtype: string
}

export interface NativeInstructionDiagnostics {
  kind: string
  count: number
}

export interface NativeKvStateSchema {
  maxTokens: number
  blockSize: number
  kvDtype: string
  window?: number | undefined
  currentBlockAttention?: NativeCurrentBlockAttention | undefined
  batch: number
  packedCausalChains?: NativePackedCausalChainsLayout | undefined
  lastTokenRow?: boolean | undefined
  outputSelections?: Array<NativeDecodeOutputSelection> | undefined
}

export interface NativeMemoryDiagnostics {
  externalBytes: number
  persistentBytes: number
  stateBytes: number
  outputBytes: number
  workspaceBytes: number
  transactionBytes: number
  peakLiveBytes: number
  packingOverheadBytes: number
}

export interface NativePackedCausalChainsLayout {
  rowsPerSequence: number
}

export interface NativeRecurrentStateSchema {
  kdaLayers: number
  kdaHeads: number
  kdaHeadDim: number
  kdaValueDim: number
  convLayers: number
  convChannels: number
  convKernel: number
}

export interface NativeSafetensorsArchive {
  entries: Array<NativeSafetensorsEntry>
  metadata: Record<string, string>
}

export interface NativeSafetensorsEntry {
  name: string
  tensor: NativeTensor
}

export interface NativeSamplingOptions {
  temperature: number
  topK: number
  topP: number
  seed: number
  counter: number
}

export declare function saveTensors(path: string, names: Array<string>, tensors: Array<NativeTensor>, metadata: Record<string, string>, token?: CancellationToken | undefined | null): Promise<void>

export type NativeAddon = typeof import("./native-addon.js")
