// Code generated by packages/ttsc/scripts/gen-flags.mts. DO NOT EDIT.
//
// Source of truth: packages/ttsc/src/flags/schema.ts.
// Regenerate with:    pnpm format
// Verify in CI with:  node packages/ttsc/scripts/check-flags.cjs

package utility

// HostFlagAllowList is the allow-list of CLI flags this Go layer accepts. The map's
// value is true when the flag carries a separate value token (--flag VALUE
// or --flag=VALUE) and false when the flag is boolean (--flag).
//
// Generated from packages/ttsc/src/flags/schema.ts. Edit the schema, not
// this file.
var HostFlagAllowList = map[string]bool{
  "checkers":       true,
  "cwd":            true,
  "emit":           false,
  "manifest":       true,
  "noemit":         false,
  "outdir":         true,
  "p":              true,
  "plugins-json":   true,
  "project":        true,
  "quiet":          false,
  "singlethreaded": false,
  "tsconfig":       true,
  "tsgo-args":      true,
  "verbose":        false,
}
