import path from 'node:path'
import { RE_CSS, RE_DTS, RE_NODE_MODULES } from 'rolldown-plugin-dts/internal'
import { stripExtname } from '../../utils/fs.ts'
import { matchPattern, slash, typeAssert } from '../../utils/general.ts'
import { writeJsonFile } from '../../utils/json.ts'
import type { NormalizedFormat, ResolvedConfig } from '../../config/types.ts'
import type {
  ChunksByFormat,
  RolldownChunk,
  RolldownCodeChunk,
} from '../../utils/chunks.ts'
import type { Logger } from '../../utils/logger.ts'
import type { Awaitable } from '../../utils/types.ts'
import type { PackageJson } from 'pkg-types'

export interface ExportsOptions {
  /**
   * Generate exports that link to source code during development.
   * - `string`: add as a custom condition.
   * - `true`: all conditions point to source files, and add `dist` exports to `publishConfig`.
   */
  devExports?: boolean | string

  /**
   * Generate `exports` for `package.json` file.
   *
   * @example
   * ```json
   * {
   *   "exports": {
   *      ".": {
   *         "types": "./dist/index.d.mts",
   *         "import": "./dist/index.mjs"
   *      },
   *     "./package.json": "./package.json"
   *   }
   * }
   * ```
   *
   * @default true
   */
  packageJson?: boolean

  /**
   * Generate `exports` for all files.
   *
   * @example
   * ```json
   * {
   *   "exports": {
   *    "./*": "./*"
   *   }
   * }
   * ```
   *
   * @default false
   */
  all?: boolean

  /**
   * Specifies file patterns (as glob patterns or regular expressions) to exclude from package exports.
   * Use this to prevent certain files from being included in the exported package, such as test files, binaries, or internal utilities.
   *
   * **Note:** Do not include file extensions, and paths should be relative to the dist directory.
   *
   * @example
   * ```ts
   * exclude: ['cli', '**\/*.test', /internal/]
   * ```
   */
  exclude?: (RegExp | string)[]

  /**
   * Generate legacy fields (`main` and `module`) for older Node.js and bundlers
   * that do not support package `exports` field.
   *
   * Defaults to false, if only ESM builds are included, true otherwise.
   *
   * @see {@link https://github.com/publint/publint/issues/24}
   */
  legacy?: boolean

  /**
   * Specifies custom exports to add to the package exports in addition to the ones generated by tsdown.
   * Use this to add additional exports in the exported package, such as workers or assets.
   *
   * @example
   * ```ts
   * customExports(exports) {
   *   exports['./worker.js'] = './dist/worker.js';
   *   return exports;
   * }
   * ```
   *
   * @example
   * ```jsonc
   * {
   *   "customExports": {
   *     "./worker.js": {
   *       "types": "./dist/worker.d.ts",
   *       "default": "./dist/worker.js"
   *     }
   *   }
   * }
   * ```
   */
  customExports?:
    | Record<string, any>
    | ((
        exports: Record<string, any>,
        context: {
          pkg: PackageJson
          chunks: ChunksByFormat
          isPublish: boolean
        },
      ) => Awaitable<Record<string, any>>)

  /**
   * Generate `inlinedDependencies` field in `package.json`.
   * Lists dependencies that are physically inlined into the bundle with their exact versions.
   *
   * @default true
   * @see {@link https://github.com/e18e/ecosystem-issues/issues/237}
   */
  inlinedDependencies?: boolean

  /**
   * Add file extensions to subpath export keys.
   *
   * When enabled, all subpath exports (except the root `"."`) will include
   * a `.js` extension in the key (e.g., `"./utils.js"` instead of `"./utils"`).
   *
   * This follows the Node.js recommendation for subpath exports:
   * @see {@link https://nodejs.org/api/packages.html#extensions-in-subpaths}
   *
   * @default false
   */
  extensions?: boolean

  /**
   * Generate the `bin` field in `package.json` for CLI executables.
   *
   * Behavior depends on the value:
   *
   * - *Unset* (default): Soft auto-detect. Scans entry chunks for shebangs
   *   (e.g. `#!/usr/bin/env node`). If exactly one is found, it is used as
   *   the bin entry. If multiple are found, a warning is shown and no `bin`
   *   field is written. If none are found, nothing happens silently.
   * - `true`: Strict auto-detect. Same as the default, but throws if
   *   multiple shebang entries are found, and warns if none are found.
   *   Use this when your package is known to ship a CLI and you want to
   *   fail fast on misconfiguration.
   * - `false`: Disable bin generation entirely, even if shebangs are
   *   present.
   * - `string`: Use the given source file path (relative to `cwd`) as the
   *   CLI entry. The command name is derived from the package name without
   *   its scope. Warns if the source file does not contain a shebang.
   * - `Record<string, string>`: Explicitly map command names to source file
   *   paths (relative to `cwd`). Warns for each source file that does not
   *   contain a shebang.
   *
   * When {@link ExportsOptions.devExports} is enabled, the `bin` field in
   * `package.json` points to source files during local development, while
   * `publishConfig.bin` points to built output paths for publishing.
   *
   * @example
   * <caption>Auto-detect a CLI entry from a shebang</caption>
   *
   * ```ts
   * {
   *   bin: true
   * }
   * ```
   *
   * @example
   * <caption>Single CLI command with an explicit source entry</caption>
   *
   * ```ts
   * {
   *   bin: './src/cli.ts'
   * }
   * ```
   *
   * @example
   * <caption>Multiple named CLI commands</caption>
   *
   * ```ts
   * {
   *   bin: {
   *     tool: './src/cli.ts',
   *     serve: './src/cli-extra.ts',
   *   },
   * }
   * ```
   *
   * @see {@link https://docs.npmjs.com/cli/v11/configuring-npm/package-json#bin | npm documentation for the `bin` field}
   */
  bin?: boolean | string | Record<string, string>
}

export async function writeExports(
  options: ResolvedConfig,
  chunks: ChunksByFormat,
  inlinedDeps?: Record<string, string | string[]>,
): Promise<void> {
  typeAssert(options.pkg)

  const { pkg } = options
  const { publishExports, publishBin, bin, ...generated } =
    await generateExports(pkg, chunks, options, inlinedDeps)

  const updatedPkg = {
    ...pkg,
    ...generated,
    ...(bin === undefined ? {} : { bin }),
    packageJsonPath: undefined,
  }

  if (publishExports || publishBin) {
    updatedPkg.publishConfig ||= {}
    if (publishExports) {
      updatedPkg.publishConfig.exports = publishExports
    }
    if (publishBin) {
      updatedPkg.publishConfig.bin = publishBin
    }
  }

  writeJsonFile(pkg.packageJsonPath, updatedPkg)
}

type SubExport = Partial<Record<'cjs' | 'es' | 'src', string>>

function shouldExclude(
  fileName: string,
  exclude?: (RegExp | string)[],
): boolean {
  if (!exclude?.length) return false
  return matchPattern(fileName, exclude)
}

export async function generateExports(
  pkg: PackageJson,
  chunks: ChunksByFormat,
  options: Pick<ResolvedConfig, 'exports' | 'css' | 'logger' | 'cwd'>,
  inlinedDeps?: Record<string, string | string[]>,
): Promise<{
  main: string | undefined
  module: string | undefined
  types: string | undefined
  exports: Record<string, any>
  bin?: string | Record<string, string>
  publishBin?: string | Record<string, string>
  inlinedDependencies?: Record<string, string | string[]>
  publishExports?: Record<string, any>
}> {
  typeAssert(options.exports)
  let {
    exports: {
      devExports,
      all,
      packageJson = true,
      exclude,
      customExports,
      legacy,
      extensions,
      inlinedDependencies: emitInlinedDeps = true,
      bin,
    },
    css,
    logger,
    cwd,
  } = options

  const pkgRoot = path.dirname(pkg.packageJsonPath)

  let main: string | undefined,
    module: string | undefined,
    cjsTypes: string | undefined,
    esmTypes: string | undefined
  const exportsMap: Map<string, SubExport> = new Map()

  const formats = Object.keys(chunks)
  if (!formats.includes('cjs') && !formats.includes('es')) {
    logger.warn(`No CJS or ESM formats found in chunks for package ${pkg.name}`)
  }

  const isPureESM = formats.length === 1 && formats[0] === 'es'
  legacy ??= !isPureESM

  for (const [format, chunksByFormat] of Object.entries(chunks) as [
    NormalizedFormat,
    RolldownChunk[],
  ][]) {
    if (format !== 'es' && format !== 'cjs') continue

    // Filter out non-entry chunks and excluded files
    const filteredChunks = chunksByFormat.filter(
      (chunk): chunk is RolldownCodeChunk => {
        if (chunk.type !== 'chunk') {
          return false
        }

        if (!chunk.isEntry) {
          if (!all) return false

          if (
            chunk.facadeModuleId?.[0] === '\0' ||
            (chunk.facadeModuleId && RE_NODE_MODULES.test(chunk.facadeModuleId))
          ) {
            return false
          }
        }

        const [name] = getExportName(chunk)
        return !shouldExclude(name, exclude)
      },
    )

    const onlyOneEntry =
      filteredChunks.filter((chunk) => !RE_DTS.test(chunk.fileName)).length ===
      1

    for (const chunk of filteredChunks) {
      let [name, normalizedName, isDts] = getExportName(chunk)
      const isIndex = onlyOneEntry || name === 'index'
      const distFile = join(pkgRoot, chunk.outDir, normalizedName)

      if (isIndex) {
        name = '.'
        if (format === 'cjs') {
          if (isDts) {
            cjsTypes = distFile
          } else {
            main = distFile
          }
        } else if (format === 'es') {
          if (isDts) {
            esmTypes = distFile
          } else {
            module = distFile
          }
        }
      } else if (name.endsWith('/index')) {
        name = `./${name.slice(0, -6)}`
      } else {
        name = `./${name}`
      }

      if (extensions && name !== '.') {
        name = `${name}.js`
      }

      let subExport = exportsMap.get(name)
      if (!subExport) {
        subExport = {}
        exportsMap.set(name, subExport)
      }

      if (!isDts) {
        subExport[format] = distFile
        if (chunk.facadeModuleId && !subExport.src) {
          subExport.src = `./${slash(path.relative(pkgRoot, chunk.facadeModuleId))}`
        }
      }
    }
  }

  const sortedExportsMap = [...exportsMap].toSorted(([a], [b]) => {
    if (a === 'index') return -1
    return a.localeCompare(b)
  })

  let exports: Record<string, any> = Object.fromEntries(
    sortedExportsMap.map(([name, subExport]) => [
      name,
      genSubExport(devExports, subExport),
    ]),
  )
  exportMeta(exports, all, packageJson)
  exportCss(exports, chunks, css, pkgRoot)
  if (typeof customExports === 'object') {
    exports = { ...exports, ...customExports }
  } else if (typeof customExports === 'function') {
    exports = await customExports(exports, {
      pkg,
      chunks,
      isPublish: false,
    })
  }

  let publishExports: Record<string, any> | undefined
  if (devExports) {
    publishExports = Object.fromEntries(
      sortedExportsMap.map(([name, subExport]) => [
        name,
        genSubExport(false, subExport),
      ]),
    )
    exportMeta(publishExports, all, packageJson)
    exportCss(publishExports, chunks, css, pkgRoot)
    if (typeof customExports === 'object') {
      publishExports = { ...publishExports, ...customExports }
    } else if (typeof customExports === 'function') {
      publishExports = await customExports(publishExports, {
        pkg,
        chunks,
        isPublish: true,
      })
    }
  }

  const binResult = generateBin(
    bin,
    !!devExports,
    pkg,
    chunks,
    pkgRoot,
    logger,
    cwd,
  )
  const publishBin =
    devExports && binResult
      ? generateBin(bin, false, pkg, chunks, pkgRoot, logger, cwd)
      : undefined

  return {
    main: legacy ? main || module || pkg.main : undefined,
    module: legacy ? module || pkg.module : undefined,
    types: legacy ? cjsTypes || esmTypes || pkg.types : pkg.types,
    exports,
    bin: binResult,
    publishBin,
    inlinedDependencies: emitInlinedDeps ? inlinedDeps : undefined,
    publishExports,
  }
}

function genSubExport(
  devExports: string | boolean | undefined,
  { src, es, cjs }: SubExport,
) {
  if (devExports === true) {
    return src!
  }

  let value: any
  const dualFormat = es && cjs
  if (!dualFormat && !devExports) {
    value = cjs || es
  } else {
    value = {}
    if (typeof devExports === 'string') {
      value[devExports] = src
    }
    if (es) value[dualFormat ? 'import' : 'default'] = es
    if (cjs) value[dualFormat ? 'require' : 'default'] = cjs
  }

  return value
}

function exportMeta(
  exports: Record<string, any>,
  all?: boolean,
  packageJson?: boolean,
) {
  if (all) {
    exports['./*'] = './*'
  } else if (packageJson) {
    exports['./package.json'] = './package.json'
  }
}

function exportCss(
  exports: Record<string, any>,
  chunks: ChunksByFormat,
  css: { splitting?: boolean } | undefined,
  pkgRoot: string,
) {
  if (css?.splitting) return

  for (const chunksByFormat of Object.values(chunks)) {
    for (const chunk of chunksByFormat) {
      if (chunk.type === 'asset' && RE_CSS.test(chunk.fileName)) {
        const filename = slash(chunk.fileName)
        exports[`./${filename}`] = join(pkgRoot, chunk.outDir, filename)
        return
      }
    }
  }
}

export function hasExportsTypes(value: unknown): boolean {
  if (value == null || typeof value !== 'object') return false
  if (Array.isArray(value)) return value.some(hasExportsTypes)
  if ('types' in value) return true
  return Object.values(value).some(hasExportsTypes)
}

const RE_SHEBANG = /^#!.*/

function generateBin(
  bin: ExportsOptions['bin'],
  devExports: boolean,
  pkg: PackageJson,
  chunks: ChunksByFormat,
  pkgRoot: string,
  logger: Logger,
  cwd: string,
): string | Record<string, string> | undefined {
  if (bin === false) return

  if (bin === true || bin === undefined || typeof bin === 'string') {
    if (!pkg.name)
      throw new Error(
        'Package name is required when using string form for `bin`',
      )

    const binName = pkg.name[0] === '@' ? pkg.name.split('/', 2)[1] : pkg.name

    if (bin === true || bin === undefined) {
      let detected: string | undefined
      const seen = new Set<string>()

      for (const format of ['es', 'cjs'] as const) {
        const formatChunks = chunks[format]
        if (!formatChunks) continue
        for (const chunk of formatChunks) {
          if (chunk.type !== 'chunk' || !chunk.isEntry || !chunk.facadeModuleId)
            continue
          if (!RE_SHEBANG.test(chunk.code)) continue
          if (seen.has(chunk.facadeModuleId)) continue
          seen.add(chunk.facadeModuleId)

          if (detected) {
            if (bin === true) {
              throw new Error(
                'Multiple entry chunks with shebangs found. Use `exports.bin: { command: "./src/file.ts" }` to specify which one to use.',
              )
            }
            logger.warn(
              'Multiple entry chunks with shebangs found. Use `exports.bin: true` or `exports.bin: { command: "./src/file.ts" }` to configure explicitly.',
            )
            return
          }
          detected = devExports
            ? `./${slash(path.relative(pkgRoot, chunk.facadeModuleId))}`
            : join(pkgRoot, chunk.outDir, slash(chunk.fileName))
        }
      }

      if (detected == null) {
        if (bin === true) {
          logger.warn(
            '`exports.bin` is true but no entry chunks with shebangs were found',
          )
        }
        return
      }
      return { [binName]: detected }
    }

    if (typeof bin === 'string') {
      const match = findChunkBySource(bin)
      if (!match) {
        throw new Error(`Could not find output chunk for bin entry "${bin}"`)
      }
      return { [binName]: devExports ? normalizeSource(bin) : match }
    }
  }

  // Object form: { commandName: './src/file.ts' }
  const result: Record<string, string> = {}
  for (const [cmdName, sourcePath] of Object.entries(bin)) {
    const match = findChunkBySource(sourcePath)
    if (!match) {
      throw new Error(
        `Could not find output chunk for bin entry "${cmdName}": "${sourcePath}"`,
      )
    }
    result[cmdName] = devExports ? normalizeSource(sourcePath) : match
  }
  return result

  function normalizeSource(sourcePath: string): string {
    const resolved = path.resolve(cwd, sourcePath)
    return `./${slash(path.relative(pkgRoot, resolved))}`
  }

  function findChunkBySource(sourcePath: string): string | undefined {
    const resolved = path.resolve(cwd, sourcePath)

    for (const format of ['es', 'cjs'] as const) {
      const formatChunks = chunks[format]
      if (!formatChunks) continue
      for (const chunk of formatChunks) {
        if (chunk.type !== 'chunk' || !chunk.isEntry) continue
        if (chunk.facadeModuleId !== resolved) continue

        if (!RE_SHEBANG.test(chunk.code)) {
          logger.warn(
            `Bin entry "${sourcePath}" does not contain a shebang line`,
          )
        }
        return join(pkgRoot, chunk.outDir, slash(chunk.fileName))
      }
    }
  }
}

function getExportName(
  chunk: RolldownCodeChunk,
): [name: string, normalizedName: string, isDts: boolean] {
  const normalizedName = slash(chunk.fileName)
  let name = stripExtname(normalizedName)

  const isDts = name.endsWith('.d')
  if (isDts) {
    name = name.slice(0, -2)
  }

  return [name, normalizedName, isDts] as const
}

function join(pkgRoot: string, outDir: string, fileName: string) {
  const outDirRelative = slash(path.relative(pkgRoot, outDir))
  return `${outDirRelative ? `./${outDirRelative}` : '.'}/${fileName}`
}
