export enum ExtractorMessageId {
  ExtraReleaseTag = 'ae-extra-release-tag',
  Undocumented = 'ae-undocumented',
  DifferentReleaseTags = 'ae-different-release-tags',
  IncompatibleReleaseTags = 'ae-incompatible-release-tags',
  MissingReleaseTag = 'ae-missing-release-tag',
  MisplacedPackageTag = 'ae-misplaced-package-tag',
  ForgottenExport = 'ae-forgotten-export',
  InternalMissingUnderscore = 'ae-internal-missing-underscore',
  InternalMixedReleaseTag = 'ae-internal-mixed-release-tag',
  PreapprovedUnsupportedType = 'ae-preapproved-unsupported-type',
  PreapprovedBadReleaseTag = 'ae-preapproved-bad-release-tag',
  UnresolvedInheritDocReference = 'ae-unresolved-inheritdoc-reference',
  UnresolvedInheritDocBase = 'ae-unresolved-inheritdoc-base',
  CyclicInheritDoc = 'ae-cyclic-inherit-doc',
  UnresolvedLink = 'ae-unresolved-link',
  SetterWithDocs = 'ae-setter-with-docs',
  MissingGetter = 'ae-missing-getter',
  UnresolvedImportPath = 'ae-unresolved-import-path',
  WrongInputFileType = 'ae-wrong-input-file-type',
}

export const allExtractorMessageIds: ReadonlySet<string> = new Set<string>([
  'ae-extra-release-tag',
  'ae-undocumented',
  'ae-different-release-tags',
  'ae-incompatible-release-tags',
  'ae-missing-release-tag',
  'ae-misplaced-package-tag',
  'ae-forgotten-export',
  'ae-internal-missing-underscore',
  'ae-internal-mixed-release-tag',
  'ae-preapproved-unsupported-type',
  'ae-preapproved-bad-release-tag',
  'ae-unresolved-inheritdoc-reference',
  'ae-unresolved-inheritdoc-base',
  'ae-cyclic-inherit-doc',
  'ae-unresolved-link',
  'ae-setter-with-docs',
  'ae-missing-getter',
  'ae-unresolved-import-path',
  'ae-wrong-input-file-type',
])
